<?php
$section=array();
$sectionName=array();
$topics=array();
$tags=array();
$page=array();
$slideRoot='img';
$slideExt='.png';

$slide[0]='Welcome '; $slideName[0]='Welcome'; $slidePage['Welcome']='0'; $slideTags[0]='welcome home'; $slideTopics[0]='';
$slide[1]='Functional'; $slideName[1]='Functional '; $slidePage['Functional1']='1'; $slideTags[1]='functional'; $slideTopics[1]='Ticket Activity Milestone Action Planning Workload Cost Report';
$slide[2]='Functional'; $slideName[2]='Functional (2)'; $slidePage['Functional2']='2'; $slideTags[2]='functional'; $slideTopics[2]='Expense Bill Risk Action Issue Meeting Decision Question Message Import ';
$slide[3]='Functional'; $slideName[3]='Functional (3)'; $slidePage['Functional3']='3'; $slideTags[3]='functional'; $slideTopics[3]='Client User Resource AccessRight Calendar';
$slide[4]='Functional'; $slideName[4]='Functional (4)'; $slidePage['Functional4']='4'; $slideTags[4]='functional'; $slideTopics[4]='Document Requirement Test Parameter';
$slide[5]='Functional'; $slideName[5]='Functional (5)'; $slidePage['Functional5']='5'; $slideTags[5]='functional'; $slideTopics[5]='AccessProfile GuiFilter';
$slide[6]='Technical'; $slideName[6]='Technical'; $slidePage['Technical1']='6'; $slideTags[6]='technical gui interface ajax browser'; $slideTopics[6]='GuiGenerality';
$slide[7]='Technical'; $slideName[7]='Technical (2)'; $slidePage['Technical2']='7'; $slideTags[7]='install setup deploy'; $slideTopics[7]='Installation';
$slide[8]='Technical'; $slideName[8]='Technical (3)'; $slidePage['Technical3']='8'; $slideTags[8]='parameter'; $slideTopics[8]='Parameters1';
$slide[9]='Installation'; $slideName[9]='Installation'; $slidePage['Installation']='9'; $slideTags[9]='install setup deploy php mysql http server zip'; $slideTopics[9]='Configuration Parameters1 NewVersion Connection';
$slide[10]='Configuration'; $slideName[10]='Configuration'; $slidePage['Configuration']='10'; $slideTags[10]='install setup config parameter'; $slideTopics[10]='Installation Parameters1 NewVersion Connection';
$slide[11]='Parameters'; $slideName[11]='Parameters'; $slidePage['Parameters1']='11'; $slideTags[11]='config parameter install setup'; $slideTopics[11]='Installation Configuration NewVersion';
$slide[12]='Parameters'; $slideName[12]='Parameters (2)'; $slidePage['Parameters2']='12'; $slideTags[12]='config parameter install setup'; $slideTopics[12]='Installation Configuration NewVersion';
$slide[13]='Parameters'; $slideName[13]='Parameters (3)'; $slidePage['Parameters3']='13'; $slideTags[13]='config parameter install setup'; $slideTopics[13]='Installation Configuration NewVersion';
$slide[14]='Parameters'; $slideName[14]='Parameters (4)'; $slidePage['Parameters4']='14'; $slideTags[14]='config parameter install setup'; $slideTopics[14]='Installation Configuration NewVersion';
$slide[15]='Parameters'; $slideName[15]='Parameters (5)'; $slidePage['Parameters5']='15'; $slideTags[15]='config parameter install setup'; $slideTopics[15]='Installation Configuration NewVersion';
$slide[16]='NewVersion'; $slideName[16]='Install new version'; $slidePage['NewVersion']='16'; $slideTags[16]='install setup deploy php mysql http server zip new version release update'; $slideTopics[16]='Installation Configuration Parameters1';
$slide[17]='Connection'; $slideName[17]='Connection'; $slidePage['Connection']='17'; $slideTags[17]='connect login'; $slideTopics[17]='GuiGenerality Installation Configuration';
$slide[18]='GUI'; $slideName[18]='User interface'; $slidePage['GuiGenerality']='18'; $slideTags[18]='gui interface'; $slideTopics[18]='Themes GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[19]='GUI'; $slideName[19]='Toolbars'; $slidePage['GuiToolbar']='19'; $slideTags[19]='gui interface toolbar show hide switch help manual hyperlink logo external-shortcuts shortcuts'; $slideTopics[19]='Themes GuiGenerality GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[20]='GUI'; $slideName[20]='Menu'; $slidePage['GuiMenu']='20'; $slideTags[20]='gui interface menu project combo'; $slideTopics[20]='Themes GuiGenerality GuiToolbar GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[21]='GUI'; $slideName[21]='Quick Menu'; $slidePage['GuiQuickMenu']='21'; $slideTags[21]='gui interface menu project combo'; $slideTopics[21]='Themes GuiGenerality GuiToolbar GuiMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[22]='GUI'; $slideName[22]='List'; $slidePage['GuiList']='22'; $slideTags[22]='gui interface list column'; $slideTopics[22]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[23]='GUI'; $slideName[23]='Filter'; $slidePage['GuiFilter']='23'; $slideTags[23]='gui interface filter complex'; $slideTopics[23]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[24]='GUI'; $slideName[24]='ListParameter'; $slidePage['GuiListParameters']='24'; $slideTags[24]='gui interface list order selection width'; $slideTopics[24]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[25]='GUI'; $slideName[25]='Detail'; $slidePage['GuiDetail']='25'; $slideTags[25]='gui interface detail item save print'; $slideTopics[25]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiCombo GuiAlert GuiProject';
$slide[26]='GUI'; $slideName[26]='Combo detail'; $slidePage['GuiCombo']='26'; $slideTags[26]='gui interface detail item save print combo list'; $slideTopics[26]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail  GuiAlert GuiProject';
$slide[27]='GUI'; $slideName[27]='Alert'; $slidePage['GuiAlert']='27'; $slideTags[27]='gui interface detail item save print combo list alert info warning'; $slideTopics[27]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiProject';
$slide[28]='Themes'; $slideName[28]='Themes'; $slidePage['Themes']='28'; $slideTags[28]='theme color'; $slideTopics[28]='GuiGenerality ThemesTemplates';
$slide[29]='Themes'; $slideName[29]='Themes templates'; $slidePage['ThemesTemplates']='29'; $slideTags[29]='theme color example'; $slideTopics[29]='GuiGenerality Themes';
$slide[30]='Multilingual'; $slideName[30]='Multilingual'; $slidePage['Multilingual']='30'; $slideTags[30]='english french german translat multiling'; $slideTopics[30]='GuiGenerality Configuration Parameters1';
$slide[31]='Creation'; $slideName[31]='Creation'; $slidePage['Creation']='31'; $slideTags[31]='creation'; $slideTopics[31]='GuiGenerality Update Delete Copy';
$slide[32]='Update'; $slideName[32]='Update'; $slidePage['Update']='32'; $slideTags[32]='update'; $slideTopics[32]='GuiGenerality Creation Delete copy';
$slide[33]='Delete'; $slideName[33]='Delete'; $slidePage['Delete']='33'; $slideTags[33]='delete'; $slideTopics[33]='GuiGenerality Creation Update Copy';
$slide[34]='Copy'; $slideName[34]='Copy'; $slidePage['Copy']='34'; $slideTags[34]='copy'; $slideTopics[34]='GuiGenerality Creation Update Delete';
$slide[35]='MultipleUpdate'; $slideName[35]='Multiple Update'; $slidePage['MultipleUpdate']='35'; $slideTags[35]='multiple update several grouped'; $slideTopics[35]='GuiGenerality Update';
$slide[36]='Today'; $slideName[36]='Today'; $slidePage['Today']='36'; $slideTags[36]='today summary todo message'; $slideTopics[36]='Message Project Ticket Activity Milestone Risk Action Issue';
$slide[37]='Today'; $slideName[37]='Today parameters'; $slidePage['TodayParameters']='37'; $slideTags[37]='today summary todo message'; $slideTopics[37]='Message Project Ticket Activity Milestone Risk Action Issue Report';
$slide[38]='Project'; $slideName[38]='Project'; $slidePage['Project']='38'; $slideTags[38]='project planning sub-project'; $slideTopics[38]='ProjectFields ProjectProgress ProjectAffectation ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[39]='Project'; $slideName[39]='Project fields'; $slidePage['ProjectFields']='39'; $slideTags[39]='project planning sub-project hyperlink external-shortcuts shortcuts'; $slideTopics[39]='Project ProjectAffectation ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning Affectation Customer';
$slide[40]='Project'; $slideName[40]='Project affectations and versions'; $slidePage['ProjectAffectation']='40'; $slideTags[40]='project planning affectation version'; $slideTopics[40]='Project ProjectFields ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[41]='Project'; $slideName[41]='Project progress'; $slidePage['ProjectProgress']='41'; $slideTags[41]='project planning'; $slideTopics[41]='Project ProjectFields ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[42]='Project'; $slideName[42]='Project dependencies'; $slidePage['ProjectDependencies']='42'; $slideTags[42]='project planning'; $slideTopics[42]='Project ProjectFields ProjectProgress ProjectAffectation GuiGenerality Creation Update Delete Planning';
$slide[43]='Document'; $slideName[43]='Document'; $slidePage['Document']='43'; $slideTags[43]='document directory file'; $slideTopics[43]='DocumentFields DocumentVersions DocumentDirectory DocumentApprovers Product Project';
$slide[44]='Document'; $slideName[44]='Document fields'; $slidePage['DocumentFields']='44'; $slideTags[44]='document directory file'; $slideTopics[44]='Document DocumentVersions DocumentDirectory DocumentApprovers Product Project LinkedElements';
$slide[45]='Document'; $slideName[45]='Document versions'; $slidePage['DocumentVersions']='45'; $slideTags[45]='document directory file version'; $slideTopics[45]='Document DocumentFields DocumentDirectory DocumentApprovers Product Project';
$slide[46]='Document'; $slideName[46]='Document approvers'; $slidePage['DocumentApprovers']='46'; $slideTags[46]='document directory file version approvers approve'; $slideTopics[46]='Document DocumentFields DocumentDirectory DocumentVersion Product Project';
$slide[47]='Ticket'; $slideName[47]='Ticket'; $slidePage['Ticket']='47'; $slideTags[47]='ticket bug task track'; $slideTopics[47]='TicketFields TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[48]='Ticket'; $slideName[48]='Ticket fields'; $slidePage['TicketFields']='48'; $slideTags[48]='ticket bug task track'; $slideTopics[48]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[49]='Ticket'; $slideName[49]='Ticket fields'; $slidePage['TicketFields2']='49'; $slideTags[49]='ticket bug task track work timer'; $slideTopics[49]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[50]='TicketSimple'; $slideName[50]='Simple Ticket'; $slidePage['TicketSimple']='50'; $slideTags[50]='ticket bug task track simple'; $slideTopics[50]='TicketSimpleFields Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[51]='TicketSimple'; $slideName[51]='Simple Ticket fields'; $slidePage['TicketSimpleFields']='51'; $slideTags[51]='ticket bug task track simple'; $slideTopics[51]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[52]='TicketSimple'; $slideName[52]='Simple Ticket fields'; $slidePage['TicketSimpleFields2']='52'; $slideTags[52]='ticket bug task track simple'; $slideTopics[52]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[53]='Activity'; $slideName[53]='Activity'; $slidePage['Activity']='53'; $slideTags[53]='activity task planning'; $slideTopics[53]='ActivityFields ActivityAssignment ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[54]='Activity'; $slideName[54]='Activity fields'; $slidePage['ActivityFields']='54'; $slideTags[54]='activity task planning'; $slideTopics[54]='Activity ActivityAssignement ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[55]='Activity'; $slideName[55]='Activity assignment'; $slidePage['ActivityAssignement']='55'; $slideTags[55]='activity task planning assignment'; $slideTopics[55]='Activity ActivityFields ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[56]='Activity'; $slideName[56]='Activity progress'; $slidePage['ActivityProgress']='56'; $slideTags[56]='activity task planning progress'; $slideTopics[56]='Activity ActivityFields ActivityAssignment ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[57]='Activity'; $slideName[57]='Activity dependency'; $slidePage['ActivityDependencies']='57'; $slideTags[57]='activity task planning'; $slideTopics[57]='Activity ActivityFields ActivityAssignment ActivityProgress GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[58]='Milestone'; $slideName[58]='Milestone'; $slidePage['Milestone']='58'; $slideTags[58]='milestone flag '; $slideTopics[58]='MilestoneFields MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[59]='Milestone'; $slideName[59]='Milestone fields'; $slidePage['MilestoneFields']='59'; $slideTags[59]='milestone flag '; $slideTopics[59]='Milestone MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[60]='Milestone'; $slideName[60]='Milestone progress'; $slidePage['MilestoneProgress']='60'; $slideTags[60]='milestone flag '; $slideTopics[60]='Milestone MilestoneFields MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[61]='Milestone'; $slideName[61]='Milestone dependencies'; $slidePage['MilestoneDependencies']='61'; $slideTags[61]='milestone flag '; $slideTopics[61]='Milestone MilestoneFields MilestoneProgress GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[62]='Action'; $slideName[62]='Action'; $slidePage['Action']='62'; $slideTags[62]='risk action issue'; $slideTopics[62]='ActionFields Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[63]='Action'; $slideName[63]='Action fields'; $slidePage['ActionFields']='63'; $slideTags[63]='risk action issue'; $slideTopics[63]='Action Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[64]='Imputation'; $slideName[64]='Real work allocation'; $slidePage['Imputation']='64'; $slideTags[64]='imputation work follow-up allocation'; $slideTopics[64]='Activity ActivityAssignement Planning Resource Project Affectation';
$slide[65]='Planning'; $slideName[65]='Planning'; $slidePage['Planning1']='65'; $slideTags[65]='planning work plan date calculation gantt'; $slideTopics[65]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[66]='Planning'; $slideName[66]='Planning (2)'; $slidePage['Planning2']='66'; $slideTags[66]='planning work plan date calculation gantt'; $slideTopics[66]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[67]='Planning'; $slideName[67]='Planning (3)'; $slidePage['Planning3']='67'; $slideTags[67]='planning work plan date calculation gantt'; $slideTopics[67]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[68]='Planning'; $slideName[68]='Planning (4)'; $slidePage['Planning4']='68'; $slideTags[68]='planning work plan date calculation gantt'; $slideTopics[68]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[69]='Planning'; $slideName[69]='Planning (5)'; $slidePage['Planning5']='69'; $slideTags[69]='planning work plan date calculation gantt'; $slideTopics[69]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[70]='PortfolioPlanning'; $slideName[70]='Projects portfolio'; $slidePage['PortfolioPlanning']='70'; $slideTags[70]='planning gantt portfolio'; $slideTopics[70]='Planning';
$slide[71]='ResourcePlanning'; $slideName[71]='Resource Planning'; $slidePage['ResourcePlanning']='71'; $slideTags[71]='planning work plan date calculation gantt resource'; $slideTopics[71]='ActivityAssignement ActivityProgress ActivityDependencies Planning';
$slide[72]='Report'; $slideName[72]='Report'; $slidePage['Report']='72'; $slideTags[72]='parameter report print '; $slideTopics[72]='';
$slide[73]='Requirement'; $slideName[73]='Requirement'; $slidePage['Requirement']='73'; $slideTags[73]='requirement'; $slideTopics[73]='RequirementFields TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[74]='Requirement'; $slideName[74]='Requirement fields'; $slidePage['RequirementFields']='74'; $slideTags[74]='requirement'; $slideTopics[74]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[75]='Requirement'; $slideName[75]='Requirement fields'; $slidePage['RequirementFields2']='75'; $slideTags[75]='requirement'; $slideTopics[75]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[76]='TestCase'; $slideName[76]='Test case'; $slidePage['TestCase']='76'; $slideTags[76]='test case'; $slideTopics[76]='TestCaseFields Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[77]='TestCase'; $slideName[77]='Test case fields'; $slidePage['TestCaseFields']='77'; $slideTags[77]='test case'; $slideTopics[77]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[78]='TestCase'; $slideName[78]='Test case fields'; $slidePage['TestCaseFields2']='78'; $slideTags[78]='test case'; $slideTopics[78]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[79]='TestSession'; $slideName[79]='Test session'; $slidePage['TestSession']='79'; $slideTags[79]='test session'; $slideTopics[79]='TestSessionFields Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[80]='TestSession'; $slideName[80]='Test session fields'; $slidePage['TestSessionFields']='80'; $slideTags[80]='test session'; $slideTopics[80]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[81]='TestSession'; $slideName[81]='Test session fields'; $slidePage['TestSessionFields2']='81'; $slideTags[81]='test session'; $slideTopics[81]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[82]='Command'; $slideName[82]='Order'; $slidePage['Command']='82'; $slideTags[82]='order bill command'; $slideTopics[82]='activity';
$slide[83]='Command'; $slideName[83]='Order fields'; $slidePage['CommandFields']='83'; $slideTags[83]='order bill command'; $slideTopics[83]='activity';
$slide[84]='IndividualExpense'; $slideName[84]='Individual expense'; $slidePage['IndividualExpense']='84'; $slideTags[84]='expense cost travel '; $slideTopics[84]='IndividualExpenseFields IndividualExpenseDetails ProjectExpense';
$slide[85]='IndividualExpense'; $slideName[85]='Individual expense fields'; $slidePage['IndividualExpenseFields']='85'; $slideTags[85]='expense cost travel '; $slideTopics[85]='IndividualExpense IndividualExpenseDetails ProjectExpense';
$slide[86]='IndividualExpense'; $slideName[86]='Individual expense details'; $slidePage['IndividualExpenseDetails']='86'; $slideTags[86]='expense cost travel detail'; $slideTopics[86]='IndividualExpenseFields IndividualExpense ProjectExpense';
$slide[87]='ProjectExpense'; $slideName[87]='Project expense'; $slidePage['ProjectExpense']='87'; $slideTags[87]='expense'; $slideTopics[87]='ProjectExpenseFields IndividualExpense';
$slide[88]='ProjectExpense'; $slideName[88]='Project expense fields'; $slidePage['ProjectExpenseFields']='88'; $slideTags[88]='expense'; $slideTopics[88]='ProjectExpense IndividualExpense';
$slide[89]='Term'; $slideName[89]='Term'; $slidePage['Term']='89'; $slideTags[89]='term trigger bill fixed price'; $slideTopics[89]='TermFileds Bill';
$slide[90]='Term'; $slideName[90]='Term fields'; $slidePage['TermFields']='90'; $slideTags[90]='term trigger bill fixed price'; $slideTopics[90]='Term Bill';
$slide[91]='Bill'; $slideName[91]='Bill'; $slidePage['Bill']='91'; $slideTags[91]='bill billing'; $slideTopics[91]='Term Bill ActivityPrice BillingType BillType';
$slide[92]='Bill'; $slideName[92]='Bill fields'; $slidePage['BillFields']='92'; $slideTags[92]='bill billing'; $slideTopics[92]='Term Bill ActivityPrice BillingType BillType Recipient Contact';
$slide[93]='Bill'; $slideName[93]='Bill lines'; $slidePage['BillLines']='93'; $slideTags[93]='risk action issue opportunity'; $slideTopics[93]='Term Bill ActivityPrice BillingType BillType';
$slide[94]='ActivityPrice'; $slideName[94]='Activity price'; $slidePage['ActivityPrice']='94'; $slideTags[94]='risk action issue opportunity'; $slideTopics[94]='Activity ActivityType BillingType';
$slide[95]='Risk'; $slideName[95]='Risk'; $slidePage['Risk']='95'; $slideTags[95]='risk action issue'; $slideTopics[95]='RiskFields Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[96]='Risk'; $slideName[96]='Risk fields'; $slidePage['RiskFields']='96'; $slideTags[96]='risk action issue'; $slideTopics[96]='Risk Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[97]='Opportunity'; $slideName[97]='Opportunity'; $slidePage['Opportunity']='97'; $slideTags[97]='meeting workshop steering committee invitation attendees'; $slideTopics[97]='OpportunityFields Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[98]='Opportunity'; $slideName[98]='Opportunity fields'; $slidePage['OpportunityFields']='98'; $slideTags[98]='meeting workshop steering committee'; $slideTopics[98]='Opportunity Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[99]='Issue'; $slideName[99]='Issue'; $slidePage['Issue']='99'; $slideTags[99]='risk action issue'; $slideTopics[99]='IssueFields IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[100]='Issue'; $slideName[100]='Issue fields'; $slidePage['IssueFields']='100'; $slideTags[100]='risk action issue'; $slideTopics[100]='Issue IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[101]='Meeting'; $slideName[101]='Meeting'; $slidePage['Meeting']='101'; $slideTags[101]='meeting workshop steering committee invitation attendees'; $slideTopics[101]='MeetingFields MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[102]='Meeting'; $slideName[102]='Meeting fields'; $slidePage['MeetingFields']='102'; $slideTags[102]='meeting workshop steering committee'; $slideTopics[102]='Meeting MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[103]='PeriodicMeeting'; $slideName[103]='Periodic meeting'; $slidePage['PeriodicMeeting']='103'; $slideTags[103]='meeting workshop steering committee invitation attendees periodic'; $slideTopics[103]='PeriodicMeetingFields Meeting MeetingType';
$slide[104]='PeriodicMeeting'; $slideName[104]='Periodic meeting fields'; $slidePage['PeriodicMeetingFields']='104'; $slideTags[104]='meeting workshop steering committee periodic'; $slideTopics[104]='PeriodicMeeting Meeting MeetingType';
$slide[105]='Decision'; $slideName[105]='Decision'; $slidePage['Decision']='105'; $slideTags[105]='decision'; $slideTopics[105]='DecisionFields DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[106]='Decision'; $slideName[106]='Decision fields'; $slidePage['DecisionFields']='106'; $slideTags[106]='decision'; $slideTopics[106]='Decision DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[107]='Question'; $slideName[107]='Question'; $slidePage['Question']='107'; $slideTags[107]='question answer'; $slideTopics[107]='QuestionFields QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[108]='Question'; $slideName[108]='Question fields'; $slidePage['QuestionFields']='108'; $slideTags[108]='question answer'; $slideTopics[108]='Question QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[109]='Mail'; $slideName[109]='Emails'; $slidePage['Mail']='109'; $slideTags[109]='email mail'; $slideTopics[109]='AutomaticEmailing';
$slide[110]='Alert'; $slideName[110]='Alerts'; $slidePage['Alert']='110'; $slideTags[110]='alert warning information indicator'; $slideTopics[110]='GuiAlert IndicatorDefinition';
$slide[111]='Message'; $slideName[111]='Message'; $slidePage['Message']='111'; $slideTags[111]='message alert'; $slideTopics[111]='User Project Profile Today';
$slide[112]='Import'; $slideName[112]='Import'; $slidePage['Import']='112'; $slideTags[112]='import load'; $slideTopics[112]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[113]='Import'; $slideName[113]='Import Run'; $slidePage['ImportRun']='113'; $slideTags[113]='import load'; $slideTopics[113]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[114]='AutomaticImport'; $slideName[114]='Automatic Import'; $slidePage['AutomaticImport']='114'; $slideTags[114]='automatic automated import cron'; $slideTopics[114]='Import GlobalParameter';
$slide[115]='Affectation'; $slideName[115]='Affectation'; $slidePage['Affectation']='115'; $slideTags[115]='affectation resource contact user project'; $slideTopics[115]='GuiGenerality Resource Contact User Project';
$slide[116]='User'; $slideName[116]='User'; $slidePage['User']='116'; $slideTags[116]='contact resource user login password'; $slideTopics[116]='GuiGenerality Contact Resource UserAffectation';
$slide[117]='User'; $slideName[117]='User affectations'; $slidePage['UserAffectation']='117'; $slideTags[117]='contact resource user login password affectation'; $slideTopics[117]='GuiGenerality Contact Resource User';
$slide[118]='Resource'; $slideName[118]='Resource description'; $slidePage['Resource']='118'; $slideTags[118]='resource capacity affectation'; $slideTopics[118]='ResourceCost GuiGenerality User Contact Team Planning Affectation';
$slide[119]='Resource'; $slideName[119]='Resource function cost & affectation'; $slidePage['ResourceCost']='119'; $slideTags[119]='resource capacity affectation cost'; $slideTopics[119]='GuiGenerality User Contact Team Planning Affectation Resource';
$slide[120]='Contact'; $slideName[120]='Contact'; $slidePage['Contact']='120'; $slideTags[120]='contact customer requestor'; $slideTopics[120]='Client User GuiGenerality Creation Update Delete AutomaticEmailing ContactAffectation';
$slide[121]='Contact'; $slideName[121]='Contact affectations'; $slidePage['ContactAffectation']='121'; $slideTags[121]='contact customer requestor affectation'; $slideTopics[121]='Client User GuiGenerality Creation Update Delete AutomaticEmailing Contact';
$slide[122]='Client'; $slideName[122]='Customer'; $slidePage['Client']='122'; $slideTags[122]='client customer contact'; $slideTopics[122]='Contact Project GuiGenerality Creation Update Delete';
$slide[123]='Recipient'; $slideName[123]='Recipient'; $slidePage['Recipient']='123'; $slideTags[123]='recipient bill'; $slideTopics[123]='Bill';
$slide[124]='Team'; $slideName[124]='Team'; $slidePage['Team']='124'; $slideTags[124]='team resource affectation'; $slideTopics[124]='GuiGenerality Resource';
$slide[125]='Product'; $slideName[125]='Product'; $slidePage['Product']='125'; $slideTags[125]='product version'; $slideTopics[125]='Version Project Customer Contact';
$slide[126]='Version'; $slideName[126]='Version'; $slidePage['Version']='126'; $slideTags[126]='product version'; $slideTopics[126]='Product Project Customer Contact';
$slide[127]='Context'; $slideName[127]='Context'; $slidePage['Context']='127'; $slideTags[127]='context environment os browser'; $slideTopics[127]='Ticket TranslatableName';
$slide[128]='Calendar'; $slideName[128]='Calendar'; $slidePage['Calendar']='128'; $slideTags[128]='calendar off open closed day'; $slideTopics[128]='GuiGenerality Planning';
$slide[129]='Calendar'; $slideName[129]='Calendar description'; $slidePage['CalendarDescription']='129'; $slideTags[129]='calendar off open closed day'; $slideTopics[129]='GuiGenerality Planning';
$slide[130]='DocumentDirectory'; $slideName[130]='Document directory'; $slidePage['DocumentDirectory']='130'; $slideTags[130]='document directory folder place'; $slideTopics[130]='Document';
$slide[131]='Role'; $slideName[131]='Function'; $slidePage['Role']='131'; $slideTags[131]='function resource cost'; $slideTopics[131]='GuiGenerality Resource';
$slide[132]='Status'; $slideName[132]='Status'; $slidePage['Status']='132'; $slideTags[132]='status workflow lifecycle'; $slideTopics[132]='Workflow Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[133]='Quality'; $slideName[133]='Quality level'; $slidePage['Quality']='133'; $slideTags[133]='quality'; $slideTopics[133]='Project Today';
$slide[134]='HealthStatus'; $slideName[134]='Health Status'; $slidePage['HealthStatus']='134'; $slideTags[134]='health'; $slideTopics[134]='Project Today';
$slide[135]='OverallProgress'; $slideName[135]='Overall Progress'; $slidePage['OverallProgress']='135'; $slideTags[135]='progress'; $slideTopics[135]='Project Today';
$slide[136]='Trend'; $slideName[136]='Trend'; $slidePage['Trend']='136'; $slideTags[136]='trend'; $slideTopics[136]='Project Today';
$slide[137]='Likelihood'; $slideName[137]='Likelihood'; $slidePage['Likelihood']='137'; $slideTags[137]='likelihood probability'; $slideTopics[137]='GuiGenerality criticality severity risk';
$slide[138]='Criticality'; $slideName[138]='Criticality'; $slidePage['Criticality']='138'; $slideTags[138]='criticality'; $slideTopics[138]='GuiGenerality risk ticket likelihood severity priority urgency';
$slide[139]='Severity'; $slideName[139]='Severity'; $slidePage['Severity']='139'; $slideTags[139]='severity'; $slideTopics[139]='GuiGenerality risk criticality likelihood';
$slide[140]='Urgency'; $slideName[140]='Urgency'; $slidePage['Urgency']='140'; $slideTags[140]='urgency priority'; $slideTopics[140]='GuiGenerality ticket priority criticality';
$slide[141]='Priority'; $slideName[141]='Priority'; $slidePage['Priority']='141'; $slideTags[141]='priority urgency'; $slideTopics[141]='GuiGenerality urgency criticality ticket';
$slide[142]='RiskLevel'; $slideName[142]='Risk level'; $slidePage['RiskLevel']='142'; $slideTags[142]='risk level'; $slideTopics[142]='GuiGenerality';
$slide[143]='Feasibility'; $slideName[143]='Feasibility'; $slidePage['Feasibility']='143'; $slideTags[143]='feasibility'; $slideTopics[143]='GuiGenerality';
$slide[144]='Efficiency'; $slideName[144]='Efficiency'; $slidePage['Efficiency']='144'; $slideTags[144]='efficiency'; $slideTopics[144]='GuiGenerality Action';
$slide[145]='PredefinedNote'; $slideName[145]='Predefined note'; $slidePage['PredefinedNote']='145'; $slideTags[145]='predefined note text'; $slideTopics[145]='Notes';
$slide[146]='Workflow'; $slideName[146]='Workflow description'; $slidePage['Workflow']='146'; $slideTags[146]='workflow status'; $slideTopics[146]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[147]='Workflow'; $slideName[147]='Workflow table'; $slidePage['WorkflowTable']='147'; $slideTags[147]='workflow status'; $slideTopics[147]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[148]='StatusMail'; $slideName[148]='Mail on events'; $slidePage['StatusMail']='148'; $slideTags[148]='mail emailing status'; $slideTopics[148]='GuiGenerality Mail Status AutomaticEmailing ReplyToEmails';
$slide[149]='ReplyToEmail'; $slideName[149]='Reply to emails'; $slidePage['ReplyToEmail']='149'; $slideTags[149]='mail emailing reply'; $slideTopics[149]='GuiGenerality MailAutomaticEmailing';
$slide[150]='TicketDelay'; $slideName[150]='Delay for tickets'; $slidePage['TicketDelay']='150'; $slideTags[150]='delay ticket'; $slideTopics[150]='GuiGenerality Ticket';
$slide[151]='IndicatorDefinition'; $slideName[151]='Indicator'; $slidePage['IndicatorDefinition']='151'; $slideTags[151]='delay indicator alert warning'; $slideTopics[151]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[152]='ProjectType'; $slideName[152]='Project type'; $slidePage['ProjectType']='152'; $slideTags[152]='project type template administrative operational billing'; $slideTopics[152]='Project Bill';
$slide[153]='TicketType'; $slideName[153]='Ticket type'; $slidePage['TicketType']='153'; $slideTags[153]='type ticket'; $slideTopics[153]='Ticket GuiGenerality';
$slide[154]='ActivityType'; $slideName[154]='Activity type'; $slidePage['ActivityType']='154'; $slideTags[154]='activity type'; $slideTopics[154]='Activity GuiGenerality';
$slide[155]='MilestoneType'; $slideName[155]='Milestone type'; $slidePage['MilestoneType']='155'; $slideTags[155]='milestone type'; $slideTopics[155]='Milestone GuiGenerality';
$slide[156]='IndividualExpenseType'; $slideName[156]='Individual expense type'; $slidePage['IndividualExpenseType']='156'; $slideTags[156]='expense type'; $slideTopics[156]='IndividualExpense GuiGenerality';
$slide[157]='ProjectExpenseType'; $slideName[157]='Project expensetype'; $slidePage['ProjectExpenseType']='157'; $slideTags[157]='expense type'; $slideTopics[157]='ProjectExpense GuiGenerality';
$slide[158]='ExpenseDetailType'; $slideName[158]='Expense detail type'; $slidePage['ExpenseDetailType']='158'; $slideTags[158]='expense type'; $slideTopics[158]='IndividualExpense ProjectExpense GuiGenerality';
$slide[159]='BillType'; $slideName[159]='Bill type'; $slidePage['BillType']='159'; $slideTags[159]='bill type'; $slideTopics[159]='Bill GuiGenerality Creation Update Delete';
$slide[160]='RiskType'; $slideName[160]='Risk type'; $slidePage['RiskType']='160'; $slideTags[160]='risk type'; $slideTopics[160]='Risk GuiGenerality Creation Update Delete';
$slide[161]='RiskType'; $slideName[161]='Opportunity type'; $slidePage['Opportunity Type']='161'; $slideTags[161]='opportunity type'; $slideTopics[161]='Opportunity GuiGenerality Creation Update Delete';
$slide[162]='ActionType'; $slideName[162]='Action type'; $slidePage['ActionType']='162'; $slideTags[162]='action type'; $slideTopics[162]='Action GuiGenerality Creation Update Delete';
$slide[163]='IssueType'; $slideName[163]='Issue type'; $slidePage['IssueType']='163'; $slideTags[163]='issue type'; $slideTopics[163]='Issue GuiGenerality Creation Update Delete';
$slide[164]='MeetingType'; $slideName[164]='Meeting type'; $slidePage['MeetingType']='164'; $slideTags[164]='meeting type'; $slideTopics[164]='Meeting GuiGenerality Creation Update Delete';
$slide[165]='DecisionType'; $slideName[165]='Decision type'; $slidePage['DecisionType']='165'; $slideTags[165]='decision type'; $slideTopics[165]='Decision GuiGenerality Creation Update Delete';
$slide[166]='QuestionType'; $slideName[166]='Question type'; $slidePage['QuestionType']='166'; $slideTags[166]='question type'; $slideTopics[166]='Question GuiGenerality Creation Update Delete';
$slide[167]='MessageType'; $slideName[167]='Message type'; $slidePage['MessageType']='167'; $slideTags[167]='message type'; $slideTopics[167]='Message GuiGenerality Creation Update Delete';
$slide[168]='DocumentType'; $slideName[168]='Document type'; $slidePage['DocumentType']='168'; $slideTags[168]='document type'; $slideTopics[168]='Document GuiGenerality Creation Update Delete';
$slide[169]='ContextType'; $slideName[169]='Context type'; $slidePage['ContextType']='169'; $slideTags[169]='context type'; $slideTopics[169]='Context GuiGenerality Creation Update Delete';
$slide[170]='RequirementType'; $slideName[170]='Requirement type'; $slidePage['RequirementType']='170'; $slideTags[170]='requirement type'; $slideTopics[170]='Requirement GuiGenerality Creation Update Delete';
$slide[171]='TestCaseType'; $slideName[171]='Test case type'; $slidePage['TestCaseType']='171'; $slideTags[171]='test case type'; $slideTopics[171]='TestCase GuiGenerality Creation Update Delete';
$slide[172]='TestSessionType'; $slideName[172]='Test session type'; $slidePage['TestSessionType']='172'; $slideTags[172]='test session type'; $slideTopics[172]='TestSession GuiGenerality Creation Update Delete';
$slide[173]='Profile'; $slideName[173]='Profile'; $slidePage['Profile']='173'; $slideTags[173]='connection profile'; $slideTopics[173]='TranslatableName User';
$slide[174]='AccessProfile'; $slideName[174]='Access mode'; $slidePage['AccessProfile']='174'; $slideTags[174]='access mode read write update delete'; $slideTopics[174]='TranslatableName User Resource Profile';
$slide[175]='Habilitation'; $slideName[175]='Access to forms'; $slidePage['Habilitation']='175'; $slideTags[175]='ticket bug task track habilitation'; $slideTopics[175]='Profile AccessRight';
$slide[176]='HabilitationReport'; $slideName[176]='Access to reports'; $slidePage['HabilitationReport']='176'; $slideTags[176]='access report rights'; $slideTopics[176]='Profile';
$slide[177]='AccessRight'; $slideName[177]='Access mode to data'; $slidePage['AccessMode']='177'; $slideTags[177]='access screen form rights'; $slideTopics[177]='Profile Habilitation';
$slide[178]='HabilitationOther'; $slideName[178]='Specific access mode'; $slidePage['HabilitationOther']='178'; $slideTags[178]='access specific'; $slideTopics[178]='User Profile GuiCombo';
$slide[179]='HabilitationOther'; $slideName[179]='Specific access mode'; $slidePage['HabilitationOther2']='179'; $slideTags[179]='access specific'; $slideTopics[179]='User Profile GuiCombo';
$slide[180]='Administration'; $slideName[180]='Global parameters'; $slidePage['Administration']='180'; $slideTags[180]='administration cron maintenance purge'; $slideTopics[180]='';
$slide[181]='Audit'; $slideName[181]='Audit connections'; $slidePage['Audit']='181'; $slideTags[181]='connections who_is_online'; $slideTopics[181]='';
$slide[182]='GlobalParameter'; $slideName[182]='Global parameters'; $slidePage['GlobalParameter']='182'; $slideTags[182]='parameters work hour day unit planning responsible'; $slideTopics[182]='';
$slide[183]='GlobalParameter'; $slideName[183]='Global parameters'; $slidePage['GlobalParameter2']='183'; $slideTags[183]='parameters user password ldap'; $slideTopics[183]='';
$slide[184]='GlobalParameter'; $slideName[184]='Global parameters'; $slidePage['GlobalParameter3']='184'; $slideTags[184]='parameters format reference localization internationalizatin language'; $slideTopics[184]='';
$slide[185]='GlobalParameter'; $slideName[185]='Global parameters'; $slidePage['GlobalParameter4']='185'; $slideTags[185]='parameters icons theme files directories billing'; $slideTopics[185]='';
$slide[186]='GlobalParameter'; $slideName[186]='Global parameters'; $slidePage['GlobalParameter5']='186'; $slideTags[186]='parameters cron email'; $slideTopics[186]='';
$slide[187]='GlobalParameter'; $slideName[187]='Global parameters'; $slidePage['GlobalParameter6']='187'; $slideTags[187]='parameters email'; $slideTopics[187]='';
$slide[188]='GlobalParameter'; $slideName[188]='Global parameters'; $slidePage['GlobalParameter7']='188'; $slideTags[188]='parameters email'; $slideTopics[188]='';
$slide[189]='UserParameter'; $slideName[189]='User parameters'; $slidePage['UserParameter']='189'; $slideTags[189]='parameters'; $slideTopics[189]='';
$slide[190]='TranslatableName'; $slideName[190]='Translatable name'; $slidePage['translatableName']='190'; $slideTags[190]='translatable translation name profile'; $slideTopics[190]='AccessProfile ConnectionProfile';
$slide[191]='AutomaticEmailing'; $slideName[191]='Automatic emailing'; $slidePage['AutomaticEmailing']='191'; $slideTags[191]=''; $slideTopics[191]='Mail Status GuiGenerality Creation Update Delete';
$slide[192]='API'; $slideName[192]='api'; $slidePage['api']='192'; $slideTags[192]='api'; $slideTopics[192]='';
$slide[193]='API'; $slideName[193]='call api'; $slidePage['apiCode']='193'; $slideTags[193]='api'; $slideTopics[193]='';
$slide[194]='LinkedElements'; $slideName[194]='Linked elements'; $slidePage['LinkedElements']='194'; $slideTags[194]='link linked'; $slideTopics[194]='';
$slide[195]='Attachments'; $slideName[195]='Attachments'; $slidePage['Attachments']='195'; $slideTags[195]='attach file link privacy'; $slideTopics[195]='Ticket Activity Milestone Risk Issue Meeting Decision Question Parameters4 UserParameters';
$slide[196]='Notes'; $slideName[196]='Notes'; $slidePage['Notes']='196'; $slideTags[196]='note comment privacy predefined'; $slideTopics[196]='Ticket Activity Milestone Risk Action Issue Meeting Decision Question UserParameters';
$slide[197]='ChangeHistory'; $slideName[197]='Change history'; $slidePage['ChangeHistory']='197'; $slideTags[197]='change history track update'; $slideTopics[197]='UserParameters';
$slide[198]='Backup'; $slideName[198]='Backup / Restore'; $slidePage['Backup']='198'; $slideTags[198]='backup restore'; $slideTopics[198]='';
$slide[199]='Shortcuts'; $slideName[199]='Shortcuts'; $slidePage['Shortcuts']='199'; $slideTags[199]='shortcut key'; $slideTopics[199]='';
$slide[200]='LastWords'; $slideName[200]='Last words'; $slidePage['LastWords']='200'; $slideTags[200]='murphy hofstader history version'; $slideTopics[200]='';

if (! isset($includeManual)) {
  foreach ($slide as $id=>$name) {
    echo 'slide[' . $id . ']=' . $name . '<br/>';
  }
}

$prec='';
foreach ($slide as $id=>$name) {
  if (substr($name,0,2)=='X ') {
    unset($slide[$id]);
    unset($slideName[$id]);
    unset($slidePage[$id]);
    unset($slideTags[$id]);
    unset($slideTopics[$id]);
  } else {
    if ($name!=$prec) {
      $section[$id]=$name;
      $sectionName[$name]=$slideName[$id];
      $prec=$name;
    }
  }
}
$tags=array();
foreach ($slideTags as $id=>$name) {
 $split=explode(" ",$name);
 foreach ($split as $tag) {
   if (trim($tag) and !array_key_exists($tag, $tags)) {
     $tags[$tag]=array();
   }
   $tags[$tag][]=$id;
 }
}
ksort($tags);