<?php
$section=array();
$sectionName=array();
$topics=array();
$tags=array();
$page=array();
$slideRoot='img';
$slideExt='.png';

$slide[0]='Welcome '; $slideName[0]='Welcome'; $slidePage['Welcome']='0'; $slideTags[0]='welcome home'; $slideTopics[0]='';
$slide[1]='Functional'; $slideName[1]='Functional '; $slidePage['Functional1']='1'; $slideTags[1]='functional'; $slideTopics[1]='Ticket Activity Milestone Action Planning Workload Cost Report';
$slide[2]='Functional'; $slideName[2]='Functional (2)'; $slidePage['Functional2']='2'; $slideTags[2]='functional'; $slideTopics[2]='Expense Bill Risk Action Issue Meeting Decision Question Message Import ';
$slide[3]='Functional'; $slideName[3]='Functional (3)'; $slidePage['Functional3']='3'; $slideTags[3]='functional'; $slideTopics[3]='Client User Resource AccessRight Calendar';
$slide[4]='Functional'; $slideName[4]='Functional (4)'; $slidePage['Functional4']='4'; $slideTags[4]='functional'; $slideTopics[4]='Document Requirement Test Parameter';
$slide[5]='Functional'; $slideName[5]='Functional (5)'; $slidePage['Functional5']='5'; $slideTags[5]='functional'; $slideTopics[5]='AccessProfile GuiFilter';
$slide[6]='Technical'; $slideName[6]='Technical'; $slidePage['Technical1']='6'; $slideTags[6]='technical gui interface ajax browser'; $slideTopics[6]='GuiGenerality';
$slide[7]='Technical'; $slideName[7]='Technical (2)'; $slidePage['Technical2']='7'; $slideTags[7]='install setup deploy'; $slideTopics[7]='Installation';
$slide[8]='Technical'; $slideName[8]='Technical (3)'; $slidePage['Technical3']='8'; $slideTags[8]='parameter'; $slideTopics[8]='Parameters1';
$slide[9]='Installation'; $slideName[9]='Installation'; $slidePage['Installation']='9'; $slideTags[9]='install setup deploy php mysql http server zip'; $slideTopics[9]='Configuration Parameters1 NewVersion Connection';
$slide[10]='Configuration'; $slideName[10]='Configuration'; $slidePage['Configuration']='10'; $slideTags[10]='install setup config parameter'; $slideTopics[10]='Installation Parameters1 NewVersion Connection';
$slide[11]='Parameters'; $slideName[11]='Parameters'; $slidePage['Parameters1']='11'; $slideTags[11]='config parameter install setup'; $slideTopics[11]='Installation Configuration NewVersion';
$slide[12]='Parameters'; $slideName[12]='Parameters (2)'; $slidePage['Parameters2']='12'; $slideTags[12]='config parameter install setup'; $slideTopics[12]='Installation Configuration NewVersion';
$slide[13]='Parameters'; $slideName[13]='Parameters (3)'; $slidePage['Parameters3']='13'; $slideTags[13]='config parameter install setup'; $slideTopics[13]='Installation Configuration NewVersion';
$slide[14]='Parameters'; $slideName[14]='Parameters (4)'; $slidePage['Parameters4']='14'; $slideTags[14]='config parameter install setup'; $slideTopics[14]='Installation Configuration NewVersion';
$slide[15]='Parameters'; $slideName[15]='Parameters (5)'; $slidePage['Parameters5']='15'; $slideTags[15]='config parameter install setup'; $slideTopics[15]='Installation Configuration NewVersion';
$slide[16]='NewVersion'; $slideName[16]='Install new version'; $slidePage['NewVersion']='16'; $slideTags[16]='install setup deploy php mysql http server zip new version release update'; $slideTopics[16]='Installation Configuration Parameters1';
$slide[17]='Connection'; $slideName[17]='Connection'; $slidePage['Connection']='17'; $slideTags[17]='connect login'; $slideTopics[17]='GuiGenerality Installation Configuration';
$slide[18]='GUI'; $slideName[18]='User interface'; $slidePage['GuiGenerality']='18'; $slideTags[18]='gui interface'; $slideTopics[18]='Themes GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[19]='GUI'; $slideName[19]='Toolbars'; $slidePage['GuiToolbar']='19'; $slideTags[19]='gui interface toolbar show hide switch help manual hyperlink logo external-shortcuts shortcuts'; $slideTopics[19]='Themes GuiGenerality GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[20]='GUI'; $slideName[20]='Menu'; $slidePage['GuiMenu']='20'; $slideTags[20]='gui interface menu project combo'; $slideTopics[20]='Themes GuiGenerality GuiToolbar GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[21]='GUI'; $slideName[21]='Quick Menu'; $slidePage['GuiQuickMenu']='21'; $slideTags[21]='gui interface menu project combo'; $slideTopics[21]='Themes GuiGenerality GuiToolbar GuiMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[22]='GUI'; $slideName[22]='List'; $slidePage['GuiList']='22'; $slideTags[22]='gui interface list column'; $slideTopics[22]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[23]='GUI'; $slideName[23]='Filter'; $slidePage['GuiFilter']='23'; $slideTags[23]='gui interface filter complex'; $slideTopics[23]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[24]='GUI'; $slideName[24]='Detail'; $slidePage['GuiDetail']='24'; $slideTags[24]='gui interface detail item save print'; $slideTopics[24]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiCombo GuiAlert GuiProject';
$slide[25]='GUI'; $slideName[25]='Combo detail'; $slidePage['GuiCombo']='25'; $slideTags[25]='gui interface detail item save print combo list'; $slideTopics[25]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail  GuiAlert GuiProject';
$slide[26]='GUI'; $slideName[26]='Alert'; $slidePage['GuiAlert']='26'; $slideTags[26]='gui interface detail item save print combo list alert info warning'; $slideTopics[26]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiProject';
$slide[27]='Themes'; $slideName[27]='Themes'; $slidePage['Themes']='27'; $slideTags[27]='theme color'; $slideTopics[27]='GuiGenerality ThemesTemplates';
$slide[28]='Themes'; $slideName[28]='Themes templates'; $slidePage['ThemesTemplates']='28'; $slideTags[28]='theme color example'; $slideTopics[28]='GuiGenerality Themes';
$slide[29]='Multilingual'; $slideName[29]='Multilingual'; $slidePage['Multilingual']='29'; $slideTags[29]='english french german translat multiling'; $slideTopics[29]='GuiGenerality Configuration Parameters1';
$slide[30]='Creation'; $slideName[30]='Creation'; $slidePage['Creation']='30'; $slideTags[30]='creation'; $slideTopics[30]='GuiGenerality Update Delete Copy';
$slide[31]='Update'; $slideName[31]='Update'; $slidePage['Update']='31'; $slideTags[31]='update'; $slideTopics[31]='GuiGenerality Creation Delete copy';
$slide[32]='Delete'; $slideName[32]='Delete'; $slidePage['Delete']='32'; $slideTags[32]='delete'; $slideTopics[32]='GuiGenerality Creation Update Copy';
$slide[33]='Copy'; $slideName[33]='Copy'; $slidePage['Copy']='33'; $slideTags[33]='copy'; $slideTopics[33]='GuiGenerality Creation Update Delete';
$slide[34]='MultipleUpdate'; $slideName[34]='Multiple Update'; $slidePage['MultipleUpdate']='34'; $slideTags[34]='multiple update several grouped'; $slideTopics[34]='GuiGenerality Update';
$slide[35]='Today'; $slideName[35]='Today'; $slidePage['Today']='35'; $slideTags[35]='today summary todo message'; $slideTopics[35]='Message Project Ticket Activity Milestone Risk Action Issue';
$slide[36]='Today'; $slideName[36]='Today parameters'; $slidePage['TodayParameters']='36'; $slideTags[36]='today summary todo message'; $slideTopics[36]='Message Project Ticket Activity Milestone Risk Action Issue Report';
$slide[37]='Project'; $slideName[37]='Project'; $slidePage['Project']='37'; $slideTags[37]='project planning sub-project'; $slideTopics[37]='ProjectFields ProjectProgress ProjectAffectation ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[38]='Project'; $slideName[38]='Project fields'; $slidePage['ProjectFields']='38'; $slideTags[38]='project planning sub-project hyperlink external-shortcuts shortcuts'; $slideTopics[38]='Project ProjectAffectation ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning Affectation Customer';
$slide[39]='Project'; $slideName[39]='Project affectations and versions'; $slidePage['ProjectAffectation']='39'; $slideTags[39]='project planning affectation version'; $slideTopics[39]='Project ProjectFields ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[40]='Project'; $slideName[40]='Project progress'; $slidePage['ProjectProgress']='40'; $slideTags[40]='project planning'; $slideTopics[40]='Project ProjectFields ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[41]='Project'; $slideName[41]='Project dependencies'; $slidePage['ProjectDependencies']='41'; $slideTags[41]='project planning'; $slideTopics[41]='Project ProjectFields ProjectProgress ProjectAffectation GuiGenerality Creation Update Delete Planning';
$slide[42]='Document'; $slideName[42]='Document'; $slidePage['Document']='42'; $slideTags[42]='document directory file'; $slideTopics[42]='DocumentFields DocumentVersions DocumentDirectory DocumentApprovers Product Project';
$slide[43]='Document'; $slideName[43]='Document fields'; $slidePage['DocumentFields']='43'; $slideTags[43]='document directory file'; $slideTopics[43]='Document DocumentVersions DocumentDirectory DocumentApprovers Product Project LinkedElements';
$slide[44]='Document'; $slideName[44]='Document versions'; $slidePage['DocumentVersions']='44'; $slideTags[44]='document directory file version'; $slideTopics[44]='Document DocumentFields DocumentDirectory DocumentApprovers Product Project';
$slide[45]='Document'; $slideName[45]='Document approvers'; $slidePage['DocumentApprovers']='45'; $slideTags[45]='document directory file version approvers approve'; $slideTopics[45]='Document DocumentFields DocumentDirectory DocumentVersion Product Project';
$slide[46]='Ticket'; $slideName[46]='Ticket'; $slidePage['Ticket']='46'; $slideTags[46]='ticket bug task track'; $slideTopics[46]='TicketFields TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[47]='Ticket'; $slideName[47]='Ticket fields'; $slidePage['TicketFields']='47'; $slideTags[47]='ticket bug task track'; $slideTopics[47]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[48]='Ticket'; $slideName[48]='Ticket fields'; $slidePage['TicketFields2']='48'; $slideTags[48]='ticket bug task track work timer'; $slideTopics[48]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[49]='TicketSimple'; $slideName[49]='Simple Ticket'; $slidePage['TicketSimple']='49'; $slideTags[49]='ticket bug task track simple'; $slideTopics[49]='TicketSimpleFields Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[50]='TicketSimple'; $slideName[50]='Simple Ticket fields'; $slidePage['TicketSimpleFields']='50'; $slideTags[50]='ticket bug task track simple'; $slideTopics[50]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[51]='TicketSimple'; $slideName[51]='Simple Ticket fields'; $slidePage['TicketSimpleFields2']='51'; $slideTags[51]='ticket bug task track simple'; $slideTopics[51]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[52]='Activity'; $slideName[52]='Activity'; $slidePage['Activity']='52'; $slideTags[52]='activity task planning'; $slideTopics[52]='ActivityFields ActivityAssignment ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[53]='Activity'; $slideName[53]='Activity fields'; $slidePage['ActivityFields']='53'; $slideTags[53]='activity task planning'; $slideTopics[53]='Activity ActivityAssignement ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[54]='Activity'; $slideName[54]='Activity assignment'; $slidePage['ActivityAssignement']='54'; $slideTags[54]='activity task planning assignment'; $slideTopics[54]='Activity ActivityFields ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[55]='Activity'; $slideName[55]='Activity progress'; $slidePage['ActivityProgress']='55'; $slideTags[55]='activity task planning progress'; $slideTopics[55]='Activity ActivityFields ActivityAssignment ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[56]='Activity'; $slideName[56]='Activity dependency'; $slidePage['ActivityDependencies']='56'; $slideTags[56]='activity task planning'; $slideTopics[56]='Activity ActivityFields ActivityAssignment ActivityProgress GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[57]='Milestone'; $slideName[57]='Milestone'; $slidePage['Milestone']='57'; $slideTags[57]='milestone flag '; $slideTopics[57]='MilestoneFields MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[58]='Milestone'; $slideName[58]='Milestone fields'; $slidePage['MilestoneFields']='58'; $slideTags[58]='milestone flag '; $slideTopics[58]='Milestone MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[59]='Milestone'; $slideName[59]='Milestone progress'; $slidePage['MilestoneProgress']='59'; $slideTags[59]='milestone flag '; $slideTopics[59]='Milestone MilestoneFields MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[60]='Milestone'; $slideName[60]='Milestone dependencies'; $slidePage['MilestoneDependencies']='60'; $slideTags[60]='milestone flag '; $slideTopics[60]='Milestone MilestoneFields MilestoneProgress GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[61]='Action'; $slideName[61]='Action'; $slidePage['Action']='61'; $slideTags[61]='risk action issue'; $slideTopics[61]='ActionFields ActionDependencies Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[62]='Action'; $slideName[62]='Action fields'; $slidePage['ActionFields']='62'; $slideTags[62]='risk action issue'; $slideTopics[62]='Action ActionDependencies Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[63]='Action'; $slideName[63]='Action dependencies'; $slidePage['ActionDependencies']='63'; $slideTags[63]='risk action issue'; $slideTopics[63]='Action ActionFields Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[64]='Imputation'; $slideName[64]='Real work allocation'; $slidePage['Imputation']='64'; $slideTags[64]='imputation work follow-up allocation'; $slideTopics[64]='Activity ActivityAssignement Planning Resource Project Affectation';
$slide[65]='Planning'; $slideName[65]='Planning'; $slidePage['Planning1']='65'; $slideTags[65]='planning work plan date calculation gantt'; $slideTopics[65]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[66]='Planning'; $slideName[66]='Planning (2)'; $slidePage['Planning2']='66'; $slideTags[66]='planning work plan date calculation gantt'; $slideTopics[66]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[67]='Planning'; $slideName[67]='Planning (3)'; $slidePage['Planning3']='67'; $slideTags[67]='planning work plan date calculation gantt'; $slideTopics[67]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[68]='Planning'; $slideName[68]='Planning (4)'; $slidePage['Planning4']='68'; $slideTags[68]='planning work plan date calculation gantt'; $slideTopics[68]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[69]='Planning'; $slideName[69]='Planning (5)'; $slidePage['Planning5']='69'; $slideTags[69]='planning work plan date calculation gantt'; $slideTopics[69]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[70]='PortfolioPlanning'; $slideName[70]='Projects portfolio'; $slidePage['PortfolioPlanning']='70'; $slideTags[70]='planning gantt portfolio'; $slideTopics[70]='Planning';
$slide[71]='ResourcePlanning'; $slideName[71]='Resource Planning'; $slidePage['ResourcePlanning']='71'; $slideTags[71]='planning work plan date calculation gantt resource'; $slideTopics[71]='ActivityAssignement ActivityProgress ActivityDependencies Planning';
$slide[72]='Report'; $slideName[72]='Report'; $slidePage['Report']='72'; $slideTags[72]='parameter report print '; $slideTopics[72]='';
$slide[73]='Requirement'; $slideName[73]='Requirement'; $slidePage['Requirement']='73'; $slideTags[73]='requirement'; $slideTopics[73]='RequirementFields TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[74]='Requirement'; $slideName[74]='Requirement fields'; $slidePage['RequirementFields']='74'; $slideTags[74]='requirement'; $slideTopics[74]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[75]='Requirement'; $slideName[75]='Requirement fields'; $slidePage['RequirementFields2']='75'; $slideTags[75]='requirement'; $slideTopics[75]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[76]='TestCase'; $slideName[76]='Test case'; $slidePage['TestCase']='76'; $slideTags[76]='test case'; $slideTopics[76]='TestCaseFields Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[77]='TestCase'; $slideName[77]='Test case fields'; $slidePage['TestCaseFields']='77'; $slideTags[77]='test case'; $slideTopics[77]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[78]='TestCase'; $slideName[78]='Test case fields'; $slidePage['TestCaseFields2']='78'; $slideTags[78]='test case'; $slideTopics[78]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[79]='TestSession'; $slideName[79]='Test session'; $slidePage['TestSession']='79'; $slideTags[79]='test session'; $slideTopics[79]='TestSessionFields Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[80]='TestSession'; $slideName[80]='Test session fields'; $slidePage['TestSessionFields']='80'; $slideTags[80]='test session'; $slideTopics[80]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[81]='TestSession'; $slideName[81]='Test session fields'; $slidePage['TestSessionFields2']='81'; $slideTags[81]='test session'; $slideTopics[81]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[82]='Command'; $slideName[82]='Order'; $slidePage['Command']='82'; $slideTags[82]='order bill command'; $slideTopics[82]='activity';
$slide[83]='Command'; $slideName[83]='Order fields'; $slidePage['CommandFields']='83'; $slideTags[83]='order bill command'; $slideTopics[83]='activity';
$slide[84]='IndividualExpense'; $slideName[84]='Individual expense'; $slidePage['IndividualExpense']='84'; $slideTags[84]='expense cost travel '; $slideTopics[84]='IndividualExpenseFields IndividualExpenseDetails ProjectExpense';
$slide[85]='IndividualExpense'; $slideName[85]='Individual expense fields'; $slidePage['IndividualExpenseFields']='85'; $slideTags[85]='expense cost travel '; $slideTopics[85]='IndividualExpense IndividualExpenseDetails ProjectExpense';
$slide[86]='IndividualExpense'; $slideName[86]='Individual expense details'; $slidePage['IndividualExpenseDetails']='86'; $slideTags[86]='expense cost travel detail'; $slideTopics[86]='IndividualExpenseFields IndividualExpense ProjectExpense';
$slide[87]='ProjectExpense'; $slideName[87]='Project expense'; $slidePage['ProjectExpense']='87'; $slideTags[87]='expense'; $slideTopics[87]='ProjectExpenseFields IndividualExpense';
$slide[88]='ProjectExpense'; $slideName[88]='Project expense fields'; $slidePage['ProjectExpenseFields']='88'; $slideTags[88]='expense'; $slideTopics[88]='ProjectExpense IndividualExpense';
$slide[89]='Term'; $slideName[89]='Term'; $slidePage['Term']='89'; $slideTags[89]='term trigger bill fixed price'; $slideTopics[89]='TermFileds Bill';
$slide[90]='Term'; $slideName[90]='Term fields'; $slidePage['TermFields']='90'; $slideTags[90]='term trigger bill fixed price'; $slideTopics[90]='Term Bill';
$slide[91]='Bill'; $slideName[91]='Bill'; $slidePage['Bill']='91'; $slideTags[91]='bill billing'; $slideTopics[91]='Term Bill ActivityPrice BillingType BillType';
$slide[92]='Bill'; $slideName[92]='Bill fields'; $slidePage['BillFields']='92'; $slideTags[92]='bill billing'; $slideTopics[92]='Term Bill ActivityPrice BillingType BillType Recipient Contact';
$slide[93]='Bill'; $slideName[93]='Bill lines'; $slidePage['BillLines']='93'; $slideTags[93]='risk action issue opportunity'; $slideTopics[93]='Term Bill ActivityPrice BillingType BillType';
$slide[94]='ActivityPrice'; $slideName[94]='Activity price'; $slidePage['ActivityPrice']='94'; $slideTags[94]='risk action issue opportunity'; $slideTopics[94]='Activity ActivityType BillingType';
$slide[95]='Risk'; $slideName[95]='Risk'; $slidePage['Risk']='95'; $slideTags[95]='risk action issue'; $slideTopics[95]='RiskFields Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[96]='Risk'; $slideName[96]='Risk fields'; $slidePage['RiskFields']='96'; $slideTags[96]='risk action issue'; $slideTopics[96]='Risk Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[97]='Opportunity'; $slideName[97]='Opportunity'; $slidePage['Opportunity']='97'; $slideTags[97]='meeting workshop steering committee invitation attendees'; $slideTopics[97]='OpportunityFields Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[98]='Opportunity'; $slideName[98]='Opportunity fields'; $slidePage['OpportunityFields']='98'; $slideTags[98]='meeting workshop steering committee'; $slideTopics[98]='Opportunity Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[99]='Issue'; $slideName[99]='Issue'; $slidePage['Issue']='99'; $slideTags[99]='risk action issue'; $slideTopics[99]='IssueFields IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[100]='Issue'; $slideName[100]='Issue fields'; $slidePage['IssueFields']='100'; $slideTags[100]='risk action issue'; $slideTopics[100]='Issue IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[101]='Meeting'; $slideName[101]='Meeting'; $slidePage['Meeting']='101'; $slideTags[101]='meeting workshop steering committee invitation attendees'; $slideTopics[101]='MeetingFields MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[102]='Meeting'; $slideName[102]='Meeting fields'; $slidePage['MeetingFields']='102'; $slideTags[102]='meeting workshop steering committee'; $slideTopics[102]='Meeting MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[103]='PeriodicMeeting'; $slideName[103]='Periodic meeting'; $slidePage['PeriodicMeeting']='103'; $slideTags[103]='meeting workshop steering committee invitation attendees periodic'; $slideTopics[103]='PeriodicMeetingFields Meeting MeetingType';
$slide[104]='PeriodicMeeting'; $slideName[104]='Periodic meeting fields'; $slidePage['PeriodicMeetingFields']='104'; $slideTags[104]='meeting workshop steering committee periodic'; $slideTopics[104]='PeriodicMeeting Meeting MeetingType';
$slide[105]='Decision'; $slideName[105]='Decision'; $slidePage['Decision']='105'; $slideTags[105]='decision'; $slideTopics[105]='DecisionFields DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[106]='Decision'; $slideName[106]='Decision fields'; $slidePage['DecisionFields']='106'; $slideTags[106]='decision'; $slideTopics[106]='Decision DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[107]='Question'; $slideName[107]='Question'; $slidePage['Question']='107'; $slideTags[107]='question answer'; $slideTopics[107]='QuestionFields QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[108]='Question'; $slideName[108]='Question fields'; $slidePage['QuestionFields']='108'; $slideTags[108]='question answer'; $slideTopics[108]='Question QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[109]='Mail'; $slideName[109]='Emails'; $slidePage['Mail']='109'; $slideTags[109]='email mail'; $slideTopics[109]='AutomaticEmailing';
$slide[110]='Alert'; $slideName[110]='Alerts'; $slidePage['Alert']='110'; $slideTags[110]='alert warning information indicator'; $slideTopics[110]='GuiAlert IndicatorDefinition';
$slide[111]='Message'; $slideName[111]='Message'; $slidePage['Message']='111'; $slideTags[111]='message alert'; $slideTopics[111]='User Project Profile Today';
$slide[112]='Import'; $slideName[112]='Import'; $slidePage['Import']='112'; $slideTags[112]='import load'; $slideTopics[112]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[113]='Import'; $slideName[113]='Import Run'; $slidePage['ImportRun']='113'; $slideTags[113]='import load'; $slideTopics[113]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[114]='AutomaticImport'; $slideName[114]='Automatic Import'; $slidePage['AutomaticImport']='114'; $slideTags[114]='automatic automated import cron'; $slideTopics[114]='Import GlobalParameter';
$slide[115]='Affectation'; $slideName[115]='Affectation'; $slidePage['Affectation']='115'; $slideTags[115]='affectation resource contact user project'; $slideTopics[115]='GuiGenerality Resource Contact User Project';
$slide[116]='User'; $slideName[116]='User'; $slidePage['User']='116'; $slideTags[116]='contact resource user login password'; $slideTopics[116]='GuiGenerality Contact Resource UserAffectation';
$slide[117]='User'; $slideName[117]='User affectations'; $slidePage['UserAffectation']='117'; $slideTags[117]='contact resource user login password affectation'; $slideTopics[117]='GuiGenerality Contact Resource User';
$slide[118]='Resource'; $slideName[118]='Resource description'; $slidePage['Resource']='118'; $slideTags[118]='resource capacity affectation'; $slideTopics[118]='ResourceCost GuiGenerality User Contact Team Planning Affectation';
$slide[119]='Resource'; $slideName[119]='Resource function cost & affectation'; $slidePage['ResourceCost']='119'; $slideTags[119]='resource capacity affectation cost'; $slideTopics[119]='GuiGenerality User Contact Team Planning Affectation Resource';
$slide[120]='Contact'; $slideName[120]='Contact'; $slidePage['Contact']='120'; $slideTags[120]='contact customer requestor'; $slideTopics[120]='Client User GuiGenerality Creation Update Delete AutomaticEmailing ContactAffectation';
$slide[121]='Contact'; $slideName[121]='Contact affectations'; $slidePage['ContactAffectation']='121'; $slideTags[121]='contact customer requestor affectation'; $slideTopics[121]='Client User GuiGenerality Creation Update Delete AutomaticEmailing Contact';
$slide[122]='Client'; $slideName[122]='Customer'; $slidePage['Client']='122'; $slideTags[122]='client customer contact'; $slideTopics[122]='Contact Project GuiGenerality Creation Update Delete';
$slide[123]='Recipient'; $slideName[123]='Recipient'; $slidePage['Recipient']='123'; $slideTags[123]='recipient bill'; $slideTopics[123]='Bill';
$slide[124]='Team'; $slideName[124]='Team'; $slidePage['Team']='124'; $slideTags[124]='team resource affectation'; $slideTopics[124]='GuiGenerality Resource';
$slide[125]='Product'; $slideName[125]='Product'; $slidePage['Product']='125'; $slideTags[125]='product version'; $slideTopics[125]='Version Project Customer Contact';
$slide[126]='Version'; $slideName[126]='Version'; $slidePage['Version']='126'; $slideTags[126]='product version'; $slideTopics[126]='Product Project Customer Contact';
$slide[127]='Context'; $slideName[127]='Context'; $slidePage['Context']='127'; $slideTags[127]='context environment os browser'; $slideTopics[127]='Ticket TranslatableName';
$slide[128]='Calendar'; $slideName[128]='Calendar'; $slidePage['Calendar']='128'; $slideTags[128]='calendar off open closed day'; $slideTopics[128]='GuiGenerality Planning';
$slide[129]='DocumentDirectory'; $slideName[129]='Document directory'; $slidePage['DocumentDirectory']='129'; $slideTags[129]='document directory folder place'; $slideTopics[129]='Document';
$slide[130]='Role'; $slideName[130]='Function'; $slidePage['Role']='130'; $slideTags[130]='function resource cost'; $slideTopics[130]='GuiGenerality Resource';
$slide[131]='Status'; $slideName[131]='Status'; $slidePage['Status']='131'; $slideTags[131]='status workflow lifecycle'; $slideTopics[131]='Workflow Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[132]='HealthStatus'; $slideName[132]='HealthStatus'; $slidePage['HealthStatus']='132'; $slideTags[132]='health'; $slideTopics[132]='Project Today';
$slide[133]='Likelihood'; $slideName[133]='Likelihood'; $slidePage['Likelihood']='133'; $slideTags[133]='likelihood probability'; $slideTopics[133]='GuiGenerality criticality severity risk';
$slide[134]='Criticality'; $slideName[134]='Criticality'; $slidePage['Criticality']='134'; $slideTags[134]='criticality'; $slideTopics[134]='GuiGenerality risk ticket likelihood severity priority urgency';
$slide[135]='Severity'; $slideName[135]='Severity'; $slidePage['Severity']='135'; $slideTags[135]='severity'; $slideTopics[135]='GuiGenerality risk criticality likelihood';
$slide[136]='Urgency'; $slideName[136]='Urgency'; $slidePage['Urgency']='136'; $slideTags[136]='urgency priority'; $slideTopics[136]='GuiGenerality ticket priority criticality';
$slide[137]='Priority'; $slideName[137]='Priority'; $slidePage['Priority']='137'; $slideTags[137]='priority urgency'; $slideTopics[137]='GuiGenerality urgency criticality ticket';
$slide[138]='RiskLevel'; $slideName[138]='Risk level'; $slidePage['RiskLevel']='138'; $slideTags[138]='risk level'; $slideTopics[138]='GuiGenerality';
$slide[139]='Feasibility'; $slideName[139]='Feasibility'; $slidePage['Feasibility']='139'; $slideTags[139]='feasibility'; $slideTopics[139]='GuiGenerality';
$slide[140]='Efficiency'; $slideName[140]='Efficiency'; $slidePage['Efficiency']='140'; $slideTags[140]='efficiency'; $slideTopics[140]='GuiGenerality Action';
$slide[141]='PredefinedNote'; $slideName[141]='Predefined note'; $slidePage['PredefinedNote']='141'; $slideTags[141]='predefined note text'; $slideTopics[141]='Notes';
$slide[142]='Workflow'; $slideName[142]='Workflow description'; $slidePage['Workflow']='142'; $slideTags[142]='workflow status'; $slideTopics[142]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[143]='Workflow'; $slideName[143]='Workflow table'; $slidePage['WorkflowTable']='143'; $slideTags[143]='workflow status'; $slideTopics[143]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[144]='StatusMail'; $slideName[144]='Mail on events'; $slidePage['StatusMail']='144'; $slideTags[144]='mail emailing status'; $slideTopics[144]='GuiGenerality Mail Status AutomaticEmailing ReplyToEmails';
$slide[145]='ReplyToEmail'; $slideName[145]='Reply to emails'; $slidePage['ReplyToEmail']='145'; $slideTags[145]='mail emailing reply'; $slideTopics[145]='GuiGenerality MailAutomaticEmailing';
$slide[146]='TicketDelay'; $slideName[146]='Delay for tickets'; $slidePage['TicketDelay']='146'; $slideTags[146]='delay ticket'; $slideTopics[146]='GuiGenerality Ticket';
$slide[147]='IndicatorDefinition'; $slideName[147]='Indicator'; $slidePage['IndicatorDefinition']='147'; $slideTags[147]='delay indicator alert warning'; $slideTopics[147]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[148]='ProjectType'; $slideName[148]='Project type'; $slidePage['ProjectType']='148'; $slideTags[148]='project type template administrative operational billing'; $slideTopics[148]='Project Bill';
$slide[149]='TicketType'; $slideName[149]='Ticket type'; $slidePage['TicketType']='149'; $slideTags[149]='type ticket'; $slideTopics[149]='Ticket GuiGenerality';
$slide[150]='ActivityType'; $slideName[150]='Activity type'; $slidePage['ActivityType']='150'; $slideTags[150]='activity type'; $slideTopics[150]='Activity GuiGenerality';
$slide[151]='MilestoneType'; $slideName[151]='Milestone type'; $slidePage['MilestoneType']='151'; $slideTags[151]='milestone type'; $slideTopics[151]='Milestone GuiGenerality';
$slide[152]='IndividualExpenseType'; $slideName[152]='Individual expense type'; $slidePage['IndividualExpenseType']='152'; $slideTags[152]='expense type'; $slideTopics[152]='IndividualExpense GuiGenerality';
$slide[153]='ProjectExpenseType'; $slideName[153]='Project expensetype'; $slidePage['ProjectExpenseType']='153'; $slideTags[153]='expense type'; $slideTopics[153]='ProjectExpense GuiGenerality';
$slide[154]='ExpenseDetailType'; $slideName[154]='Expense detail type'; $slidePage['ExpenseDetailType']='154'; $slideTags[154]='expense type'; $slideTopics[154]='IndividualExpense ProjectExpense GuiGenerality';
$slide[155]='BillType'; $slideName[155]='Bill type'; $slidePage['BillType']='155'; $slideTags[155]='bill type'; $slideTopics[155]='Bill GuiGenerality Creation Update Delete';
$slide[156]='RiskType'; $slideName[156]='Risk type'; $slidePage['RiskType']='156'; $slideTags[156]='risk type'; $slideTopics[156]='Risk GuiGenerality Creation Update Delete';
$slide[157]='RiskType'; $slideName[157]='Opportunity type'; $slidePage['Opportunity Type']='157'; $slideTags[157]='opportunity type'; $slideTopics[157]='Opportunity GuiGenerality Creation Update Delete';
$slide[158]='ActionType'; $slideName[158]='Action type'; $slidePage['ActionType']='158'; $slideTags[158]='action type'; $slideTopics[158]='Action GuiGenerality Creation Update Delete';
$slide[159]='IssueType'; $slideName[159]='Issue type'; $slidePage['IssueType']='159'; $slideTags[159]='issue type'; $slideTopics[159]='Issue GuiGenerality Creation Update Delete';
$slide[160]='MeetingType'; $slideName[160]='Meeting type'; $slidePage['MeetingType']='160'; $slideTags[160]='meeting type'; $slideTopics[160]='Meeting GuiGenerality Creation Update Delete';
$slide[161]='DecisionType'; $slideName[161]='Decision type'; $slidePage['DecisionType']='161'; $slideTags[161]='decision type'; $slideTopics[161]='Decision GuiGenerality Creation Update Delete';
$slide[162]='QuestionType'; $slideName[162]='Question type'; $slidePage['QuestionType']='162'; $slideTags[162]='question type'; $slideTopics[162]='Question GuiGenerality Creation Update Delete';
$slide[163]='MessageType'; $slideName[163]='Message type'; $slidePage['MessageType']='163'; $slideTags[163]='message type'; $slideTopics[163]='Message GuiGenerality Creation Update Delete';
$slide[164]='DocumentType'; $slideName[164]='Document type'; $slidePage['DocumentType']='164'; $slideTags[164]='document type'; $slideTopics[164]='Document GuiGenerality Creation Update Delete';
$slide[165]='ContextType'; $slideName[165]='Context type'; $slidePage['ContextType']='165'; $slideTags[165]='context type'; $slideTopics[165]='Context GuiGenerality Creation Update Delete';
$slide[166]='RequirementType'; $slideName[166]='Requirement type'; $slidePage['RequirementType']='166'; $slideTags[166]='requirement type'; $slideTopics[166]='Requirement GuiGenerality Creation Update Delete';
$slide[167]='TestCaseType'; $slideName[167]='Test case type'; $slidePage['TestCaseType']='167'; $slideTags[167]='test case type'; $slideTopics[167]='TestCase GuiGenerality Creation Update Delete';
$slide[168]='TestSessionType'; $slideName[168]='Test session type'; $slidePage['TestSessionType']='168'; $slideTags[168]='test session type'; $slideTopics[168]='TestSession GuiGenerality Creation Update Delete';
$slide[169]='Profile'; $slideName[169]='Profile'; $slidePage['Profile']='169'; $slideTags[169]='connection profile'; $slideTopics[169]='TranslatableName User';
$slide[170]='AccessProfile'; $slideName[170]='Access mode'; $slidePage['AccessProfile']='170'; $slideTags[170]='access mode read write update delete'; $slideTopics[170]='TranslatableName User Resource Profile';
$slide[171]='Habilitation'; $slideName[171]='Access to forms'; $slidePage['Habilitation']='171'; $slideTags[171]='ticket bug task track habilitation'; $slideTopics[171]='Profile AccessRight';
$slide[172]='HabilitationReport'; $slideName[172]='Access to reports'; $slidePage['HabilitationReport']='172'; $slideTags[172]='access report rights'; $slideTopics[172]='Profile';
$slide[173]='AccessRight'; $slideName[173]='Access mode to data'; $slidePage['AccessMode']='173'; $slideTags[173]='access screen form rights'; $slideTopics[173]='Profile Habilitation';
$slide[174]='HabilitationOther'; $slideName[174]='Specific access mode'; $slidePage['HabilitationOther']='174'; $slideTags[174]='access specific'; $slideTopics[174]='User Profile GuiCombo';
$slide[175]='HabilitationOther'; $slideName[175]='Specific access mode'; $slidePage['HabilitationOther2']='175'; $slideTags[175]='access specific'; $slideTopics[175]='User Profile GuiCombo';
$slide[176]='Administration'; $slideName[176]='Global parameters'; $slidePage['Administration']='176'; $slideTags[176]='administration cron maintenance purge'; $slideTopics[176]='';
$slide[177]='Audit'; $slideName[177]='Audit connections'; $slidePage['Audit']='177'; $slideTags[177]='connections who_is_online'; $slideTopics[177]='';
$slide[178]='GlobalParameter'; $slideName[178]='Global parameters'; $slidePage['GlobalParameter']='178'; $slideTags[178]='parameters ldap reference format'; $slideTopics[178]='';
$slide[179]='GlobalParameter'; $slideName[179]='Global parameters'; $slidePage['GlobalParameter2']='179'; $slideTags[179]='parameters ldap billing format'; $slideTopics[179]='';
$slide[180]='GlobalParameter'; $slideName[180]='Global parameters'; $slidePage['GlobalParameter3']='180'; $slideTags[180]='parameters ldap billing format'; $slideTopics[180]='';
$slide[181]='GlobalParameter'; $slideName[181]='Global parameters'; $slidePage['GlobalParameter4']='181'; $slideTags[181]='parameters ldap billing format'; $slideTopics[181]='';
$slide[182]='GlobalParameter'; $slideName[182]='Global parameters'; $slidePage['GlobalParameter5']='182'; $slideTags[182]='parameters ldap billing format'; $slideTopics[182]='';
$slide[183]='GlobalParameter'; $slideName[183]='Global parameters'; $slidePage['GlobalParameter6']='183'; $slideTags[183]='parameters ldap billing format'; $slideTopics[183]='';
$slide[184]='UserParameter'; $slideName[184]='User parameters'; $slidePage['UserParameter']='184'; $slideTags[184]='parameters'; $slideTopics[184]='';
$slide[185]='TranslatableName'; $slideName[185]='Translatable name'; $slidePage['translatableName']='185'; $slideTags[185]='translatable translation name profile'; $slideTopics[185]='AccessProfile ConnectionProfile';
$slide[186]='AutomaticEmailing'; $slideName[186]='Automatic emailing'; $slidePage['AutomaticEmailing']='186'; $slideTags[186]=''; $slideTopics[186]='Mail Status GuiGenerality Creation Update Delete';
$slide[187]='LinkedElements'; $slideName[187]='Linked elements'; $slidePage['LinkedElements']='187'; $slideTags[187]='link linked'; $slideTopics[187]='';
$slide[188]='Attachments'; $slideName[188]='Attachments'; $slidePage['Attachments']='188'; $slideTags[188]='attach file link privacy'; $slideTopics[188]='Ticket Activity Milestone Risk Issue Meeting Decision Question Parameters4 UserParameters';
$slide[189]='Notes'; $slideName[189]='Notes'; $slidePage['Notes']='189'; $slideTags[189]='note comment privacy predefined'; $slideTopics[189]='Ticket Activity Milestone Risk Action Issue Meeting Decision Question UserParameters';
$slide[190]='ChangeHistory'; $slideName[190]='Change history'; $slidePage['ChangeHistory']='190'; $slideTags[190]='change history track update'; $slideTopics[190]='UserParameters';
$slide[191]='Backup'; $slideName[191]='Backup / Restore'; $slidePage['Backup']='191'; $slideTags[191]='backup restore'; $slideTopics[191]='';
$slide[192]='Shortcuts'; $slideName[192]='Shortcuts'; $slidePage['Shortcuts']='192'; $slideTags[192]='shortcut key'; $slideTopics[192]='';
$slide[193]='LastWords'; $slideName[193]='Last words'; $slidePage['LastWords']='193'; $slideTags[193]='murphy hofstader history version'; $slideTopics[193]='';

if (! isset($includeManual)) {
  foreach ($slide as $id=>$name) {
    echo 'slide[' . $id . ']=' . $name . '<br/>';
  }
}

$prec='';
foreach ($slide as $id=>$name) {
  if (substr($name,0,2)=='X ') {
    unset($slide[$id]);
    unset($slideName[$id]);
    unset($slidePage[$id]);
    unset($slideTags[$id]);
    unset($slideTopics[$id]);
  } else {
    if ($name!=$prec) {
      $section[$id]=$name;
      $sectionName[$name]=$slideName[$id];
      $prec=$name;
    }
  }
}
$tags=array();
foreach ($slideTags as $id=>$name) {
 $split=explode(" ",$name);
 foreach ($split as $tag) {
   if (trim($tag) and !array_key_exists($tag, $tags)) {
     $tags[$tag]=array();
   }
   $tags[$tag][]=$id;
 }
}
ksort($tags);