<style type="text/css">
<!--
@import "../view/css/facture.css";
-->
</style>

<?php 

// Header
include_once '../tool/projector.php';


echo '<table id="bill" align="center">';
	echo '<tr height="10%">';
		echo '<td width="40%">';
			echo '<table id="billadress">';
				echo '<tr>';
					echo '<th>';
						echo "ETS TOTO";
					echo '</th>';
				echo '</tr>';
				echo '<tr>';
					echo '<td class="adress">';
						echo "1 rue du Ballon<br />75000 PARIS";
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo "Tel : 01 20 20 20 20<br />Fax : 01 21 21 21 21";
					echo '</td>';
				echo '</tr>';
			echo '</table>';
		echo '</td>';
		echo '<td width="20%">';
		echo '</td>';
		echo '<td width="40%">';
			echo '<table id="details">';
				echo '<tr>';
					echo '<td>';
						echo "Facture n: ___________";
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo i18n("colCompanyNumber") . " : ___________";
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo "N de TVA : ___________";
					echo '</td>';
				echo '</tr>';
			echo '</table>';
		echo '</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan=3>';
			echo '<hr width=570px align="center" />';
			echo '<hr width=570px align="center" />';
		echo '</td>';
	echo '</tr>';
	echo '<tr height="10%">';
		echo '<td width="60%">';
			echo '<table id="adressCustomer">';
				echo '<tr>';
					echo '<th>';
						echo "ETS MACHIN";
					echo '</th>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo "XXX rue trucmuch";
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo "00000 NOWHERE";
					echo '</td>';
				echo '</tr>';
			echo '</table>';
		echo '</td>';
		echo '<td width="20%">';
		echo '</td>';
		echo '<td width="40%">';
			echo '<table id="details">';
				echo '<tr>';
					echo '<td>';
						echo "Date : 4/03/2011";
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo 'Responsable : ________';
					echo '</td>';
				echo '</tr>';
			echo '</table>';
		echo '</td>';
	echo '</tr>';
	echo '<tr height=50%>';
		echo '<td colspan=3>';
			echo '<table id="list">';
				echo '<tr>';
					echo '<th class="1">';
						echo "Quantite";					
					echo '</th>';
					echo '<th class="2">';
						echo "Description";	
					echo '</th>';
					echo '<th class="3">';
						echo "Ref commande";					
					echo '</th>';
					echo '<th class="4">';
						echo "Prix unitaire";					
					echo '</th>';
					echo '<th class="5">';
						echo 'Montant';					
					echo '</th>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
					
					echo '</td>';
					echo '<td>';
	
					echo '</td>';
					echo '<td>';
						echo "XZN MACHIN 3.8.6.5";					
					echo '</td>';
					echo '<td>';
				
					echo '</td>';
					echo '<td>';
					
					echo '</td>';					
				echo '</tr>';
				echo '<tr>';
					echo '<td class="1">';
						echo "1";					
					echo '</td>';
					echo '<td>';
						echo "20% du total";	
					echo '</td>';
					echo '<td>';
					
					echo '</td>';
					echo '<td>';
						echo "6 666,00 e";					
					echo '</td>';
					echo '<td>';
						echo '6 666,00 e';					
					echo '</td>';					
				echo '</tr>';
				echo '<tr height="300px">';
					echo '<td class="bottom">';
										
					echo '</td>';
					echo '<td class="bottom">';
	
					echo '</td>';
					echo '<td class="bottom">';
					
					echo '</td>';
					echo '<td class="bottom">';
					
					echo '</td>';
					echo '<td class="bottom">';
					
					echo '</td>';					
				echo '</tr>';
			echo '</table>';
		echo '</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td>';
			echo '<table id="payment">';
				echo '<tr>';
					echo '<th colspan=5>';
						echo "Par cheque :";
					echo '</th>';
				echo '</tr>';
				echo '<tr>';
					echo '<td colspan=1>';
						echo "Ordre :";
					echo '</td>';
					echo '<td colspan=3>';
						echo "__________";
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td colspan=1>';
						echo "Banque :";
					echo '</td>';
					echo '<td colspan=3>';
						echo "__________";
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<th colspan=5>';
						echo 'Par virement :';
					echo '</th>';
				echo '</tr>';
				echo '<tr>';
					echo '<th class="1">';
						echo 'Banque';
					echo '</th>';
					echo '<th class="1">';
						echo 'Guichet';
					echo '</th>';
					echo '<th class="1">';
						echo 'Numero de compte';
					echo '</th>';
					echo '<th class="1">';
						echo 'cle RIB';
					echo '</th>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo 'XXXX';
					echo '</td>';
					echo '<td>';
						echo 'XXXX';
					echo '</td>';
					echo '<td>';
						echo 'XXXX';
					echo '</td>';
					echo '<td>';
						echo 'XXXX';
					echo '</td>';
				echo '</tr>';
			echo '</table>';
		echo '</td>';
		echo '<td colspan=2>';
			echo '<table id="amount">';
				echo '<tr>';
					echo '<td>';
					echo '</td>';
					echo '<td>';
					echo '</td>';
					echo '<td class="1">';
						echo '6 666,00 e';
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
					echo '</td>';
					echo '<td>';
					echo '</td>';
					echo '<td>';
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<th>';
						echo 'TVA :';
					echo '</th>';
					echo '<th class="1">';
						echo '19,60%';
					echo '</th>';
					echo '<td class="1">';
						echo '???? e';
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
					echo '</td>';
					echo '<td>';
					echo '</td>';
					echo '<td>';
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
					echo '</td>';
					echo '<th>';
						echo 'Total :';
					echo '</th>';
					echo '<td class="1">';
						echo '? ???,?? e';
					echo '</td>';
				echo '</tr>';
			echo '</table>';
		echo '</td>';
	echo '</tr>';
	echo '<tr height="10%">';
		echo '<td>';
			echo 'TEST DERNIERE LIGNE';
		echo '</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td colspan=3>';
			echo '<hr width=570px align="center" />';
			echo '<hr width=570px align="center" />';
		echo '</td>';
	echo '</tr>';
echo '</table>';
?>