<?php
$section=array();
$sectionName=array();
$topics=array();
$tags=array();
$page=array();
$slideRoot='img';
$slideExt='.png';

// Copy and paste
$slide[0]='Welcome '; $slideName[0]='Welcome'; $slidePage['Welcome']='0'; $slideTags[0]='welcome home'; $slideTopics[0]='';
$slide[1]='Functional'; $slideName[1]='Functional '; $slidePage['Functional1']='1'; $slideTags[1]='functional'; $slideTopics[1]='Ticket Activity Milestone Action Planning Workload Cost Report';
$slide[2]='Functional'; $slideName[2]='Functional (2)'; $slidePage['Functional2']='2'; $slideTags[2]='functional'; $slideTopics[2]='Expense Bill Risk Action Issue Meeting Decision Question Message Import ';
$slide[3]='Functional'; $slideName[3]='Functional (3)'; $slidePage['Functional3']='3'; $slideTags[3]='functional'; $slideTopics[3]='Client User Resource AccessRight Calendar';
$slide[4]='Functional'; $slideName[4]='Functional (4)'; $slidePage['Functional4']='4'; $slideTags[4]='functional'; $slideTopics[4]='Document Requirement Test Parameter';
$slide[5]='Functional'; $slideName[5]='Functional (5)'; $slidePage['Functional5']='5'; $slideTags[5]='functional'; $slideTopics[5]='AccessProfile GuiFilter';
$slide[6]='Technical'; $slideName[6]='Technical'; $slidePage['Technical1']='6'; $slideTags[6]='technical gui interface ajax browser'; $slideTopics[6]='GuiGenerality';
$slide[7]='Technical'; $slideName[7]='Technical (2)'; $slidePage['Technical2']='7'; $slideTags[7]='install setup deploy'; $slideTopics[7]='Installation';
$slide[8]='Technical'; $slideName[8]='Technical (3)'; $slidePage['Technical3']='8'; $slideTags[8]='parameter'; $slideTopics[8]='Parameters1';
$slide[9]='Installation'; $slideName[9]='Installation'; $slidePage['Installation']='9'; $slideTags[9]='install setup deploy php mysql http server zip'; $slideTopics[9]='Configuration Parameters1 NewVersion Connection';
$slide[10]='Configuration'; $slideName[10]='Configuration'; $slidePage['Configuration']='10'; $slideTags[10]='install setup config parameter'; $slideTopics[10]='Installation Parameters1 NewVersion Connection';
$slide[11]='Parameters'; $slideName[11]='Parameters'; $slidePage['Parameters1']='11'; $slideTags[11]='config parameter install setup'; $slideTopics[11]='Installation Configuration NewVersion';
$slide[12]='Parameters'; $slideName[12]='Parameters (2)'; $slidePage['Parameters2']='12'; $slideTags[12]='config parameter install setup'; $slideTopics[12]='Installation Configuration NewVersion';
$slide[13]='Parameters'; $slideName[13]='Parameters (3)'; $slidePage['Parameters3']='13'; $slideTags[13]='config parameter install setup'; $slideTopics[13]='Installation Configuration NewVersion';
$slide[14]='Parameters'; $slideName[14]='Parameters (4)'; $slidePage['Parameters4']='14'; $slideTags[14]='config parameter install setup'; $slideTopics[14]='Installation Configuration NewVersion';
$slide[15]='Parameters'; $slideName[15]='Parameters (5)'; $slidePage['Parameters5']='15'; $slideTags[15]='config parameter install setup'; $slideTopics[15]='Installation Configuration NewVersion';
$slide[16]='NewVersion'; $slideName[16]='Install new version'; $slidePage['NewVersion']='16'; $slideTags[16]='install setup deploy php mysql http server zip new version release update'; $slideTopics[16]='Installation Configuration Parameters1';
$slide[17]='Connection'; $slideName[17]='Connection'; $slidePage['Connection']='17'; $slideTags[17]='connect login'; $slideTopics[17]='GuiGenerality Installation Configuration';
$slide[18]='GUI'; $slideName[18]='User interface'; $slidePage['GuiGenerality']='18'; $slideTags[18]='gui interface'; $slideTopics[18]='Themes GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[19]='GUI'; $slideName[19]='Toolbars'; $slidePage['GuiToolbar']='19'; $slideTags[19]='gui interface toolbar show hide switch help manual hyperlink logo external-shortcuts shortcuts'; $slideTopics[19]='Themes GuiGenerality GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[20]='GUI'; $slideName[20]='Menu'; $slidePage['GuiMenu']='20'; $slideTags[20]='gui interface menu project combo'; $slideTopics[20]='Themes GuiGenerality GuiToolbar GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[21]='GUI'; $slideName[21]='Quick Menu'; $slidePage['GuiQuickMenu']='21'; $slideTags[21]='gui interface menu project combo'; $slideTopics[21]='Themes GuiGenerality GuiToolbar GuiMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[22]='GUI'; $slideName[22]='List'; $slidePage['GuiList']='22'; $slideTags[22]='gui interface list column'; $slideTopics[22]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[23]='GUI'; $slideName[23]='Filter'; $slidePage['GuiFilter']='23'; $slideTags[23]='gui interface filter complex'; $slideTopics[23]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[24]='GUI'; $slideName[24]='ListParameter'; $slidePage['GuiListParameters']='24'; $slideTags[24]='gui interface list order selection width'; $slideTopics[24]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[25]='GUI'; $slideName[25]='Detail'; $slidePage['GuiDetail']='25'; $slideTags[25]='gui interface detail item save print'; $slideTopics[25]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiCombo GuiAlert GuiProject';
$slide[26]='GUI'; $slideName[26]='Combo detail'; $slidePage['GuiCombo']='26'; $slideTags[26]='gui interface detail item save print combo list'; $slideTopics[26]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail  GuiAlert GuiProject';
$slide[27]='GUI'; $slideName[27]='Alert'; $slidePage['GuiAlert']='27'; $slideTags[27]='gui interface detail item save print combo list alert info warning'; $slideTopics[27]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiProject';
$slide[28]='Themes'; $slideName[28]='Themes'; $slidePage['Themes']='28'; $slideTags[28]='theme color'; $slideTopics[28]='GuiGenerality ThemesTemplates';
$slide[29]='Themes'; $slideName[29]='Themes templates'; $slidePage['ThemesTemplates']='29'; $slideTags[29]='theme color example'; $slideTopics[29]='GuiGenerality Themes';
$slide[30]='Multilingual'; $slideName[30]='Multilingual'; $slidePage['Multilingual']='30'; $slideTags[30]='english french german translat multiling'; $slideTopics[30]='GuiGenerality Configuration Parameters1';
$slide[31]='Creation'; $slideName[31]='Creation'; $slidePage['Creation']='31'; $slideTags[31]='creation'; $slideTopics[31]='GuiGenerality Update Delete Copy';
$slide[32]='Update'; $slideName[32]='Update'; $slidePage['Update']='32'; $slideTags[32]='update'; $slideTopics[32]='GuiGenerality Creation Delete copy';
$slide[33]='Delete'; $slideName[33]='Delete'; $slidePage['Delete']='33'; $slideTags[33]='delete'; $slideTopics[33]='GuiGenerality Creation Update Copy';
$slide[34]='Copy'; $slideName[34]='Copy'; $slidePage['Copy']='34'; $slideTags[34]='copy'; $slideTopics[34]='GuiGenerality Creation Update Delete';
$slide[35]='MultipleUpdate'; $slideName[35]='Multiple Update'; $slidePage['MultipleUpdate']='35'; $slideTags[35]='multiple update several grouped'; $slideTopics[35]='GuiGenerality Update';
$slide[36]='Checklist'; $slideName[36]='Checklist'; $slidePage['Checklist']='36'; $slideTags[36]='checklist quality'; $slideTopics[36]='ChecklistDefinition';
$slide[37]='Export'; $slideName[37]='Export'; $slidePage['Export']='37'; $slideTags[37]='export csv'; $slideTopics[37]='Import';
$slide[38]='Today'; $slideName[38]='Today'; $slidePage['Today']='38'; $slideTags[38]='today summary todo message'; $slideTopics[38]='Message Project Ticket Activity Milestone Risk Action Issue';
$slide[39]='Today'; $slideName[39]='Today parameters'; $slidePage['TodayParameters']='39'; $slideTags[39]='today summary todo message'; $slideTopics[39]='Message Project Ticket Activity Milestone Risk Action Issue Report';
$slide[40]='Project'; $slideName[40]='Project'; $slidePage['Project']='40'; $slideTags[40]='project planning sub-project'; $slideTopics[40]='ProjectFields ProjectProgress ProjectAffectation ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[41]='Project'; $slideName[41]='Project fields'; $slidePage['ProjectFields']='41'; $slideTags[41]='project planning sub-project hyperlink external-shortcuts shortcuts'; $slideTopics[41]='Project ProjectAffectation ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning Affectation Customer';
$slide[42]='Project'; $slideName[42]='Project affectations and versions'; $slidePage['ProjectAffectation']='42'; $slideTags[42]='project planning affectation version'; $slideTopics[42]='Project ProjectFields ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[43]='Project'; $slideName[43]='Project progress'; $slidePage['ProjectProgress']='43'; $slideTags[43]='project planning'; $slideTopics[43]='Project ProjectFields ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[44]='Project'; $slideName[44]='Project dependencies'; $slidePage['ProjectDependencies']='44'; $slideTags[44]='project planning'; $slideTopics[44]='Project ProjectFields ProjectProgress ProjectAffectation GuiGenerality Creation Update Delete Planning';
$slide[45]='Document'; $slideName[45]='Document'; $slidePage['Document']='45'; $slideTags[45]='document directory file'; $slideTopics[45]='DocumentFields DocumentVersions DocumentDirectory DocumentApprovers Product Project';
$slide[46]='Document'; $slideName[46]='Document fields'; $slidePage['DocumentFields']='46'; $slideTags[46]='document directory file'; $slideTopics[46]='Document DocumentVersions DocumentDirectory DocumentApprovers Product Project LinkedElements';
$slide[47]='Document'; $slideName[47]='Document versions'; $slidePage['DocumentVersions']='47'; $slideTags[47]='document directory file version'; $slideTopics[47]='Document DocumentFields DocumentDirectory DocumentApprovers Product Project';
$slide[48]='Document'; $slideName[48]='Document approvers'; $slidePage['DocumentApprovers']='48'; $slideTags[48]='document directory file version approvers approve'; $slideTopics[48]='Document DocumentFields DocumentDirectory DocumentVersion Product Project';
$slide[49]='Ticket'; $slideName[49]='Ticket'; $slidePage['Ticket']='49'; $slideTags[49]='ticket bug task track'; $slideTopics[49]='TicketFields TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[50]='Ticket'; $slideName[50]='Ticket fields'; $slidePage['TicketFields']='50'; $slideTags[50]='ticket bug task track'; $slideTopics[50]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[51]='Ticket'; $slideName[51]='Ticket fields'; $slidePage['TicketFields2']='51'; $slideTags[51]='ticket bug task track work timer'; $slideTopics[51]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[52]='TicketSimple'; $slideName[52]='Simple Ticket'; $slidePage['TicketSimple']='52'; $slideTags[52]='ticket bug task track simple'; $slideTopics[52]='TicketSimpleFields Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[53]='TicketSimple'; $slideName[53]='Simple Ticket fields'; $slidePage['TicketSimpleFields']='53'; $slideTags[53]='ticket bug task track simple'; $slideTopics[53]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[54]='TicketSimple'; $slideName[54]='Simple Ticket fields'; $slidePage['TicketSimpleFields2']='54'; $slideTags[54]='ticket bug task track simple'; $slideTopics[54]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[55]='Activity'; $slideName[55]='Activity'; $slidePage['Activity']='55'; $slideTags[55]='activity task planning'; $slideTopics[55]='ActivityFields ActivityAssignment ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[56]='Activity'; $slideName[56]='Activity fields'; $slidePage['ActivityFields']='56'; $slideTags[56]='activity task planning'; $slideTopics[56]='Activity ActivityAssignement ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[57]='Activity'; $slideName[57]='Activity assignment'; $slidePage['ActivityAssignement']='57'; $slideTags[57]='activity task planning assignment'; $slideTopics[57]='Activity ActivityFields ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[58]='Activity'; $slideName[58]='Activity progress'; $slidePage['ActivityProgress']='58'; $slideTags[58]='activity task planning progress'; $slideTopics[58]='Activity ActivityFields ActivityAssignment ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[59]='Activity'; $slideName[59]='Activity dependency'; $slidePage['ActivityDependencies']='59'; $slideTags[59]='activity task planning'; $slideTopics[59]='Activity ActivityFields ActivityAssignment ActivityProgress GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[60]='Milestone'; $slideName[60]='Milestone'; $slidePage['Milestone']='60'; $slideTags[60]='milestone flag '; $slideTopics[60]='MilestoneFields MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[61]='Milestone'; $slideName[61]='Milestone fields'; $slidePage['MilestoneFields']='61'; $slideTags[61]='milestone flag '; $slideTopics[61]='Milestone MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[62]='Milestone'; $slideName[62]='Milestone progress'; $slidePage['MilestoneProgress']='62'; $slideTags[62]='milestone flag '; $slideTopics[62]='Milestone MilestoneFields MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[63]='Milestone'; $slideName[63]='Milestone dependencies'; $slidePage['MilestoneDependencies']='63'; $slideTags[63]='milestone flag '; $slideTopics[63]='Milestone MilestoneFields MilestoneProgress GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[64]='Action'; $slideName[64]='Action'; $slidePage['Action']='64'; $slideTags[64]='risk action issue'; $slideTopics[64]='ActionFields Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[65]='Action'; $slideName[65]='Action fields'; $slidePage['ActionFields']='65'; $slideTags[65]='risk action issue'; $slideTopics[65]='Action Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[66]='Imputation'; $slideName[66]='Real work allocation'; $slidePage['Imputation']='66'; $slideTags[66]='imputation work follow-up allocation'; $slideTopics[66]='Activity ActivityAssignement Planning Resource Project Affectation';
$slide[67]='Planning'; $slideName[67]='Planning'; $slidePage['Planning1']='67'; $slideTags[67]='planning work plan date calculation gantt'; $slideTopics[67]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[68]='Planning'; $slideName[68]='Planning (2)'; $slidePage['Planning2']='68'; $slideTags[68]='planning work plan date calculation gantt'; $slideTopics[68]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[69]='Planning'; $slideName[69]='Planning (3)'; $slidePage['Planning3']='69'; $slideTags[69]='planning work plan date calculation gantt'; $slideTopics[69]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[70]='Planning'; $slideName[70]='Planning (4)'; $slidePage['Planning4']='70'; $slideTags[70]='planning work plan date calculation gantt'; $slideTopics[70]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[71]='Planning'; $slideName[71]='Planning (5)'; $slidePage['Planning5']='71'; $slideTags[71]='planning work plan date calculation gantt'; $slideTopics[71]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[72]='PortfolioPlanning'; $slideName[72]='Projects portfolio'; $slidePage['PortfolioPlanning']='72'; $slideTags[72]='planning gantt portfolio'; $slideTopics[72]='Planning';
$slide[73]='ResourcePlanning'; $slideName[73]='Resource Planning'; $slidePage['ResourcePlanning']='73'; $slideTags[73]='planning work plan date calculation gantt resource'; $slideTopics[73]='ActivityAssignement ActivityProgress ActivityDependencies Planning';
$slide[74]='Report'; $slideName[74]='Report'; $slidePage['Report']='74'; $slideTags[74]='parameter report print '; $slideTopics[74]='';
$slide[75]='Requirement'; $slideName[75]='Requirement'; $slidePage['Requirement']='75'; $slideTags[75]='requirement'; $slideTopics[75]='RequirementFields TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[76]='Requirement'; $slideName[76]='Requirement fields'; $slidePage['RequirementFields']='76'; $slideTags[76]='requirement'; $slideTopics[76]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[77]='Requirement'; $slideName[77]='Requirement fields'; $slidePage['RequirementFields2']='77'; $slideTags[77]='requirement'; $slideTopics[77]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[78]='TestCase'; $slideName[78]='Test case'; $slidePage['TestCase']='78'; $slideTags[78]='test case'; $slideTopics[78]='TestCaseFields Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[79]='TestCase'; $slideName[79]='Test case fields'; $slidePage['TestCaseFields']='79'; $slideTags[79]='test case'; $slideTopics[79]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[80]='TestCase'; $slideName[80]='Test case fields'; $slidePage['TestCaseFields2']='80'; $slideTags[80]='test case'; $slideTopics[80]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[81]='TestSession'; $slideName[81]='Test session'; $slidePage['TestSession']='81'; $slideTags[81]='test session'; $slideTopics[81]='TestSessionFields Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[82]='TestSession'; $slideName[82]='Test session fields'; $slidePage['TestSessionFields']='82'; $slideTags[82]='test session'; $slideTopics[82]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[83]='TestSession'; $slideName[83]='Test session fields'; $slidePage['TestSessionFields2']='83'; $slideTags[83]='test session'; $slideTopics[83]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[84]='Quotation'; $slideName[84]='Quotation'; $slidePage['Quotation']='84'; $slideTags[84]='quotation proposal estimate'; $slideTopics[84]='Order Creation Update Delete';
$slide[85]='Quotation'; $slideName[85]='Quotation fields'; $slidePage['QuotationFields']='85'; $slideTags[85]='quotation proposal estimate'; $slideTopics[85]='Order Creation Update Delete';
$slide[86]='Command'; $slideName[86]='Order'; $slidePage['Command']='86'; $slideTags[86]='order bill command'; $slideTopics[86]='Activity Quotation';
$slide[87]='Command'; $slideName[87]='Order fields'; $slidePage['CommandFields']='87'; $slideTags[87]='order bill command'; $slideTopics[87]='Activity Quotation';
$slide[88]='IndividualExpense'; $slideName[88]='Individual expense'; $slidePage['IndividualExpense']='88'; $slideTags[88]='expense cost travel '; $slideTopics[88]='IndividualExpenseFields IndividualExpenseDetails ProjectExpense';
$slide[89]='IndividualExpense'; $slideName[89]='Individual expense fields'; $slidePage['IndividualExpenseFields']='89'; $slideTags[89]='expense cost travel '; $slideTopics[89]='IndividualExpense IndividualExpenseDetails ProjectExpense';
$slide[90]='IndividualExpense'; $slideName[90]='Individual expense details'; $slidePage['IndividualExpenseDetails']='90'; $slideTags[90]='expense cost travel detail'; $slideTopics[90]='IndividualExpenseFields IndividualExpense ProjectExpense';
$slide[91]='ProjectExpense'; $slideName[91]='Project expense'; $slidePage['ProjectExpense']='91'; $slideTags[91]='expense'; $slideTopics[91]='ProjectExpenseFields IndividualExpense';
$slide[92]='ProjectExpense'; $slideName[92]='Project expense fields'; $slidePage['ProjectExpenseFields']='92'; $slideTags[92]='expense'; $slideTopics[92]='ProjectExpense IndividualExpense';
$slide[93]='Term'; $slideName[93]='Term'; $slidePage['Term']='93'; $slideTags[93]='term trigger bill fixed price'; $slideTopics[93]='TermFileds Bill';
$slide[94]='Term'; $slideName[94]='Term fields'; $slidePage['TermFields']='94'; $slideTags[94]='term trigger bill fixed price'; $slideTopics[94]='Term Bill';
$slide[95]='Bill'; $slideName[95]='Bill'; $slidePage['Bill']='95'; $slideTags[95]='bill billing'; $slideTopics[95]='Term Bill ActivityPrice BillingType BillType';
$slide[96]='Bill'; $slideName[96]='Bill fields'; $slidePage['BillFields']='96'; $slideTags[96]='bill billing'; $slideTopics[96]='Term Bill ActivityPrice BillingType BillType Recipient Contact';
$slide[97]='Bill'; $slideName[97]='Bill lines'; $slidePage['BillLines']='97'; $slideTags[97]='bill billing'; $slideTopics[97]='Term Bill ActivityPrice BillingType BillType';
$slide[98]='ActivityPrice'; $slideName[98]='Activity price'; $slidePage['ActivityPrice']='98'; $slideTags[98]='activity price bill billing'; $slideTopics[98]='Activity ActivityType BillingType';
$slide[99]='Risk'; $slideName[99]='Risk'; $slidePage['Risk']='99'; $slideTags[99]='risk action issue opportunity'; $slideTopics[99]='RiskFields Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[100]='Risk'; $slideName[100]='Risk fields'; $slidePage['RiskFields']='100'; $slideTags[100]='risk action issue opportunity'; $slideTopics[100]='Risk Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[101]='Opportunity'; $slideName[101]='Opportunity'; $slidePage['Opportunity']='101'; $slideTags[101]='opportunity risk action issue'; $slideTopics[101]='OpportunityFields Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[102]='Opportunity'; $slideName[102]='Opportunity fields'; $slidePage['OpportunityFields']='102'; $slideTags[102]='opportunity risk action issue'; $slideTopics[102]='Opportunity Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[103]='Issue'; $slideName[103]='Issue'; $slidePage['Issue']='103'; $slideTags[103]='risk action issue'; $slideTopics[103]='IssueFields IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[104]='Issue'; $slideName[104]='Issue fields'; $slidePage['IssueFields']='104'; $slideTags[104]='risk action issue'; $slideTopics[104]='Issue IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[105]='Meeting'; $slideName[105]='Meeting'; $slidePage['Meeting']='105'; $slideTags[105]='meeting workshop steering committee invitation attendees'; $slideTopics[105]='MeetingFields MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[106]='Meeting'; $slideName[106]='Meeting fields'; $slidePage['MeetingFields']='106'; $slideTags[106]='meeting workshop steering committee'; $slideTopics[106]='Meeting MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[107]='PeriodicMeeting'; $slideName[107]='Periodic meeting'; $slidePage['PeriodicMeeting']='107'; $slideTags[107]='meeting workshop steering committee invitation attendees periodic'; $slideTopics[107]='PeriodicMeetingFields Meeting MeetingType';
$slide[108]='PeriodicMeeting'; $slideName[108]='Periodic meeting fields'; $slidePage['PeriodicMeetingFields']='108'; $slideTags[108]='meeting workshop steering committee periodic'; $slideTopics[108]='PeriodicMeeting Meeting MeetingType';
$slide[109]='Decision'; $slideName[109]='Decision'; $slidePage['Decision']='109'; $slideTags[109]='decision'; $slideTopics[109]='DecisionFields DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[110]='Decision'; $slideName[110]='Decision fields'; $slidePage['DecisionFields']='110'; $slideTags[110]='decision'; $slideTopics[110]='Decision DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[111]='Question'; $slideName[111]='Question'; $slidePage['Question']='111'; $slideTags[111]='question answer'; $slideTopics[111]='QuestionFields QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[112]='Question'; $slideName[112]='Question fields'; $slidePage['QuestionFields']='112'; $slideTags[112]='question answer'; $slideTopics[112]='Question QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[113]='Mail'; $slideName[113]='Emails'; $slidePage['Mail']='113'; $slideTags[113]='email mail'; $slideTopics[113]='AutomaticEmailing';
$slide[114]='Alert'; $slideName[114]='Alerts'; $slidePage['Alert']='114'; $slideTags[114]='alert warning information indicator'; $slideTopics[114]='GuiAlert IndicatorDefinition';
$slide[115]='Message'; $slideName[115]='Message'; $slidePage['Message']='115'; $slideTags[115]='message alert'; $slideTopics[115]='User Project Profile Today';
$slide[116]='Import'; $slideName[116]='Import'; $slidePage['Import']='116'; $slideTags[116]='import load csv xlsx'; $slideTopics[116]='AutomaticImport Export';
$slide[117]='Import'; $slideName[117]='Import Run'; $slidePage['ImportRun']='117'; $slideTags[117]='import load'; $slideTopics[117]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[118]='AutomaticImport'; $slideName[118]='Automatic Import'; $slidePage['AutomaticImport']='118'; $slideTags[118]='automatic automated import cron'; $slideTopics[118]='Import GlobalParameter';
$slide[119]='Affectation'; $slideName[119]='Affectation'; $slidePage['Affectation']='119'; $slideTags[119]='affectation resource contact user project'; $slideTopics[119]='GuiGenerality Resource Contact User Project';
$slide[120]='User'; $slideName[120]='User'; $slidePage['User']='120'; $slideTags[120]='contact resource user login password'; $slideTopics[120]='GuiGenerality Contact Resource UserAffectation';
$slide[121]='User'; $slideName[121]='User affectations'; $slidePage['UserAffectation']='121'; $slideTags[121]='contact resource user login password affectation'; $slideTopics[121]='GuiGenerality Contact Resource User';
$slide[122]='Resource'; $slideName[122]='Resource description'; $slidePage['Resource']='122'; $slideTags[122]='resource capacity affectation'; $slideTopics[122]='ResourceCost GuiGenerality User Contact Team Planning Affectation';
$slide[123]='Resource'; $slideName[123]='Resource function cost & affectation'; $slidePage['ResourceCost']='123'; $slideTags[123]='resource capacity affectation cost'; $slideTopics[123]='GuiGenerality User Contact Team Planning Affectation Resource';
$slide[124]='Contact'; $slideName[124]='Contact'; $slidePage['Contact']='124'; $slideTags[124]='contact customer requestor'; $slideTopics[124]='Client User GuiGenerality Creation Update Delete AutomaticEmailing ContactAffectation';
$slide[125]='Contact'; $slideName[125]='Contact affectations'; $slidePage['ContactAffectation']='125'; $slideTags[125]='contact customer requestor affectation'; $slideTopics[125]='Client User GuiGenerality Creation Update Delete AutomaticEmailing Contact';
$slide[126]='Client'; $slideName[126]='Customer'; $slidePage['Client']='126'; $slideTags[126]='client customer contact'; $slideTopics[126]='Contact Project GuiGenerality Creation Update Delete';
$slide[127]='Recipient'; $slideName[127]='Recipient'; $slidePage['Recipient']='127'; $slideTags[127]='recipient bill'; $slideTopics[127]='Bill';
$slide[128]='Team'; $slideName[128]='Team'; $slidePage['Team']='128'; $slideTags[128]='team resource affectation'; $slideTopics[128]='GuiGenerality Resource';
$slide[129]='Product'; $slideName[129]='Product'; $slidePage['Product']='129'; $slideTags[129]='product version'; $slideTopics[129]='Version Project Customer Contact';
$slide[130]='Version'; $slideName[130]='Version'; $slidePage['Version']='130'; $slideTags[130]='product version'; $slideTopics[130]='Product Project Customer Contact';
$slide[131]='Context'; $slideName[131]='Context'; $slidePage['Context']='131'; $slideTags[131]='context environment os browser'; $slideTopics[131]='Ticket TranslatableName';
$slide[132]='Calendar'; $slideName[132]='Calendar'; $slidePage['Calendar']='132'; $slideTags[132]='calendar off open closed day'; $slideTopics[132]='GuiGenerality Planning';
$slide[133]='Calendar'; $slideName[133]='Calendar description'; $slidePage['CalendarDescription']='133'; $slideTags[133]='calendar off open closed day'; $slideTopics[133]='GuiGenerality Planning';
$slide[134]='DocumentDirectory'; $slideName[134]='Document directory'; $slidePage['DocumentDirectory']='134'; $slideTags[134]='document directory folder place'; $slideTopics[134]='Document';
$slide[135]='Role'; $slideName[135]='Function'; $slidePage['Role']='135'; $slideTags[135]='function resource cost'; $slideTopics[135]='GuiGenerality Resource';
$slide[136]='Status'; $slideName[136]='Status'; $slidePage['Status']='136'; $slideTags[136]='status workflow lifecycle'; $slideTopics[136]='Workflow Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[137]='Quality'; $slideName[137]='Quality level'; $slidePage['Quality']='137'; $slideTags[137]='quality'; $slideTopics[137]='Project Today';
$slide[138]='HealthStatus'; $slideName[138]='Health Status'; $slidePage['HealthStatus']='138'; $slideTags[138]='health'; $slideTopics[138]='Project Today';
$slide[139]='OverallProgress'; $slideName[139]='Overall Progress'; $slidePage['OverallProgress']='139'; $slideTags[139]='progress'; $slideTopics[139]='Project Today';
$slide[140]='Trend'; $slideName[140]='Trend'; $slidePage['Trend']='140'; $slideTags[140]='trend'; $slideTopics[140]='Project Today';
$slide[141]='Likelihood'; $slideName[141]='Likelihood'; $slidePage['Likelihood']='141'; $slideTags[141]='likelihood probability'; $slideTopics[141]='GuiGenerality criticality severity risk';
$slide[142]='Criticality'; $slideName[142]='Criticality'; $slidePage['Criticality']='142'; $slideTags[142]='criticality'; $slideTopics[142]='GuiGenerality risk ticket likelihood severity priority urgency';
$slide[143]='Severity'; $slideName[143]='Severity'; $slidePage['Severity']='143'; $slideTags[143]='severity'; $slideTopics[143]='GuiGenerality risk criticality likelihood';
$slide[144]='Urgency'; $slideName[144]='Urgency'; $slidePage['Urgency']='144'; $slideTags[144]='urgency priority'; $slideTopics[144]='GuiGenerality ticket priority criticality';
$slide[145]='Priority'; $slideName[145]='Priority'; $slidePage['Priority']='145'; $slideTags[145]='priority urgency'; $slideTopics[145]='GuiGenerality urgency criticality ticket';
$slide[146]='RiskLevel'; $slideName[146]='Risk level'; $slidePage['RiskLevel']='146'; $slideTags[146]='risk level'; $slideTopics[146]='GuiGenerality';
$slide[147]='Feasibility'; $slideName[147]='Feasibility'; $slidePage['Feasibility']='147'; $slideTags[147]='feasibility'; $slideTopics[147]='GuiGenerality';
$slide[148]='Efficiency'; $slideName[148]='Efficiency'; $slidePage['Efficiency']='148'; $slideTags[148]='efficiency'; $slideTopics[148]='GuiGenerality Action';
$slide[149]='PredefinedNote'; $slideName[149]='Predefined note'; $slidePage['PredefinedNote']='149'; $slideTags[149]='predefined note text'; $slideTopics[149]='Notes';
$slide[150]='Workflow'; $slideName[150]='Workflow description'; $slidePage['Workflow']='150'; $slideTags[150]='workflow status'; $slideTopics[150]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[151]='Workflow'; $slideName[151]='Workflow table'; $slidePage['WorkflowTable']='151'; $slideTags[151]='workflow status'; $slideTopics[151]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[152]='StatusMail'; $slideName[152]='Mail on events'; $slidePage['StatusMail']='152'; $slideTags[152]='mail emailing status'; $slideTopics[152]='GuiGenerality Mail Status AutomaticEmailing ReplyToEmails';
$slide[153]='ReplyToEmail'; $slideName[153]='Reply to emails'; $slidePage['ReplyToEmail']='153'; $slideTags[153]='mail emailing reply'; $slideTopics[153]='GuiGenerality MailAutomaticEmailing';
$slide[154]='TicketDelay'; $slideName[154]='Delay for tickets'; $slidePage['TicketDelay']='154'; $slideTags[154]='delay ticket'; $slideTopics[154]='GuiGenerality Ticket';
$slide[155]='IndicatorDefinition'; $slideName[155]='Indicator'; $slidePage['IndicatorDefinition']='155'; $slideTags[155]='delay indicator alert warning'; $slideTopics[155]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[156]='ChecklistDefinition'; $slideName[156]='Checklist definition'; $slidePage['ChecklistDefinition']='156'; $slideTags[156]='checklist quality'; $slideTopics[156]='Checklist';
$slide[157]='ProjectType'; $slideName[157]='Project type'; $slidePage['ProjectType']='157'; $slideTags[157]='project type template administrative operational billing'; $slideTopics[157]='Project Bill';
$slide[158]='TicketType'; $slideName[158]='Ticket type'; $slidePage['TicketType']='158'; $slideTags[158]='type ticket'; $slideTopics[158]='Ticket GuiGenerality';
$slide[159]='ActivityType'; $slideName[159]='Activity type'; $slidePage['ActivityType']='159'; $slideTags[159]='activity type'; $slideTopics[159]='Activity GuiGenerality';
$slide[160]='MilestoneType'; $slideName[160]='Milestone type'; $slidePage['MilestoneType']='160'; $slideTags[160]='milestone type'; $slideTopics[160]='Milestone GuiGenerality';
$slide[161]='QuotationType'; $slideName[161]='Quotation type'; $slidePage['MilestoneType']='161'; $slideTags[161]='quotation type'; $slideTopics[161]='Order Bill GuiGenerality';
$slide[162]='CommandType'; $slideName[162]='Order type'; $slidePage['CommandType']='162'; $slideTags[162]='order type'; $slideTopics[162]='Quotation Bill GuiGenerality';
$slide[163]='IndividualExpenseType'; $slideName[163]='Individual expense type'; $slidePage['IndividualExpenseType']='163'; $slideTags[163]='expense type'; $slideTopics[163]='IndividualExpense GuiGenerality';
$slide[164]='ProjectExpenseType'; $slideName[164]='Project expensetype'; $slidePage['ProjectExpenseType']='164'; $slideTags[164]='expense type'; $slideTopics[164]='ProjectExpense GuiGenerality';
$slide[165]='ExpenseDetailType'; $slideName[165]='Expense detail type'; $slidePage['ExpenseDetailType']='165'; $slideTags[165]='expense type'; $slideTopics[165]='IndividualExpense ProjectExpense GuiGenerality';
$slide[166]='BillType'; $slideName[166]='Bill type'; $slidePage['BillType']='166'; $slideTags[166]='bill type'; $slideTopics[166]='Bill GuiGenerality Creation Update Delete';
$slide[167]='RiskType'; $slideName[167]='Risk type'; $slidePage['RiskType']='167'; $slideTags[167]='risk type'; $slideTopics[167]='Risk GuiGenerality Creation Update Delete';
$slide[168]='RiskType'; $slideName[168]='Opportunity type'; $slidePage['Opportunity Type']='168'; $slideTags[168]='opportunity type'; $slideTopics[168]='Opportunity GuiGenerality Creation Update Delete';
$slide[169]='ActionType'; $slideName[169]='Action type'; $slidePage['ActionType']='169'; $slideTags[169]='action type'; $slideTopics[169]='Action GuiGenerality Creation Update Delete';
$slide[170]='IssueType'; $slideName[170]='Issue type'; $slidePage['IssueType']='170'; $slideTags[170]='issue type'; $slideTopics[170]='Issue GuiGenerality Creation Update Delete';
$slide[171]='MeetingType'; $slideName[171]='Meeting type'; $slidePage['MeetingType']='171'; $slideTags[171]='meeting type'; $slideTopics[171]='Meeting GuiGenerality Creation Update Delete';
$slide[172]='DecisionType'; $slideName[172]='Decision type'; $slidePage['DecisionType']='172'; $slideTags[172]='decision type'; $slideTopics[172]='Decision GuiGenerality Creation Update Delete';
$slide[173]='QuestionType'; $slideName[173]='Question type'; $slidePage['QuestionType']='173'; $slideTags[173]='question type'; $slideTopics[173]='Question GuiGenerality Creation Update Delete';
$slide[174]='MessageType'; $slideName[174]='Message type'; $slidePage['MessageType']='174'; $slideTags[174]='message type'; $slideTopics[174]='Message GuiGenerality Creation Update Delete';
$slide[175]='DocumentType'; $slideName[175]='Document type'; $slidePage['DocumentType']='175'; $slideTags[175]='document type'; $slideTopics[175]='Document GuiGenerality Creation Update Delete';
$slide[176]='ContextType'; $slideName[176]='Context type'; $slidePage['ContextType']='176'; $slideTags[176]='context type'; $slideTopics[176]='Context GuiGenerality Creation Update Delete';
$slide[177]='RequirementType'; $slideName[177]='Requirement type'; $slidePage['RequirementType']='177'; $slideTags[177]='requirement type'; $slideTopics[177]='Requirement GuiGenerality Creation Update Delete';
$slide[178]='TestCaseType'; $slideName[178]='Test case type'; $slidePage['TestCaseType']='178'; $slideTags[178]='test case type'; $slideTopics[178]='TestCase GuiGenerality Creation Update Delete';
$slide[179]='TestSessionType'; $slideName[179]='Test session type'; $slidePage['TestSessionType']='179'; $slideTags[179]='test session type'; $slideTopics[179]='TestSession GuiGenerality Creation Update Delete';
$slide[180]='Profile'; $slideName[180]='Profile'; $slidePage['Profile']='180'; $slideTags[180]='connection profile'; $slideTopics[180]='TranslatableName User';
$slide[181]='AccessProfile'; $slideName[181]='Access mode'; $slidePage['AccessProfile']='181'; $slideTags[181]='access mode read write update delete'; $slideTopics[181]='TranslatableName User Resource Profile';
$slide[182]='Habilitation'; $slideName[182]='Access to forms'; $slidePage['Habilitation']='182'; $slideTags[182]='ticket bug task track habilitation'; $slideTopics[182]='Profile AccessRight';
$slide[183]='HabilitationReport'; $slideName[183]='Access to reports'; $slidePage['HabilitationReport']='183'; $slideTags[183]='access report rights'; $slideTopics[183]='Profile';
$slide[184]='AccessRight'; $slideName[184]='Access mode to data'; $slidePage['AccessMode']='184'; $slideTags[184]='access screen form rights'; $slideTopics[184]='Profile Habilitation';
$slide[185]='HabilitationOther'; $slideName[185]='Specific access mode'; $slidePage['HabilitationOther']='185'; $slideTags[185]='access specific'; $slideTopics[185]='User Profile GuiCombo';
$slide[186]='HabilitationOther'; $slideName[186]='Specific access mode'; $slidePage['HabilitationOther2']='186'; $slideTags[186]='access specific'; $slideTopics[186]='User Profile GuiCombo';
$slide[187]='Administration'; $slideName[187]='Global parameters'; $slidePage['Administration']='187'; $slideTags[187]='administration cron maintenance purge'; $slideTopics[187]='';
$slide[188]='Audit'; $slideName[188]='Audit connections'; $slidePage['Audit']='188'; $slideTags[188]='connections who_is_online'; $slideTopics[188]='';
$slide[189]='GlobalParameter'; $slideName[189]='Global parameters'; $slidePage['GlobalParameter']='189'; $slideTags[189]='parameters work hour day unit planning responsible'; $slideTopics[189]='';
$slide[190]='GlobalParameter'; $slideName[190]='Global parameters'; $slidePage['GlobalParameter2']='190'; $slideTags[190]='parameters user password ldap'; $slideTopics[190]='';
$slide[191]='GlobalParameter'; $slideName[191]='Global parameters'; $slidePage['GlobalParameter3']='191'; $slideTags[191]='parameters format reference localization internationalizatin language'; $slideTopics[191]='';
$slide[192]='GlobalParameter'; $slideName[192]='Global parameters'; $slidePage['GlobalParameter4']='192'; $slideTags[192]='parameters icons theme files directories billing'; $slideTopics[192]='';
$slide[193]='GlobalParameter'; $slideName[193]='Global parameters'; $slidePage['GlobalParameter5']='193'; $slideTags[193]='parameters cron email'; $slideTopics[193]='';
$slide[194]='GlobalParameter'; $slideName[194]='Global parameters'; $slidePage['GlobalParameter6']='194'; $slideTags[194]='parameters email'; $slideTopics[194]='';
$slide[195]='GlobalParameter'; $slideName[195]='Global parameters'; $slidePage['GlobalParameter7']='195'; $slideTags[195]='parameters email'; $slideTopics[195]='';
$slide[196]='UserParameter'; $slideName[196]='User parameters'; $slidePage['UserParameter']='196'; $slideTags[196]='parameters'; $slideTopics[196]='';
$slide[197]='TranslatableName'; $slideName[197]='Translatable name'; $slidePage['translatableName']='197'; $slideTags[197]='translatable translation name profile'; $slideTopics[197]='AccessProfile ConnectionProfile';
$slide[198]='AutomaticEmailing'; $slideName[198]='Automatic emailing'; $slidePage['AutomaticEmailing']='198'; $slideTags[198]=''; $slideTopics[198]='Mail Status GuiGenerality Creation Update Delete';
$slide[199]='API'; $slideName[199]='api'; $slidePage['api']='199'; $slideTags[199]='api'; $slideTopics[199]='';
$slide[200]='API'; $slideName[200]='call api'; $slidePage['apiCode']='200'; $slideTags[200]='api'; $slideTopics[200]='';
$slide[201]='LinkedElements'; $slideName[201]='Linked elements'; $slidePage['LinkedElements']='201'; $slideTags[201]='link linked'; $slideTopics[201]='';
$slide[202]='Attachments'; $slideName[202]='Attachments'; $slidePage['Attachments']='202'; $slideTags[202]='attach file link privacy'; $slideTopics[202]='Ticket Activity Milestone Risk Issue Meeting Decision Question Parameters4 UserParameters';
$slide[203]='Notes'; $slideName[203]='Notes'; $slidePage['Notes']='203'; $slideTags[203]='note comment privacy predefined'; $slideTopics[203]='Ticket Activity Milestone Risk Action Issue Meeting Decision Question UserParameters';
$slide[204]='ChangeHistory'; $slideName[204]='Change history'; $slidePage['ChangeHistory']='204'; $slideTags[204]='change history track update'; $slideTopics[204]='UserParameters';
$slide[205]='Backup'; $slideName[205]='Backup / Restore'; $slidePage['Backup']='205'; $slideTags[205]='backup restore'; $slideTopics[205]='';
$slide[206]='Shortcuts'; $slideName[206]='Shortcuts'; $slidePage['Shortcuts']='206'; $slideTags[206]='shortcut key'; $slideTopics[206]='';
$slide[207]='LastWords'; $slideName[207]='Last words'; $slidePage['LastWords']='207'; $slideTags[207]='murphy hofstader history version'; $slideTopics[207]='';

if (! isset($includeManual)) {
  foreach ($slide as $id=>$name) {
    echo 'slide[' . $id . ']=' . $name . '<br/>';
  }
}

$prec='';
foreach ($slide as $id=>$name) {
  if (substr($name,0,2)=='X ') {
    unset($slide[$id]);
    unset($slideName[$id]);
    unset($slidePage[$id]);
    unset($slideTags[$id]);
    unset($slideTopics[$id]);
  } else {
    if ($name!=$prec) {
      $section[$id]=$name;
      $sectionName[$name]=$slideName[$id];
      $prec=$name;
    }
  }
}
$tags=array();
foreach ($slideTags as $id=>$name) {
 $split=explode(" ",$name);
 foreach ($split as $tag) {
   if (trim($tag) and !array_key_exists($tag, $tags)) {
     $tags[$tag]=array();
   }
   $tags[$tag][]=$id;
 }
}
ksort($tags);