<?php
$section=array();
$sectionName=array();
$topics=array();
$tags=array();
$page=array();
$slideRoot='img';
$slideExt='.png';

$slide[0]='Welcome '; $slideName[0]='Welcome'; $slidePage['Welcome']='0'; $slideTags[0]='welcome home'; $slideTopics[0]='';
$slide[1]='Functional'; $slideName[1]='Functional '; $slidePage['Functional1']='1'; $slideTags[1]='functional'; $slideTopics[1]='Ticket Activity Milestone Action Planning Workload Cost Report';
$slide[2]='Functional'; $slideName[2]='Functional (2)'; $slidePage['Functional2']='2'; $slideTags[2]='functional'; $slideTopics[2]='Expense Bill Risk Action Issue Meeting Decision Question Message Import ';
$slide[3]='Functional'; $slideName[3]='Functional (3)'; $slidePage['Functional3']='3'; $slideTags[3]='functional'; $slideTopics[3]='Client User Resource AccessRight Calendar';
$slide[4]='Functional'; $slideName[4]='Functional (4)'; $slidePage['Functional4']='4'; $slideTags[4]='functional'; $slideTopics[4]='Document Requirement Test Parameter';
$slide[5]='Functional'; $slideName[5]='Functional (5)'; $slidePage['Functional5']='5'; $slideTags[5]='functional'; $slideTopics[5]='AccessProfile GuiFilter';
$slide[6]='Technical'; $slideName[6]='Technical'; $slidePage['Technical1']='6'; $slideTags[6]='technical gui interface ajax browser'; $slideTopics[6]='GuiGenerality';
$slide[7]='Technical'; $slideName[7]='Technical (2)'; $slidePage['Technical2']='7'; $slideTags[7]='install setup deploy'; $slideTopics[7]='Installation';
$slide[8]='Technical'; $slideName[8]='Technical (3)'; $slidePage['Technical3']='8'; $slideTags[8]='parameter'; $slideTopics[8]='Parameters1';
$slide[9]='Installation'; $slideName[9]='Installation'; $slidePage['Installation']='9'; $slideTags[9]='install setup deploy php mysql http server zip'; $slideTopics[9]='Configuration Parameters1 NewVersion Connection';
$slide[10]='Configuration'; $slideName[10]='Configuration'; $slidePage['Configuration']='10'; $slideTags[10]='install setup config parameter'; $slideTopics[10]='Installation Parameters1 NewVersion Connection';
$slide[11]='Parameters'; $slideName[11]='Parameters'; $slidePage['Parameters1']='11'; $slideTags[11]='config parameter install setup'; $slideTopics[11]='Installation Configuration NewVersion';
$slide[12]='Parameters'; $slideName[12]='Parameters (2)'; $slidePage['Parameters2']='12'; $slideTags[12]='config parameter install setup'; $slideTopics[12]='Installation Configuration NewVersion';
$slide[13]='Parameters'; $slideName[13]='Parameters (3)'; $slidePage['Parameters3']='13'; $slideTags[13]='config parameter install setup'; $slideTopics[13]='Installation Configuration NewVersion';
$slide[14]='Parameters'; $slideName[14]='Parameters (4)'; $slidePage['Parameters4']='14'; $slideTags[14]='config parameter install setup'; $slideTopics[14]='Installation Configuration NewVersion';
$slide[15]='Parameters'; $slideName[15]='Parameters (5)'; $slidePage['Parameters5']='15'; $slideTags[15]='config parameter install setup'; $slideTopics[15]='Installation Configuration NewVersion';
$slide[16]='NewVersion'; $slideName[16]='Install new version'; $slidePage['NewVersion']='16'; $slideTags[16]='install setup deploy php mysql http server zip new version release update'; $slideTopics[16]='Installation Configuration Parameters1';
$slide[17]='Connection'; $slideName[17]='Connection'; $slidePage['Connection']='17'; $slideTags[17]='connect login'; $slideTopics[17]='GuiGenerality Installation Configuration';
$slide[18]='GUI'; $slideName[18]='User interface'; $slidePage['GuiGenerality']='18'; $slideTags[18]='gui interface'; $slideTopics[18]='Themes GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[19]='GUI'; $slideName[19]='Toolbars'; $slidePage['GuiToolbar']='19'; $slideTags[19]='gui interface toolbar show hide switch help manual hyperlink logo external-shortcuts shortcuts'; $slideTopics[19]='Themes GuiGenerality GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[20]='GUI'; $slideName[20]='Menu'; $slidePage['GuiMenu']='20'; $slideTags[20]='gui interface menu project combo'; $slideTopics[20]='Themes GuiGenerality GuiToolbar GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[21]='GUI'; $slideName[21]='Quick Menu'; $slidePage['GuiQuickMenu']='21'; $slideTags[21]='gui interface menu project combo'; $slideTopics[21]='Themes GuiGenerality GuiToolbar GuiMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[22]='GUI'; $slideName[22]='List'; $slidePage['GuiList']='22'; $slideTags[22]='gui interface list column'; $slideTopics[22]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[23]='GUI'; $slideName[23]='Filter'; $slidePage['GuiFilter']='23'; $slideTags[23]='gui interface filter complex'; $slideTopics[23]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[24]='GUI'; $slideName[24]='Detail'; $slidePage['GuiDetail']='24'; $slideTags[24]='gui interface detail item save print'; $slideTopics[24]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiCombo GuiAlert GuiProject';
$slide[25]='GUI'; $slideName[25]='Combo detail'; $slidePage['GuiCombo']='25'; $slideTags[25]='gui interface detail item save print combo list'; $slideTopics[25]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail  GuiAlert GuiProject';
$slide[26]='GUI'; $slideName[26]='Alert'; $slidePage['GuiAlert']='26'; $slideTags[26]='gui interface detail item save print combo list alert info warning'; $slideTopics[26]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiProject';
$slide[27]='Themes'; $slideName[27]='Themes'; $slidePage['Themes']='27'; $slideTags[27]='theme color'; $slideTopics[27]='GuiGenerality ThemesTemplates';
$slide[28]='Themes'; $slideName[28]='Themes templates'; $slidePage['ThemesTemplates']='28'; $slideTags[28]='theme color example'; $slideTopics[28]='GuiGenerality Themes';
$slide[29]='Multilingual'; $slideName[29]='Multilingual'; $slidePage['Multilingual']='29'; $slideTags[29]='english french german translat multiling'; $slideTopics[29]='GuiGenerality Configuration Parameters1';
$slide[30]='Creation'; $slideName[30]='Creation'; $slidePage['Creation']='30'; $slideTags[30]='creation'; $slideTopics[30]='GuiGenerality Update Delete Copy';
$slide[31]='Update'; $slideName[31]='Update'; $slidePage['Update']='31'; $slideTags[31]='update'; $slideTopics[31]='GuiGenerality Creation Delete copy';
$slide[32]='Delete'; $slideName[32]='Delete'; $slidePage['Delete']='32'; $slideTags[32]='delete'; $slideTopics[32]='GuiGenerality Creation Update Copy';
$slide[33]='Copy'; $slideName[33]='Copy'; $slidePage['Copy']='33'; $slideTags[33]='copy'; $slideTopics[33]='GuiGenerality Creation Update Delete';
$slide[34]='MultipleUpdate'; $slideName[34]='Multiple Update'; $slidePage['MultipleUpdate']='34'; $slideTags[34]='multiple update several grouped'; $slideTopics[34]='GuiGenerality Update';
$slide[35]='Today'; $slideName[35]='Today'; $slidePage['Today']='35'; $slideTags[35]='today summary todo message'; $slideTopics[35]='Message Project Ticket Activity Milestone Risk Action Issue';
$slide[36]='Today'; $slideName[36]='Today parameters'; $slidePage['TodayParameters']='36'; $slideTags[36]='today summary todo message'; $slideTopics[36]='Message Project Ticket Activity Milestone Risk Action Issue Report';
$slide[37]='Project'; $slideName[37]='Project'; $slidePage['Project']='37'; $slideTags[37]='project planning sub-project'; $slideTopics[37]='ProjectFields ProjectProgress ProjectAffectation ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[38]='Project'; $slideName[38]='Project fields'; $slidePage['ProjectFields']='38'; $slideTags[38]='project planning sub-project hyperlink external-shortcuts shortcuts'; $slideTopics[38]='Project ProjectAffectation ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning Affectation Customer';
$slide[39]='Project'; $slideName[39]='Project affectations and versions'; $slidePage['ProjectAffectation']='39'; $slideTags[39]='project planning affectation version'; $slideTopics[39]='Project ProjectFields ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[40]='Project'; $slideName[40]='Project progress'; $slidePage['ProjectProgress']='40'; $slideTags[40]='project planning'; $slideTopics[40]='Project ProjectFields ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[41]='Project'; $slideName[41]='Project dependencies'; $slidePage['ProjectDependencies']='41'; $slideTags[41]='project planning'; $slideTopics[41]='Project ProjectFields ProjectProgress ProjectAffectation GuiGenerality Creation Update Delete Planning';
$slide[42]='Document'; $slideName[42]='Document'; $slidePage['Document']='42'; $slideTags[42]='document directory file'; $slideTopics[42]='DocumentFields DocumentVersions DocumentDirectory DocumentApprovers Product Project';
$slide[43]='Document'; $slideName[43]='Document fields'; $slidePage['DocumentFields']='43'; $slideTags[43]='document directory file'; $slideTopics[43]='Document DocumentVersions DocumentDirectory DocumentApprovers Product Project LinkedElements';
$slide[44]='Document'; $slideName[44]='Document versions'; $slidePage['DocumentVersions']='44'; $slideTags[44]='document directory file version'; $slideTopics[44]='Document DocumentFields DocumentDirectory DocumentApprovers Product Project';
$slide[45]='Document'; $slideName[45]='Document approvers'; $slidePage['DocumentApprovers']='45'; $slideTags[45]='document directory file version approvers approve'; $slideTopics[45]='Document DocumentFields DocumentDirectory DocumentVersion Product Project';
$slide[46]='Ticket'; $slideName[46]='Ticket'; $slidePage['Ticket']='46'; $slideTags[46]='ticket bug task track'; $slideTopics[46]='TicketFields TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[47]='Ticket'; $slideName[47]='Ticket fields'; $slidePage['TicketFields']='47'; $slideTags[47]='ticket bug task track'; $slideTopics[47]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[48]='Ticket'; $slideName[48]='Ticket fields'; $slidePage['TicketFields2']='48'; $slideTags[48]='ticket bug task track work timer'; $slideTopics[48]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[49]='TicketSimple'; $slideName[49]='Simple Ticket'; $slidePage['TicketSimple']='49'; $slideTags[49]='ticket bug task track simple'; $slideTopics[49]='TicketSimpleFields Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[50]='TicketSimple'; $slideName[50]='Simple Ticket fields'; $slidePage['TicketSimpleFields']='50'; $slideTags[50]='ticket bug task track simple'; $slideTopics[50]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[51]='TicketSimple'; $slideName[51]='Simple Ticket fields'; $slidePage['TicketSimpleFields2']='51'; $slideTags[51]='ticket bug task track simple'; $slideTopics[51]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[52]='Activity'; $slideName[52]='Activity'; $slidePage['Activity']='52'; $slideTags[52]='activity task planning'; $slideTopics[52]='ActivityFields ActivityAssignment ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[53]='Activity'; $slideName[53]='Activity fields'; $slidePage['ActivityFields']='53'; $slideTags[53]='activity task planning'; $slideTopics[53]='Activity ActivityAssignement ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[54]='Activity'; $slideName[54]='Activity assignment'; $slidePage['ActivityAssignement']='54'; $slideTags[54]='activity task planning assignment'; $slideTopics[54]='Activity ActivityFields ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[55]='Activity'; $slideName[55]='Activity progress'; $slidePage['ActivityProgress']='55'; $slideTags[55]='activity task planning progress'; $slideTopics[55]='Activity ActivityFields ActivityAssignment ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[56]='Activity'; $slideName[56]='Activity dependency'; $slidePage['ActivityDependencies']='56'; $slideTags[56]='activity task planning'; $slideTopics[56]='Activity ActivityFields ActivityAssignment ActivityProgress GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[57]='Milestone'; $slideName[57]='Milestone'; $slidePage['Milestone']='57'; $slideTags[57]='milestone flag '; $slideTopics[57]='MilestoneFields MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[58]='Milestone'; $slideName[58]='Milestone fields'; $slidePage['MilestoneFields']='58'; $slideTags[58]='milestone flag '; $slideTopics[58]='Milestone MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[59]='Milestone'; $slideName[59]='Milestone progress'; $slidePage['MilestoneProgress']='59'; $slideTags[59]='milestone flag '; $slideTopics[59]='Milestone MilestoneFields MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[60]='Milestone'; $slideName[60]='Milestone dependencies'; $slidePage['MilestoneDependencies']='60'; $slideTags[60]='milestone flag '; $slideTopics[60]='Milestone MilestoneFields MilestoneProgress GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[61]='Action'; $slideName[61]='Action'; $slidePage['Action']='61'; $slideTags[61]='risk action issue'; $slideTopics[61]='ActionFields ActionDependencies Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[62]='Action'; $slideName[62]='Action fields'; $slidePage['ActionFields']='62'; $slideTags[62]='risk action issue'; $slideTopics[62]='Action ActionDependencies Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[63]='Action'; $slideName[63]='Action dependencies'; $slidePage['ActionDependencies']='63'; $slideTags[63]='risk action issue'; $slideTopics[63]='Action ActionFields Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[64]='Imputation'; $slideName[64]='Real work allocation'; $slidePage['Imputation']='64'; $slideTags[64]='imputation work follow-up allocation'; $slideTopics[64]='Activity ActivityAssignement Planning Resource Project Affectation';
$slide[65]='Planning'; $slideName[65]='Planning'; $slidePage['Planning1']='65'; $slideTags[65]='planning work plan date calculation gantt'; $slideTopics[65]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[66]='Planning'; $slideName[66]='Planning (2)'; $slidePage['Planning2']='66'; $slideTags[66]='planning work plan date calculation gantt'; $slideTopics[66]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[67]='Planning'; $slideName[67]='Planning (3)'; $slidePage['Planning3']='67'; $slideTags[67]='planning work plan date calculation gantt'; $slideTopics[67]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[68]='Planning'; $slideName[68]='Planning (4)'; $slidePage['Planning4']='68'; $slideTags[68]='planning work plan date calculation gantt'; $slideTopics[68]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[69]='Planning'; $slideName[69]='Planning (5)'; $slidePage['Planning5']='69'; $slideTags[69]='planning work plan date calculation gantt'; $slideTopics[69]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[70]='PortfolioPlanning'; $slideName[70]='Projects portfolio'; $slidePage['PortfolioPlanning']='70'; $slideTags[70]='planning gantt portfolio'; $slideTopics[70]='Planning';
$slide[71]='ResourcePlanning'; $slideName[71]='Resource Planning'; $slidePage['ResourcePlanning']='71'; $slideTags[71]='planning work plan date calculation gantt resource'; $slideTopics[71]='ActivityAssignement ActivityProgress ActivityDependencies Planning';
$slide[72]='Report'; $slideName[72]='Report'; $slidePage['Report']='72'; $slideTags[72]='parameter report print '; $slideTopics[72]='';
$slide[73]='Requirement'; $slideName[73]='Requirement'; $slidePage['Requirement']='73'; $slideTags[73]='requirement'; $slideTopics[73]='RequirementFields TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[74]='Requirement'; $slideName[74]='Requirement fields'; $slidePage['RequirementFields']='74'; $slideTags[74]='requirement'; $slideTopics[74]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[75]='Requirement'; $slideName[75]='Requirement fields'; $slidePage['RequirementFields2']='75'; $slideTags[75]='requirement'; $slideTopics[75]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[76]='TestCase'; $slideName[76]='Test case'; $slidePage['TestCase']='76'; $slideTags[76]='test case'; $slideTopics[76]='TestCaseFields Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[77]='TestCase'; $slideName[77]='Test case fields'; $slidePage['TestCaseFields']='77'; $slideTags[77]='test case'; $slideTopics[77]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[78]='TestCase'; $slideName[78]='Test case fields'; $slidePage['TestCaseFields2']='78'; $slideTags[78]='test case'; $slideTopics[78]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[79]='TestSession'; $slideName[79]='Test session'; $slidePage['TestSession']='79'; $slideTags[79]='test session'; $slideTopics[79]='TestSessionFields Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[80]='TestSession'; $slideName[80]='Test session fields'; $slidePage['TestSessionFields']='80'; $slideTags[80]='test session'; $slideTopics[80]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[81]='TestSession'; $slideName[81]='Test session fields'; $slidePage['TestSessionFields2']='81'; $slideTags[81]='test session'; $slideTopics[81]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[82]='IndividualExpense'; $slideName[82]='Individual expense'; $slidePage['IndividualExpense']='82'; $slideTags[82]='expense cost travel '; $slideTopics[82]='IndividualExpenseFields IndividualExpenseDetails ProjectExpense';
$slide[83]='IndividualExpense'; $slideName[83]='Individual expense fields'; $slidePage['IndividualExpenseFields']='83'; $slideTags[83]='expense cost travel '; $slideTopics[83]='IndividualExpense IndividualExpenseDetails ProjectExpense';
$slide[84]='IndividualExpense'; $slideName[84]='Individual expense details'; $slidePage['IndividualExpenseDetails']='84'; $slideTags[84]='expense cost travel detail'; $slideTopics[84]='IndividualExpenseFields IndividualExpense ProjectExpense';
$slide[85]='ProjectExpense'; $slideName[85]='Project expense'; $slidePage['ProjectExpense']='85'; $slideTags[85]='expense'; $slideTopics[85]='ProjectExpenseFields IndividualExpense';
$slide[86]='ProjectExpense'; $slideName[86]='Project expense fields'; $slidePage['ProjectExpenseFields']='86'; $slideTags[86]='expense'; $slideTopics[86]='ProjectExpense IndividualExpense';
$slide[87]='Term'; $slideName[87]='Term'; $slidePage['Term']='87'; $slideTags[87]='term trigger bill fixed price'; $slideTopics[87]='TermFileds Bill';
$slide[88]='Term'; $slideName[88]='Term fields'; $slidePage['TermFields']='88'; $slideTags[88]='term trigger bill fixed price'; $slideTopics[88]='Term Bill';
$slide[89]='Bill'; $slideName[89]='Bill'; $slidePage['Bill']='89'; $slideTags[89]='bill billing'; $slideTopics[89]='Term Bill ActivityPrice BillingType BillType';
$slide[90]='Bill'; $slideName[90]='Bill fields'; $slidePage['BillFields']='90'; $slideTags[90]='bill billing'; $slideTopics[90]='Term Bill ActivityPrice BillingType BillType Recipient Contact';
$slide[91]='Bill'; $slideName[91]='Bill lines'; $slidePage['BillLines']='91'; $slideTags[91]='risk action issue opportunity'; $slideTopics[91]='Term Bill ActivityPrice BillingType BillType';
$slide[92]='ActivityPrice'; $slideName[92]='Activity price'; $slidePage['ActivityPrice']='92'; $slideTags[92]='risk action issue opportunity'; $slideTopics[92]='Activity ActivityType BillingType';
$slide[93]='Risk'; $slideName[93]='Risk'; $slidePage['Risk']='93'; $slideTags[93]='risk action issue'; $slideTopics[93]='RiskFields Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[94]='Risk'; $slideName[94]='Risk fields'; $slidePage['RiskFields']='94'; $slideTags[94]='risk action issue'; $slideTopics[94]='Risk Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[95]='Opportunity'; $slideName[95]='Opportunity'; $slidePage['Opportunity']='95'; $slideTags[95]='meeting workshop steering committee invitation attendees'; $slideTopics[95]='OpportunityFields Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[96]='Opportunity'; $slideName[96]='Opportunity fields'; $slidePage['OpportunityFields']='96'; $slideTags[96]='meeting workshop steering committee'; $slideTopics[96]='Opportunity Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[97]='Issue'; $slideName[97]='Issue'; $slidePage['Issue']='97'; $slideTags[97]='risk action issue'; $slideTopics[97]='IssueFields IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[98]='Issue'; $slideName[98]='Issue fields'; $slidePage['IssueFields']='98'; $slideTags[98]='risk action issue'; $slideTopics[98]='Issue IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[99]='Meeting'; $slideName[99]='Meeting'; $slidePage['Meeting']='99'; $slideTags[99]='meeting workshop steering committee invitation attendees'; $slideTopics[99]='MeetingFields MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[100]='Meeting'; $slideName[100]='Meeting fields'; $slidePage['MeetingFields']='100'; $slideTags[100]='meeting workshop steering committee'; $slideTopics[100]='Meeting MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[101]='PeriodicMeeting'; $slideName[101]='Periodic meeting'; $slidePage['PeriodicMeeting']='101'; $slideTags[101]='meeting workshop steering committee invitation attendees periodic'; $slideTopics[101]='PeriodicMeetingFields Meeting MeetingType';
$slide[102]='PeriodicMeeting'; $slideName[102]='Periodic meeting fields'; $slidePage['PeriodicMeetingFields']='102'; $slideTags[102]='meeting workshop steering committee periodic'; $slideTopics[102]='PeriodicMeeting Meeting MeetingType';
$slide[103]='Decision'; $slideName[103]='Decision'; $slidePage['Decision']='103'; $slideTags[103]='decision'; $slideTopics[103]='DecisionFields DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[104]='Decision'; $slideName[104]='Decision fields'; $slidePage['DecisionFields']='104'; $slideTags[104]='decision'; $slideTopics[104]='Decision DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[105]='Question'; $slideName[105]='Question'; $slidePage['Question']='105'; $slideTags[105]='question answer'; $slideTopics[105]='QuestionFields QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[106]='Question'; $slideName[106]='Question fields'; $slidePage['QuestionFields']='106'; $slideTags[106]='question answer'; $slideTopics[106]='Question QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[107]='Mail'; $slideName[107]='Emails'; $slidePage['Mail']='107'; $slideTags[107]='email mail'; $slideTopics[107]='AutomaticEmailing';
$slide[108]='Alert'; $slideName[108]='Alerts'; $slidePage['Alert']='108'; $slideTags[108]='alert warning information indicator'; $slideTopics[108]='GuiAlert IndicatorDefinition';
$slide[109]='Message'; $slideName[109]='Message'; $slidePage['Message']='109'; $slideTags[109]='message alert'; $slideTopics[109]='User Project Profile Today';
$slide[110]='Import'; $slideName[110]='Import'; $slidePage['Import']='110'; $slideTags[110]='import load'; $slideTopics[110]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[111]='Import'; $slideName[111]='Import Run'; $slidePage['ImportRun']='111'; $slideTags[111]='import load'; $slideTopics[111]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[112]='AutomaticImport'; $slideName[112]='Automatic Import'; $slidePage['AutomaticImport']='112'; $slideTags[112]='automatic automated import cron'; $slideTopics[112]='Import GlobalParameter';
$slide[113]='Affectation'; $slideName[113]='Affectation'; $slidePage['Affectation']='113'; $slideTags[113]='affectation resource contact user project'; $slideTopics[113]='GuiGenerality Resource Contact User Project';
$slide[114]='User'; $slideName[114]='User'; $slidePage['User']='114'; $slideTags[114]='contact resource user login password'; $slideTopics[114]='GuiGenerality Contact Resource UserAffectation';
$slide[115]='User'; $slideName[115]='User affectations'; $slidePage['UserAffectation']='115'; $slideTags[115]='contact resource user login password affectation'; $slideTopics[115]='GuiGenerality Contact Resource User';
$slide[116]='Resource'; $slideName[116]='Resource description'; $slidePage['Resource']='116'; $slideTags[116]='resource capacity affectation'; $slideTopics[116]='ResourceCost GuiGenerality User Contact Team Planning Affectation';
$slide[117]='Resource'; $slideName[117]='Resource function cost & affectation'; $slidePage['ResourceCost']='117'; $slideTags[117]='resource capacity affectation cost'; $slideTopics[117]='GuiGenerality User Contact Team Planning Affectation Resource';
$slide[118]='Contact'; $slideName[118]='Contact'; $slidePage['Contact']='118'; $slideTags[118]='contact customer requestor'; $slideTopics[118]='Client User GuiGenerality Creation Update Delete AutomaticEmailing ContactAffectation';
$slide[119]='Contact'; $slideName[119]='Contact affectations'; $slidePage['ContactAffectation']='119'; $slideTags[119]='contact customer requestor affectation'; $slideTopics[119]='Client User GuiGenerality Creation Update Delete AutomaticEmailing Contact';
$slide[120]='Client'; $slideName[120]='Customer'; $slidePage['Client']='120'; $slideTags[120]='client customer contact'; $slideTopics[120]='Contact Project GuiGenerality Creation Update Delete';
$slide[121]='Recipient'; $slideName[121]='Recipient'; $slidePage['Recipient']='121'; $slideTags[121]='recipient bill'; $slideTopics[121]='Bill';
$slide[122]='Team'; $slideName[122]='Team'; $slidePage['Team']='122'; $slideTags[122]='team resource affectation'; $slideTopics[122]='GuiGenerality Resource';
$slide[123]='Product'; $slideName[123]='Product'; $slidePage['Product']='123'; $slideTags[123]='product version'; $slideTopics[123]='Version Project Customer Contact';
$slide[124]='Version'; $slideName[124]='Version'; $slidePage['Version']='124'; $slideTags[124]='product version'; $slideTopics[124]='Product Project Customer Contact';
$slide[125]='Context'; $slideName[125]='Context'; $slidePage['Context']='125'; $slideTags[125]='context environment os browser'; $slideTopics[125]='Ticket TranslatableName';
$slide[126]='Calendar'; $slideName[126]='Calendar'; $slidePage['Calendar']='126'; $slideTags[126]='calendar off open closed day'; $slideTopics[126]='GuiGenerality Planning';
$slide[127]='DocumentDirectory'; $slideName[127]='Document directory'; $slidePage['DocumentDirectory']='127'; $slideTags[127]='document directory folder place'; $slideTopics[127]='Document';
$slide[128]='Role'; $slideName[128]='Function'; $slidePage['Role']='128'; $slideTags[128]='function resource cost'; $slideTopics[128]='GuiGenerality Resource';
$slide[129]='Status'; $slideName[129]='Status'; $slidePage['Status']='129'; $slideTags[129]='status workflow lifecycle'; $slideTopics[129]='Workflow Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[130]='HealthStatus'; $slideName[130]='HealthStatus'; $slidePage['HealthStatus']='130'; $slideTags[130]='health'; $slideTopics[130]='Project Today';
$slide[131]='Likelihood'; $slideName[131]='Likelihood'; $slidePage['Likelihood']='131'; $slideTags[131]='likelihood probability'; $slideTopics[131]='GuiGenerality criticality severity risk';
$slide[132]='Criticality'; $slideName[132]='Criticality'; $slidePage['Criticality']='132'; $slideTags[132]='criticality'; $slideTopics[132]='GuiGenerality risk ticket likelihood severity priority urgency';
$slide[133]='Severity'; $slideName[133]='Severity'; $slidePage['Severity']='133'; $slideTags[133]='severity'; $slideTopics[133]='GuiGenerality risk criticality likelihood';
$slide[134]='Urgency'; $slideName[134]='Urgency'; $slidePage['Urgency']='134'; $slideTags[134]='urgency priority'; $slideTopics[134]='GuiGenerality ticket priority criticality';
$slide[135]='Priority'; $slideName[135]='Priority'; $slidePage['Priority']='135'; $slideTags[135]='priority urgency'; $slideTopics[135]='GuiGenerality urgency criticality ticket';
$slide[136]='RiskLevel'; $slideName[136]='Risk level'; $slidePage['RiskLevel']='136'; $slideTags[136]='risk level'; $slideTopics[136]='GuiGenerality';
$slide[137]='Feasibility'; $slideName[137]='Feasibility'; $slidePage['Feasibility']='137'; $slideTags[137]='feasibility'; $slideTopics[137]='GuiGenerality';
$slide[138]='Efficiency'; $slideName[138]='Efficiency'; $slidePage['Efficiency']='138'; $slideTags[138]='efficiency'; $slideTopics[138]='GuiGenerality Action';
$slide[139]='PredefinedNote'; $slideName[139]='Predefined note'; $slidePage['PredefinedNote']='139'; $slideTags[139]='predefined note text'; $slideTopics[139]='Notes';
$slide[140]='Workflow'; $slideName[140]='Workflow description'; $slidePage['Workflow']='140'; $slideTags[140]='workflow status'; $slideTopics[140]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[141]='Workflow'; $slideName[141]='Workflow table'; $slidePage['WorkflowTable']='141'; $slideTags[141]='workflow status'; $slideTopics[141]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[142]='StatusMail'; $slideName[142]='Mail on events'; $slidePage['StatusMail']='142'; $slideTags[142]='mail emailing status'; $slideTopics[142]='GuiGenerality Mail Status AutomaticEmailing ReplyToEmails';
$slide[143]='ReplyToEmail'; $slideName[143]='Reply to emails'; $slidePage['ReplyToEmail']='143'; $slideTags[143]='mail emailing reply'; $slideTopics[143]='GuiGenerality MailAutomaticEmailing';
$slide[144]='TicketDelay'; $slideName[144]='Delay for tickets'; $slidePage['TicketDelay']='144'; $slideTags[144]='delay ticket'; $slideTopics[144]='GuiGenerality Ticket';
$slide[145]='IndicatorDefinition'; $slideName[145]='Indicator'; $slidePage['IndicatorDefinition']='145'; $slideTags[145]='delay indicator alert warning'; $slideTopics[145]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[146]='ProjectType'; $slideName[146]='Project type'; $slidePage['ProjectType']='146'; $slideTags[146]='project type template administrative operational billing'; $slideTopics[146]='Project Bill';
$slide[147]='TicketType'; $slideName[147]='Ticket type'; $slidePage['TicketType']='147'; $slideTags[147]='type ticket'; $slideTopics[147]='Ticket GuiGenerality';
$slide[148]='ActivityType'; $slideName[148]='Activity type'; $slidePage['ActivityType']='148'; $slideTags[148]='activity type'; $slideTopics[148]='Activity GuiGenerality';
$slide[149]='MilestoneType'; $slideName[149]='Milestone type'; $slidePage['MilestoneType']='149'; $slideTags[149]='milestone type'; $slideTopics[149]='Milestone GuiGenerality';
$slide[150]='IndividualExpenseType'; $slideName[150]='Individual expense type'; $slidePage['IndividualExpenseType']='150'; $slideTags[150]='expense type'; $slideTopics[150]='IndividualExpense GuiGenerality';
$slide[151]='ProjectExpenseType'; $slideName[151]='Project expensetype'; $slidePage['ProjectExpenseType']='151'; $slideTags[151]='expense type'; $slideTopics[151]='ProjectExpense GuiGenerality';
$slide[152]='ExpenseDetailType'; $slideName[152]='Expense detail type'; $slidePage['ExpenseDetailType']='152'; $slideTags[152]='expense type'; $slideTopics[152]='IndividualExpense ProjectExpense GuiGenerality';
$slide[153]='BillType'; $slideName[153]='Bill type'; $slidePage['BillType']='153'; $slideTags[153]='bill type'; $slideTopics[153]='Bill GuiGenerality Creation Update Delete';
$slide[154]='RiskType'; $slideName[154]='Risk type'; $slidePage['RiskType']='154'; $slideTags[154]='risk type'; $slideTopics[154]='Risk GuiGenerality Creation Update Delete';
$slide[155]='RiskType'; $slideName[155]='Opportunity type'; $slidePage['Opportunity Type']='155'; $slideTags[155]='opportunity type'; $slideTopics[155]='Opportunity GuiGenerality Creation Update Delete';
$slide[156]='ActionType'; $slideName[156]='Action type'; $slidePage['ActionType']='156'; $slideTags[156]='action type'; $slideTopics[156]='Action GuiGenerality Creation Update Delete';
$slide[157]='IssueType'; $slideName[157]='Issue type'; $slidePage['IssueType']='157'; $slideTags[157]='issue type'; $slideTopics[157]='Issue GuiGenerality Creation Update Delete';
$slide[158]='MeetingType'; $slideName[158]='Meeting type'; $slidePage['MeetingType']='158'; $slideTags[158]='meeting type'; $slideTopics[158]='Meeting GuiGenerality Creation Update Delete';
$slide[159]='DecisionType'; $slideName[159]='Decision type'; $slidePage['DecisionType']='159'; $slideTags[159]='decision type'; $slideTopics[159]='Decision GuiGenerality Creation Update Delete';
$slide[160]='QuestionType'; $slideName[160]='Question type'; $slidePage['QuestionType']='160'; $slideTags[160]='question type'; $slideTopics[160]='Question GuiGenerality Creation Update Delete';
$slide[161]='MessageType'; $slideName[161]='Message type'; $slidePage['MessageType']='161'; $slideTags[161]='message type'; $slideTopics[161]='Message GuiGenerality Creation Update Delete';
$slide[162]='DocumentType'; $slideName[162]='Document type'; $slidePage['DocumentType']='162'; $slideTags[162]='document type'; $slideTopics[162]='Document GuiGenerality Creation Update Delete';
$slide[163]='ContextType'; $slideName[163]='Context type'; $slidePage['ContextType']='163'; $slideTags[163]='context type'; $slideTopics[163]='Context GuiGenerality Creation Update Delete';
$slide[164]='RequirementType'; $slideName[164]='Requirement type'; $slidePage['RequirementType']='164'; $slideTags[164]='requirement type'; $slideTopics[164]='Requirement GuiGenerality Creation Update Delete';
$slide[165]='TestCaseType'; $slideName[165]='Test case type'; $slidePage['TestCaseType']='165'; $slideTags[165]='test case type'; $slideTopics[165]='TestCase GuiGenerality Creation Update Delete';
$slide[166]='TestSessionType'; $slideName[166]='Test session type'; $slidePage['TestSessionType']='166'; $slideTags[166]='test session type'; $slideTopics[166]='TestSession GuiGenerality Creation Update Delete';
$slide[167]='Profile'; $slideName[167]='Profile'; $slidePage['Profile']='167'; $slideTags[167]='connection profile'; $slideTopics[167]='TranslatableName User';
$slide[168]='AccessProfile'; $slideName[168]='Access mode'; $slidePage['AccessProfile']='168'; $slideTags[168]='access mode read write update delete'; $slideTopics[168]='TranslatableName User Resource Profile';
$slide[169]='Habilitation'; $slideName[169]='Access to forms'; $slidePage['Habilitation']='169'; $slideTags[169]='ticket bug task track habilitation'; $slideTopics[169]='Profile AccessRight';
$slide[170]='HabilitationReport'; $slideName[170]='Access to reports'; $slidePage['HabilitationReport']='170'; $slideTags[170]='access report rights'; $slideTopics[170]='Profile';
$slide[171]='AccessRight'; $slideName[171]='Access mode to data'; $slidePage['AccessMode']='171'; $slideTags[171]='access screen form rights'; $slideTopics[171]='Profile Habilitation';
$slide[172]='HabilitationOther'; $slideName[172]='Specific access mode'; $slidePage['HabilitationOther']='172'; $slideTags[172]='access specific'; $slideTopics[172]='User Profile GuiCombo';
$slide[173]='HabilitationOther'; $slideName[173]='Specific access mode'; $slidePage['HabilitationOther2']='173'; $slideTags[173]='access specific'; $slideTopics[173]='User Profile GuiCombo';
$slide[174]='Administration'; $slideName[174]='Global parameters'; $slidePage['Administration']='174'; $slideTags[174]='administration cron maintenance purge'; $slideTopics[174]='';
$slide[175]='Audit'; $slideName[175]='Audit connections'; $slidePage['Audit']='175'; $slideTags[175]='connections who_is_online'; $slideTopics[175]='';
$slide[176]='GlobalParameter'; $slideName[176]='Global parameters'; $slidePage['GlobalParameter']='176'; $slideTags[176]='parameters ldap reference format'; $slideTopics[176]='';
$slide[177]='GlobalParameter'; $slideName[177]='Global parameters'; $slidePage['GlobalParameter2']='177'; $slideTags[177]='parameters ldap billing format'; $slideTopics[177]='';
$slide[178]='GlobalParameter'; $slideName[178]='Global parameters'; $slidePage['GlobalParameter3']='178'; $slideTags[178]='parameters ldap billing format'; $slideTopics[178]='';
$slide[179]='GlobalParameter'; $slideName[179]='Global parameters'; $slidePage['GlobalParameter4']='179'; $slideTags[179]='parameters ldap billing format'; $slideTopics[179]='';
$slide[180]='GlobalParameter'; $slideName[180]='Global parameters'; $slidePage['GlobalParameter5']='180'; $slideTags[180]='parameters ldap billing format'; $slideTopics[180]='';
$slide[181]='UserParameter'; $slideName[181]='User parameters'; $slidePage['UserParameter']='181'; $slideTags[181]='parameters'; $slideTopics[181]='';
$slide[182]='TranslatableName'; $slideName[182]='Translatable name'; $slidePage['translatableName']='182'; $slideTags[182]='translatable translation name profile'; $slideTopics[182]='AccessProfile ConnectionProfile';
$slide[183]='AutomaticEmailing'; $slideName[183]='Automatic emailing'; $slidePage['AutomaticEmailing']='183'; $slideTags[183]=''; $slideTopics[183]='Mail Status GuiGenerality Creation Update Delete';
$slide[184]='LinkedElements'; $slideName[184]='Linked elements'; $slidePage['LinkedElements']='184'; $slideTags[184]='link linked'; $slideTopics[184]='';
$slide[185]='Attachments'; $slideName[185]='Attachments'; $slidePage['Attachments']='185'; $slideTags[185]='attach file link privacy'; $slideTopics[185]='Ticket Activity Milestone Risk Issue Meeting Decision Question Parameters4 UserParameters';
$slide[186]='Notes'; $slideName[186]='Notes'; $slidePage['Notes']='186'; $slideTags[186]='note comment privacy predefined'; $slideTopics[186]='Ticket Activity Milestone Risk Action Issue Meeting Decision Question UserParameters';
$slide[187]='ChangeHistory'; $slideName[187]='Change history'; $slidePage['ChangeHistory']='187'; $slideTags[187]='change history track update'; $slideTopics[187]='UserParameters';
$slide[188]='Backup'; $slideName[188]='Backup / Restore'; $slidePage['Backup']='188'; $slideTags[188]='backup restore'; $slideTopics[188]='';
$slide[189]='Shortcuts'; $slideName[189]='Shortcuts'; $slidePage['Shortcuts']='189'; $slideTags[189]='shortcut key'; $slideTopics[189]='';
$slide[190]='LastWords'; $slideName[190]='Last words'; $slidePage['LastWords']='190'; $slideTags[190]='murphy hofstader history version'; $slideTopics[190]='';

if (! isset($includeManual)) {
  foreach ($slide as $id=>$name) {
    echo 'slide[' . $id . ']=' . $name . '<br/>';
  }
}

$prec='';
foreach ($slide as $id=>$name) {
  if (substr($name,0,2)=='X ') {
    unset($slide[$id]);
    unset($slideName[$id]);
    unset($slidePage[$id]);
    unset($slideTags[$id]);
    unset($slideTopics[$id]);
  } else {
    if ($name!=$prec) {
      $section[$id]=$name;
      $sectionName[$name]=$slideName[$id];
      $prec=$name;
    }
  }
}
$tags=array();
foreach ($slideTags as $id=>$name) {
 $split=explode(" ",$name);
 foreach ($split as $tag) {
   if (trim($tag) and !array_key_exists($tag, $tags)) {
     $tags[$tag]=array();
   }
   $tags[$tag][]=$id;
 }
}
ksort($tags);