<?php
$section=array();
$sectionName=array();
$topics=array();
$tags=array();
$page=array();
$slideRoot='img';
$slideExt='.png';

$slide[0]='Welcome '; $slideName[0]='Welcome'; $slidePage['Welcome']='0'; $slideTags[0]='welcome home'; $slideTopics[0]='';
$slide[1]='Functional'; $slideName[1]='Functional '; $slidePage['Functional1']='1'; $slideTags[1]='functional'; $slideTopics[1]='Ticket Activity Milestone Action Planning Workload Cost Report';
$slide[2]='Functional'; $slideName[2]='Functional (2)'; $slidePage['Functional2']='2'; $slideTags[2]='functional'; $slideTopics[2]='Expense Bill Risk Action Issue Meeting Decision Question Message Import ';
$slide[3]='Functional'; $slideName[3]='Functional (3)'; $slidePage['Functional3']='3'; $slideTags[3]='functional'; $slideTopics[3]='Client User Resource AccessRight Calendar';
$slide[4]='Functional'; $slideName[4]='Functional (4)'; $slidePage['Functional4']='4'; $slideTags[4]='functional'; $slideTopics[4]='Document Requirement Test Parameter';
$slide[5]='Functional'; $slideName[5]='Functional (5)'; $slidePage['Functional5']='5'; $slideTags[5]='functional'; $slideTopics[5]='AccessProfile GuiFilter';
$slide[6]='Technical'; $slideName[6]='Technical'; $slidePage['Technical1']='6'; $slideTags[6]='technical gui interface ajax browser'; $slideTopics[6]='GuiGenerality';
$slide[7]='Technical'; $slideName[7]='Technical (2)'; $slidePage['Technical2']='7'; $slideTags[7]='install setup deploy'; $slideTopics[7]='Installation';
$slide[8]='Technical'; $slideName[8]='Technical (3)'; $slidePage['Technical3']='8'; $slideTags[8]='parameter'; $slideTopics[8]='Parameters1';
$slide[9]='Installation'; $slideName[9]='Installation'; $slidePage['Installation']='9'; $slideTags[9]='install setup deploy php mysql http server zip'; $slideTopics[9]='Configuration Parameters1 NewVersion Connection';
$slide[10]='Configuration'; $slideName[10]='Configuration'; $slidePage['Configuration']='10'; $slideTags[10]='install setup config parameter'; $slideTopics[10]='Installation Parameters1 NewVersion Connection';
$slide[11]='Parameters'; $slideName[11]='Parameters'; $slidePage['Parameters1']='11'; $slideTags[11]='config parameter install setup'; $slideTopics[11]='Installation Configuration NewVersion';
$slide[12]='Parameters'; $slideName[12]='Parameters (2)'; $slidePage['Parameters2']='12'; $slideTags[12]='config parameter install setup'; $slideTopics[12]='Installation Configuration NewVersion';
$slide[13]='Parameters'; $slideName[13]='Parameters (3)'; $slidePage['Parameters3']='13'; $slideTags[13]='config parameter install setup'; $slideTopics[13]='Installation Configuration NewVersion';
$slide[14]='Parameters'; $slideName[14]='Parameters (4)'; $slidePage['Parameters4']='14'; $slideTags[14]='config parameter install setup'; $slideTopics[14]='Installation Configuration NewVersion';
$slide[15]='Parameters'; $slideName[15]='Parameters (5)'; $slidePage['Parameters5']='15'; $slideTags[15]='config parameter install setup'; $slideTopics[15]='Installation Configuration NewVersion';
$slide[16]='NewVersion'; $slideName[16]='Install new version'; $slidePage['NewVersion']='16'; $slideTags[16]='install setup deploy php mysql http server zip new version release update'; $slideTopics[16]='Installation Configuration Parameters1';
$slide[17]='Connection'; $slideName[17]='Connection'; $slidePage['Connection']='17'; $slideTags[17]='connect login'; $slideTopics[17]='GuiGenerality Installation Configuration';
$slide[18]='GUI'; $slideName[18]='User interface'; $slidePage['GuiGenerality']='18'; $slideTags[18]='gui interface'; $slideTopics[18]='Themes GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[19]='GUI'; $slideName[19]='Toolbars'; $slidePage['GuiToolbar']='19'; $slideTags[19]='gui interface toolbar show hide switch help manual hyperlink logo external-shortcuts shortcuts'; $slideTopics[19]='Themes GuiGenerality GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[20]='GUI'; $slideName[20]='Menu'; $slidePage['GuiMenu']='20'; $slideTags[20]='gui interface menu project combo'; $slideTopics[20]='Themes GuiGenerality GuiToolbar GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[21]='GUI'; $slideName[21]='Quick Menu'; $slidePage['GuiQuickMenu']='21'; $slideTags[21]='gui interface menu project combo'; $slideTopics[21]='Themes GuiGenerality GuiToolbar GuiMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[22]='GUI'; $slideName[22]='List'; $slidePage['GuiList']='22'; $slideTags[22]='gui interface list column'; $slideTopics[22]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[23]='GUI'; $slideName[23]='Filter'; $slidePage['GuiFilter']='23'; $slideTags[23]='gui interface filter complex'; $slideTopics[23]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[24]='GUI'; $slideName[24]='Detail'; $slidePage['GuiDetail']='24'; $slideTags[24]='gui interface detail item save print'; $slideTopics[24]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiCombo GuiAlert GuiProject';
$slide[25]='GUI'; $slideName[25]='Combo detail'; $slidePage['GuiCombo']='25'; $slideTags[25]='gui interface detail item save print combo list'; $slideTopics[25]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail  GuiAlert GuiProject';
$slide[26]='GUI'; $slideName[26]='Alert'; $slidePage['GuiAlert']='26'; $slideTags[26]='gui interface detail item save print combo list alert info warning'; $slideTopics[26]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiProject';
$slide[27]='Themes'; $slideName[27]='Themes'; $slidePage['Themes']='27'; $slideTags[27]='theme color'; $slideTopics[27]='GuiGenerality ThemesTemplates';
$slide[28]='Themes'; $slideName[28]='Themes templates'; $slidePage['ThemesTemplates']='28'; $slideTags[28]='theme color example'; $slideTopics[28]='GuiGenerality Themes';
$slide[29]='Multilingual'; $slideName[29]='Multilingual'; $slidePage['Multilingual']='29'; $slideTags[29]='english french german translat multiling'; $slideTopics[29]='GuiGenerality Configuration Parameters1';
$slide[30]='Creation'; $slideName[30]='Creation'; $slidePage['Creation']='30'; $slideTags[30]='creation'; $slideTopics[30]='GuiGenerality Update Delete Copy';
$slide[31]='Update'; $slideName[31]='Update'; $slidePage['Update']='31'; $slideTags[31]='update'; $slideTopics[31]='GuiGenerality Creation Delete copy';
$slide[32]='Delete'; $slideName[32]='Delete'; $slidePage['Delete']='32'; $slideTags[32]='delete'; $slideTopics[32]='GuiGenerality Creation Update Copy';
$slide[33]='Copy'; $slideName[33]='Copy'; $slidePage['Copy']='33'; $slideTags[33]='copy'; $slideTopics[33]='GuiGenerality Creation Update Delete';
$slide[34]='Today'; $slideName[34]='Today'; $slidePage['Today']='34'; $slideTags[34]='today summary todo message'; $slideTopics[34]='Message Project Ticket Activity Milestone Risk Action Issue';
$slide[35]='Today'; $slideName[35]='Today parameters'; $slidePage['TodayParameters']='35'; $slideTags[35]='today summary todo message'; $slideTopics[35]='Message Project Ticket Activity Milestone Risk Action Issue Report';
$slide[36]='Project'; $slideName[36]='Project'; $slidePage['Project']='36'; $slideTags[36]='project planning sub-project'; $slideTopics[36]='ProjectFields ProjectProgress ProjectAffectation ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[37]='Project'; $slideName[37]='Project fields'; $slidePage['ProjectFields']='37'; $slideTags[37]='project planning sub-project hyperlink external-shortcuts shortcuts'; $slideTopics[37]='Project ProjectAffectation ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning Affectation Customer';
$slide[38]='Project'; $slideName[38]='Project affectations and versions'; $slidePage['ProjectAffectation']='38'; $slideTags[38]='project planning affectation version'; $slideTopics[38]='Project ProjectFields ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[39]='Project'; $slideName[39]='Project progress'; $slidePage['ProjectProgress']='39'; $slideTags[39]='project planning'; $slideTopics[39]='Project ProjectFields ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[40]='Project'; $slideName[40]='Project dependencies'; $slidePage['ProjectDependencies']='40'; $slideTags[40]='project planning'; $slideTopics[40]='Project ProjectFields ProjectProgress ProjectAffectation GuiGenerality Creation Update Delete Planning';
$slide[41]='Document'; $slideName[41]='Document'; $slidePage['Document']='41'; $slideTags[41]='document directory file'; $slideTopics[41]='DocumentFields DocumentVersions DocumentDirectory DocumentApprovers Product Project';
$slide[42]='Document'; $slideName[42]='Document fields'; $slidePage['DocumentFields']='42'; $slideTags[42]='document directory file'; $slideTopics[42]='Document DocumentVersions DocumentDirectory DocumentApprovers Product Project LinkedElements';
$slide[43]='Document'; $slideName[43]='Document versions'; $slidePage['DocumentVersions']='43'; $slideTags[43]='document directory file version'; $slideTopics[43]='Document DocumentFields DocumentDirectory DocumentApprovers Product Project';
$slide[44]='Document'; $slideName[44]='Document approvers'; $slidePage['DocumentApprovers']='44'; $slideTags[44]='document directory file version approvers approve'; $slideTopics[44]='Document DocumentFields DocumentDirectory DocumentVersion Product Project';
$slide[45]='Ticket'; $slideName[45]='Ticket'; $slidePage['Ticket']='45'; $slideTags[45]='ticket bug task track'; $slideTopics[45]='TicketFields TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[46]='Ticket'; $slideName[46]='Ticket fields'; $slidePage['TicketFields']='46'; $slideTags[46]='ticket bug task track'; $slideTopics[46]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[47]='Ticket'; $slideName[47]='Ticket fields'; $slidePage['TicketFields2']='47'; $slideTags[47]='ticket bug task track work timer'; $slideTopics[47]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[48]='TicketSimple'; $slideName[48]='Simple Ticket'; $slidePage['TicketSimple']='48'; $slideTags[48]='ticket bug task track simple'; $slideTopics[48]='TicketSimpleFields Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[49]='TicketSimple'; $slideName[49]='Simple Ticket fields'; $slidePage['TicketSimpleFields']='49'; $slideTags[49]='ticket bug task track simple'; $slideTopics[49]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[50]='TicketSimple'; $slideName[50]='Simple Ticket fields'; $slidePage['TicketSimpleFields2']='50'; $slideTags[50]='ticket bug task track simple'; $slideTopics[50]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[51]='Activity'; $slideName[51]='Activity'; $slidePage['Activity']='51'; $slideTags[51]='activity task planning'; $slideTopics[51]='ActivityFields ActivityAssignment ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[52]='Activity'; $slideName[52]='Activity fields'; $slidePage['ActivityFields']='52'; $slideTags[52]='activity task planning'; $slideTopics[52]='Activity ActivityAssignement ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[53]='Activity'; $slideName[53]='Activity assignment'; $slidePage['ActivityAssignement']='53'; $slideTags[53]='activity task planning assignment'; $slideTopics[53]='Activity ActivityFields ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[54]='Activity'; $slideName[54]='Activity progress'; $slidePage['ActivityProgress']='54'; $slideTags[54]='activity task planning progress'; $slideTopics[54]='Activity ActivityFields ActivityAssignment ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[55]='Activity'; $slideName[55]='Activity dependency'; $slidePage['ActivityDependencies']='55'; $slideTags[55]='activity task planning'; $slideTopics[55]='Activity ActivityFields ActivityAssignment ActivityProgress GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[56]='Milestone'; $slideName[56]='Milestone'; $slidePage['Milestone']='56'; $slideTags[56]='milestone flag '; $slideTopics[56]='MilestoneFields MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[57]='Milestone'; $slideName[57]='Milestone fields'; $slidePage['MilestoneFields']='57'; $slideTags[57]='milestone flag '; $slideTopics[57]='Milestone MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[58]='Milestone'; $slideName[58]='Milestone progress'; $slidePage['MilestoneProgress']='58'; $slideTags[58]='milestone flag '; $slideTopics[58]='Milestone MilestoneFields MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[59]='Milestone'; $slideName[59]='Milestone dependencies'; $slidePage['MilestoneDependencies']='59'; $slideTags[59]='milestone flag '; $slideTopics[59]='Milestone MilestoneFields MilestoneProgress GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[60]='Action'; $slideName[60]='Action'; $slidePage['Action']='60'; $slideTags[60]='risk action issue'; $slideTopics[60]='ActionFields ActionDependencies Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[61]='Action'; $slideName[61]='Action fields'; $slidePage['ActionFields']='61'; $slideTags[61]='risk action issue'; $slideTopics[61]='Action ActionDependencies Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[62]='Action'; $slideName[62]='Action dependencies'; $slidePage['ActionDependencies']='62'; $slideTags[62]='risk action issue'; $slideTopics[62]='Action ActionFields Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[63]='Imputation'; $slideName[63]='Real work allocation'; $slidePage['Imputation']='63'; $slideTags[63]='imputation work follow-up allocation'; $slideTopics[63]='Activity ActivityAssignement Planning Resource Project Affectation';
$slide[64]='Planning'; $slideName[64]='Planning'; $slidePage['Planning1']='64'; $slideTags[64]='planning work plan date calculation gantt'; $slideTopics[64]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[65]='Planning'; $slideName[65]='Planning (2)'; $slidePage['Planning2']='65'; $slideTags[65]='planning work plan date calculation gantt'; $slideTopics[65]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[66]='Planning'; $slideName[66]='Planning (3)'; $slidePage['Planning3']='66'; $slideTags[66]='planning work plan date calculation gantt'; $slideTopics[66]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[67]='Planning'; $slideName[67]='Planning (4)'; $slidePage['Planning4']='67'; $slideTags[67]='planning work plan date calculation gantt'; $slideTopics[67]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[68]='Planning'; $slideName[68]='Planning (5)'; $slidePage['Planning5']='68'; $slideTags[68]='planning work plan date calculation gantt'; $slideTopics[68]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[69]='PortfolioPlanning'; $slideName[69]='Projects portfolio'; $slidePage['PortfolioPlanning']='69'; $slideTags[69]='planning gantt portfolio'; $slideTopics[69]='Planning';
$slide[70]='ResourcePlanning'; $slideName[70]='Resource Planning'; $slidePage['ResourcePlanning']='70'; $slideTags[70]='planning work plan date calculation gantt resource'; $slideTopics[70]='ActivityAssignement ActivityProgress ActivityDependencies Planning';
$slide[71]='Report'; $slideName[71]='Report'; $slidePage['Report']='71'; $slideTags[71]='parameter report print '; $slideTopics[71]='';
$slide[72]='Requirement'; $slideName[72]='Requirement'; $slidePage['Requirement']='72'; $slideTags[72]='requirement'; $slideTopics[72]='RequirementFields TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[73]='Requirement'; $slideName[73]='Requirement fields'; $slidePage['RequirementFields']='73'; $slideTags[73]='requirement'; $slideTopics[73]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[74]='Requirement'; $slideName[74]='Requirement fields'; $slidePage['RequirementFields2']='74'; $slideTags[74]='requirement'; $slideTopics[74]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[75]='TestCase'; $slideName[75]='Test case'; $slidePage['TestCase']='75'; $slideTags[75]='test case'; $slideTopics[75]='TestCaseFields Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[76]='TestCase'; $slideName[76]='Test case fields'; $slidePage['TestCaseFields']='76'; $slideTags[76]='test case'; $slideTopics[76]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[77]='TestCase'; $slideName[77]='Test case fields'; $slidePage['TestCaseFields2']='77'; $slideTags[77]='test case'; $slideTopics[77]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[78]='TestSession'; $slideName[78]='Test session'; $slidePage['TestSession']='78'; $slideTags[78]='test session'; $slideTopics[78]='TestSessionFields Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[79]='TestSession'; $slideName[79]='Test session fields'; $slidePage['TestSessionFields']='79'; $slideTags[79]='test session'; $slideTopics[79]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[80]='TestSession'; $slideName[80]='Test session fields'; $slidePage['TestSessionFields2']='80'; $slideTags[80]='test session'; $slideTopics[80]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[81]='IndividualExpense'; $slideName[81]='Individual expense'; $slidePage['IndividualExpense']='81'; $slideTags[81]='expense cost travel '; $slideTopics[81]='IndividualExpenseFields IndividualExpenseDetails ProjectExpense';
$slide[82]='IndividualExpense'; $slideName[82]='Individual expense fields'; $slidePage['IndividualExpenseFields']='82'; $slideTags[82]='expense cost travel '; $slideTopics[82]='IndividualExpense IndividualExpenseDetails ProjectExpense';
$slide[83]='IndividualExpense'; $slideName[83]='Individual expense details'; $slidePage['IndividualExpenseDetails']='83'; $slideTags[83]='expense cost travel detail'; $slideTopics[83]='IndividualExpenseFields IndividualExpense ProjectExpense';
$slide[84]='ProjectExpense'; $slideName[84]='Project expense'; $slidePage['ProjectExpense']='84'; $slideTags[84]='expense'; $slideTopics[84]='ProjectExpenseFields IndividualExpense';
$slide[85]='ProjectExpense'; $slideName[85]='Project expense fields'; $slidePage['ProjectExpenseFields']='85'; $slideTags[85]='expense'; $slideTopics[85]='ProjectExpense IndividualExpense';
$slide[86]='Term'; $slideName[86]='Term'; $slidePage['Term']='86'; $slideTags[86]='term trigger bill fixed price'; $slideTopics[86]='TermFileds Bill';
$slide[87]='Term'; $slideName[87]='Term fields'; $slidePage['TermFields']='87'; $slideTags[87]='term trigger bill fixed price'; $slideTopics[87]='Term Bill';
$slide[88]='Bill'; $slideName[88]='Bill'; $slidePage['Bill']='88'; $slideTags[88]='bill billing'; $slideTopics[88]='Term Bill ActivityPrice BillingType BillType';
$slide[89]='Bill'; $slideName[89]='Bill fields'; $slidePage['BillFields']='89'; $slideTags[89]='bill billing'; $slideTopics[89]='Term Bill ActivityPrice BillingType BillType Recipient Contact';
$slide[90]='Bill'; $slideName[90]='Bill lines'; $slidePage['BillLines']='90'; $slideTags[90]='risk action issue opportunity'; $slideTopics[90]='Term Bill ActivityPrice BillingType BillType';
$slide[91]='ActiviyPrice'; $slideName[91]='Activity price'; $slidePage['ActiviyPrice']='91'; $slideTags[91]='risk action issue opportunity'; $slideTopics[91]='Activity ActivityType BillingType';
$slide[92]='Risk'; $slideName[92]='Risk'; $slidePage['Risk']='92'; $slideTags[92]='risk action issue'; $slideTopics[92]='RiskFields Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[93]='Risk'; $slideName[93]='Risk fields'; $slidePage['RiskFields']='93'; $slideTags[93]='risk action issue'; $slideTopics[93]='Risk Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[94]='Opportunity'; $slideName[94]='Opportunity'; $slidePage['Opportunity']='94'; $slideTags[94]='meeting workshop steering committee invitation attendees'; $slideTopics[94]='OpportunityFields Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[95]='Opportunity'; $slideName[95]='Opportunity fields'; $slidePage['OpportunityFields']='95'; $slideTags[95]='meeting workshop steering committee'; $slideTopics[95]='Opportunity Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[96]='Issue'; $slideName[96]='Issue'; $slidePage['Issue']='96'; $slideTags[96]='risk action issue'; $slideTopics[96]='IssueFields IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[97]='Issue'; $slideName[97]='Issue fields'; $slidePage['IssueFields']='97'; $slideTags[97]='risk action issue'; $slideTopics[97]='Issue IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[98]='Meeting'; $slideName[98]='Meeting'; $slidePage['Meeting']='98'; $slideTags[98]='meeting workshop steering committee invitation attendees'; $slideTopics[98]='MeetingFields MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[99]='Meeting'; $slideName[99]='Meeting fields'; $slidePage['MeetingFields']='99'; $slideTags[99]='meeting workshop steering committee'; $slideTopics[99]='Meeting MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[100]='Decision'; $slideName[100]='Decision'; $slidePage['Decision']='100'; $slideTags[100]='decision'; $slideTopics[100]='DecisionFields DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[101]='Decision'; $slideName[101]='Decision fields'; $slidePage['DecisionFields']='101'; $slideTags[101]='decision'; $slideTopics[101]='Decision DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[102]='Question'; $slideName[102]='Question'; $slidePage['Question']='102'; $slideTags[102]='question answer'; $slideTopics[102]='QuestionFields QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[103]='Question'; $slideName[103]='Question fields'; $slidePage['QuestionFields']='103'; $slideTags[103]='question answer'; $slideTopics[103]='Question QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[104]='Mail'; $slideName[104]='Emails'; $slidePage['Mail']='104'; $slideTags[104]='email mail'; $slideTopics[104]='AutomaticEmailing';
$slide[105]='Alert'; $slideName[105]='Alerts'; $slidePage['Alert']='105'; $slideTags[105]='alert warning information indicator'; $slideTopics[105]='GuiAlert IndicatorDefinition';
$slide[106]='Message'; $slideName[106]='Message'; $slidePage['Message']='106'; $slideTags[106]='message alert'; $slideTopics[106]='User Project Profile Today';
$slide[107]='Import'; $slideName[107]='Import'; $slidePage['Import']='107'; $slideTags[107]='import load'; $slideTopics[107]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[108]='Import'; $slideName[108]='Import Run'; $slidePage['ImportRun']='108'; $slideTags[108]='import load'; $slideTopics[108]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[109]='AutomaticImport'; $slideName[109]='Automatic Import'; $slidePage['AutomaticImport']='109'; $slideTags[109]='automatic automated import cron'; $slideTopics[109]='Import GlobalParameter';
$slide[110]='Affectation'; $slideName[110]='Affectation'; $slidePage['Affectation']='110'; $slideTags[110]='affectation resource contact user project'; $slideTopics[110]='GuiGenerality Resource Contact User Project';
$slide[111]='User'; $slideName[111]='User'; $slidePage['User']='111'; $slideTags[111]='contact resource user login password'; $slideTopics[111]='GuiGenerality Contact Resource UserAffectation';
$slide[112]='User'; $slideName[112]='User affectations'; $slidePage['UserAffectation']='112'; $slideTags[112]='contact resource user login password affectation'; $slideTopics[112]='GuiGenerality Contact Resource User';
$slide[113]='Resource'; $slideName[113]='Resource description'; $slidePage['Resource']='113'; $slideTags[113]='resource capacity affectation'; $slideTopics[113]='ResourceCost GuiGenerality User Contact Team Planning Affectation';
$slide[114]='Resource'; $slideName[114]='Resource function cost & affectation'; $slidePage['ResourceCost']='114'; $slideTags[114]='resource capacity affectation cost'; $slideTopics[114]='GuiGenerality User Contact Team Planning Affectation Resource';
$slide[115]='Contact'; $slideName[115]='Contact'; $slidePage['Contact']='115'; $slideTags[115]='contact customer requestor'; $slideTopics[115]='Client User GuiGenerality Creation Update Delete AutomaticEmailing ContactAffectation';
$slide[116]='Contact'; $slideName[116]='Contact affectations'; $slidePage['ContactAffectation']='116'; $slideTags[116]='contact customer requestor affectation'; $slideTopics[116]='Client User GuiGenerality Creation Update Delete AutomaticEmailing Contact';
$slide[117]='Client'; $slideName[117]='Customer'; $slidePage['Client']='117'; $slideTags[117]='client customer contact'; $slideTopics[117]='Contact Project GuiGenerality Creation Update Delete';
$slide[118]='Recipient'; $slideName[118]='Recipient'; $slidePage['Recipient']='118'; $slideTags[118]='recipient bill'; $slideTopics[118]='Bill';
$slide[119]='Team'; $slideName[119]='Team'; $slidePage['Team']='119'; $slideTags[119]='team resource affectation'; $slideTopics[119]='GuiGenerality Resource';
$slide[120]='Product'; $slideName[120]='Product'; $slidePage['Product']='120'; $slideTags[120]='product version'; $slideTopics[120]='Version Project Customer Contact';
$slide[121]='Version'; $slideName[121]='Version'; $slidePage['Version']='121'; $slideTags[121]='product version'; $slideTopics[121]='Product Project Customer Contact';
$slide[122]='Context'; $slideName[122]='Context'; $slidePage['Context']='122'; $slideTags[122]='context environment os browser'; $slideTopics[122]='Ticket TranslatableName';
$slide[123]='Calendar'; $slideName[123]='Calendar'; $slidePage['Calendar']='123'; $slideTags[123]='calendar off open closed day'; $slideTopics[123]='GuiGenerality Planning';
$slide[124]='DocumentDirectory'; $slideName[124]='Document directory'; $slidePage['DocumentDirectory']='124'; $slideTags[124]='document directory folder place'; $slideTopics[124]='Document';
$slide[125]='Role'; $slideName[125]='Function'; $slidePage['Role']='125'; $slideTags[125]='function resource cost'; $slideTopics[125]='GuiGenerality Resource';
$slide[126]='Status'; $slideName[126]='Status'; $slidePage['Status']='126'; $slideTags[126]='status workflow lifecycle'; $slideTopics[126]='Workflow Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[127]='HealthStatus'; $slideName[127]='HealthStatus'; $slidePage['HealthStatus']='127'; $slideTags[127]='health'; $slideTopics[127]='Project Today';
$slide[128]='Likelihood'; $slideName[128]='Likelihood'; $slidePage['Likelihood']='128'; $slideTags[128]='likelihood probability'; $slideTopics[128]='GuiGenerality criticality severity risk';
$slide[129]='Criticality'; $slideName[129]='Criticality'; $slidePage['Criticality']='129'; $slideTags[129]='criticality'; $slideTopics[129]='GuiGenerality risk ticket likelihood severity priority urgency';
$slide[130]='Severity'; $slideName[130]='Severity'; $slidePage['Severity']='130'; $slideTags[130]='severity'; $slideTopics[130]='GuiGenerality risk criticality likelihood';
$slide[131]='Urgency'; $slideName[131]='Urgency'; $slidePage['Urgency']='131'; $slideTags[131]='urgency priority'; $slideTopics[131]='GuiGenerality ticket priority criticality';
$slide[132]='Priority'; $slideName[132]='Priority'; $slidePage['Priority']='132'; $slideTags[132]='priority urgency'; $slideTopics[132]='GuiGenerality urgency criticality ticket';
$slide[133]='RiskLevel'; $slideName[133]='Risk level'; $slidePage['RiskLevel']='133'; $slideTags[133]='risk level'; $slideTopics[133]='GuiGenerality';
$slide[134]='Feasibility'; $slideName[134]='Feasibility'; $slidePage['Feasibility']='134'; $slideTags[134]='feasibility'; $slideTopics[134]='GuiGenerality';
$slide[135]='PredefinedNote'; $slideName[135]='Predefined note'; $slidePage['PredefinedNote']='135'; $slideTags[135]='predefined note text'; $slideTopics[135]='Notes';
$slide[136]='Workflow'; $slideName[136]='Workflow description'; $slidePage['Workflow']='136'; $slideTags[136]='workflow status'; $slideTopics[136]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[137]='Workflow'; $slideName[137]='Workflow table'; $slidePage['WorkflowTable']='137'; $slideTags[137]='workflow status'; $slideTopics[137]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[138]='StatusMail'; $slideName[138]='Mail on status change'; $slidePage['StatusMail']='138'; $slideTags[138]='mail emailing status'; $slideTopics[138]='GuiGenerality Mail Status AutomaticEmailing';
$slide[139]='TicketDelay'; $slideName[139]='Delay for tickets'; $slidePage['TicketDelay']='139'; $slideTags[139]='delay ticket'; $slideTopics[139]='GuiGenerality Ticket';
$slide[140]='IndicatorDefinition'; $slideName[140]='Indicator'; $slidePage['IndicatorDefinition']='140'; $slideTags[140]='delay indicator alert warning'; $slideTopics[140]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[141]='ProjectType'; $slideName[141]='Project type'; $slidePage['ProjectType']='141'; $slideTags[141]='project type template administrative operational billing'; $slideTopics[141]='Project Bill';
$slide[142]='TicketType'; $slideName[142]='Ticket type'; $slidePage['TicketType']='142'; $slideTags[142]='type ticket'; $slideTopics[142]='Ticket GuiGenerality';
$slide[143]='ActivityType'; $slideName[143]='Activity type'; $slidePage['ActivityType']='143'; $slideTags[143]='activity type'; $slideTopics[143]='Activity GuiGenerality';
$slide[144]='MilestoneType'; $slideName[144]='Milestone type'; $slidePage['MilestoneType']='144'; $slideTags[144]='milestone type'; $slideTopics[144]='Milestone GuiGenerality';
$slide[145]='IndividualExpenseType'; $slideName[145]='Individual expense type'; $slidePage['IndividualExpenseType']='145'; $slideTags[145]='expense type'; $slideTopics[145]='IndividualExpense GuiGenerality';
$slide[146]='ProjectExpenseType'; $slideName[146]='Project expensetype'; $slidePage['ProjectExpenseType']='146'; $slideTags[146]='expense type'; $slideTopics[146]='ProjectExpense GuiGenerality';
$slide[147]='ExpenseDetailType'; $slideName[147]='Expense detail type'; $slidePage['ExpenseDetailType']='147'; $slideTags[147]='expense type'; $slideTopics[147]='IndividualExpense ProjectExpense GuiGenerality';
$slide[148]='BillType'; $slideName[148]='Bill type'; $slidePage['BillType']='148'; $slideTags[148]='bill type'; $slideTopics[148]='Bill GuiGenerality Creation Update Delete';
$slide[149]='RiskType'; $slideName[149]='Risk type'; $slidePage['RiskType']='149'; $slideTags[149]='risk type'; $slideTopics[149]='Risk GuiGenerality Creation Update Delete';
$slide[150]='RiskType'; $slideName[150]='Opportunity type'; $slidePage['Opportunity Type']='150'; $slideTags[150]='opportunity type'; $slideTopics[150]='Opportunity GuiGenerality Creation Update Delete';
$slide[151]='ActionType'; $slideName[151]='Action type'; $slidePage['ActionType']='151'; $slideTags[151]='action type'; $slideTopics[151]='Action GuiGenerality Creation Update Delete';
$slide[152]='IssueType'; $slideName[152]='Issue type'; $slidePage['IssueType']='152'; $slideTags[152]='issue type'; $slideTopics[152]='Issue GuiGenerality Creation Update Delete';
$slide[153]='MeetingType'; $slideName[153]='Meeting type'; $slidePage['MeetingType']='153'; $slideTags[153]='meeting type'; $slideTopics[153]='Meeting GuiGenerality Creation Update Delete';
$slide[154]='DecisionType'; $slideName[154]='Decision type'; $slidePage['DecisionType']='154'; $slideTags[154]='decision type'; $slideTopics[154]='Decision GuiGenerality Creation Update Delete';
$slide[155]='QuestionType'; $slideName[155]='Question type'; $slidePage['QuestionType']='155'; $slideTags[155]='question type'; $slideTopics[155]='Question GuiGenerality Creation Update Delete';
$slide[156]='MessageType'; $slideName[156]='Message type'; $slidePage['MessageType']='156'; $slideTags[156]='message type'; $slideTopics[156]='Message GuiGenerality Creation Update Delete';
$slide[157]='DocumentType'; $slideName[157]='Document type'; $slidePage['DocumentType']='157'; $slideTags[157]='document type'; $slideTopics[157]='Document GuiGenerality Creation Update Delete';
$slide[158]='ContextType'; $slideName[158]='Context type'; $slidePage['ContextType']='158'; $slideTags[158]='context type'; $slideTopics[158]='Context GuiGenerality Creation Update Delete';
$slide[159]='RequirementType'; $slideName[159]='Requirement type'; $slidePage['RequirementType']='159'; $slideTags[159]='requirement type'; $slideTopics[159]='Requirement GuiGenerality Creation Update Delete';
$slide[160]='TestCaseType'; $slideName[160]='Test case type'; $slidePage['TestCaseType']='160'; $slideTags[160]='test case type'; $slideTopics[160]='TestCase GuiGenerality Creation Update Delete';
$slide[161]='TestSessionType'; $slideName[161]='Test session type'; $slidePage['TestSessionType']='161'; $slideTags[161]='test session type'; $slideTopics[161]='TestSession GuiGenerality Creation Update Delete';
$slide[162]='Profile'; $slideName[162]='Profile'; $slidePage['Profile']='162'; $slideTags[162]='connection profile'; $slideTopics[162]='TranslatableName User';
$slide[163]='AccessProfile'; $slideName[163]='Access mode'; $slidePage['AccessProfile']='163'; $slideTags[163]='access mode read write update delete'; $slideTopics[163]='TranslatableName User Resource Profile';
$slide[164]='Habilitation'; $slideName[164]='Access to forms'; $slidePage['Habilitation']='164'; $slideTags[164]='ticket bug task track habilitation'; $slideTopics[164]='Profile AccessRight';
$slide[165]='HabilitationReport'; $slideName[165]='Access to reports'; $slidePage['HabilitationReport']='165'; $slideTags[165]='access report rights'; $slideTopics[165]='Profile';
$slide[166]='AccessRight'; $slideName[166]='Access mode to data'; $slidePage['AccessMode']='166'; $slideTags[166]='access screen form rights'; $slideTopics[166]='Profile Habilitation';
$slide[167]='HabilitationOther'; $slideName[167]='Specific access mode'; $slidePage['HabilitationOther']='167'; $slideTags[167]='access specific'; $slideTopics[167]='User Profile GuiCombo';
$slide[168]='HabilitationOther'; $slideName[168]='Specific access mode'; $slidePage['HabilitationOther2']='168'; $slideTags[168]='access specific'; $slideTopics[168]='User Profile GuiCombo';
$slide[169]='Administration'; $slideName[169]='Global parameters'; $slidePage['Administration']='169'; $slideTags[169]='administration cron maintenance purge'; $slideTopics[169]='';
$slide[170]='Audit'; $slideName[170]='Audit connections'; $slidePage['Audit']='170'; $slideTags[170]='connections who_is_online'; $slideTopics[170]='';
$slide[171]='GlobalParameter'; $slideName[171]='Global parameters'; $slidePage['GlobalParameter']='171'; $slideTags[171]='parameters ldap reference format'; $slideTopics[171]='';
$slide[172]='GlobalParameter'; $slideName[172]='Global parameters'; $slidePage['GlobalParameter2']='172'; $slideTags[172]='parameters ldap billing format'; $slideTopics[172]='';
$slide[173]='GlobalParameter'; $slideName[173]='Global parameters'; $slidePage['GlobalParameter3']='173'; $slideTags[173]='parameters ldap billing format'; $slideTopics[173]='';
$slide[174]='GlobalParameter'; $slideName[174]='Global parameters'; $slidePage['GlobalParameter4']='174'; $slideTags[174]='parameters ldap billing format'; $slideTopics[174]='';
$slide[175]='GlobalParameter'; $slideName[175]='Global parameters'; $slidePage['GlobalParameter5']='175'; $slideTags[175]='parameters ldap billing format'; $slideTopics[175]='';
$slide[176]='UserParameter'; $slideName[176]='User parameters'; $slidePage['UserParameter']='176'; $slideTags[176]='parameters'; $slideTopics[176]='';
$slide[177]='TranslatableName'; $slideName[177]='Translatable name'; $slidePage['translatableName']='177'; $slideTags[177]='translatable translation name profile'; $slideTopics[177]='AccessProfile ConnectionProfile';
$slide[178]='AutomaticEmailing'; $slideName[178]='Automatic emailing'; $slidePage['AutomaticEmailing']='178'; $slideTags[178]=''; $slideTopics[178]='Mail Status GuiGenerality Creation Update Delete';
$slide[179]='LinkedElements'; $slideName[179]='Linked elements'; $slidePage['LinkedElements']='179'; $slideTags[179]='link linked'; $slideTopics[179]='';
$slide[180]='Attachments'; $slideName[180]='Attachments'; $slidePage['Attachments']='180'; $slideTags[180]='attach file link privacy'; $slideTopics[180]='Ticket Activity Milestone Risk Issue Meeting Decision Question Parameters4 UserParameters';
$slide[181]='Notes'; $slideName[181]='Notes'; $slidePage['Notes']='181'; $slideTags[181]='note comment privacy predefined'; $slideTopics[181]='Ticket Activity Milestone Risk Action Issue Meeting Decision Question UserParameters';
$slide[182]='ChangeHistory'; $slideName[182]='Change history'; $slidePage['ChangeHistory']='182'; $slideTags[182]='change history track update'; $slideTopics[182]='UserParameters';
$slide[183]='Backup'; $slideName[183]='Backup / Restore'; $slidePage['Backup']='183'; $slideTags[183]='backup restore'; $slideTopics[183]='';
$slide[184]='Shortcuts'; $slideName[184]='Shortcuts'; $slidePage['Shortcuts']='184'; $slideTags[184]='shortcut key'; $slideTopics[184]='';
$slide[185]='LastWords'; $slideName[185]='Last words'; $slidePage['LastWords']='185'; $slideTags[185]='murphy hofstader history version'; $slideTopics[185]='';

if (! isset($includeManual)) {
  foreach ($slide as $id=>$name) {
    echo 'slide[' . $id . ']=' . $name . '<br/>';
  }
}

$prec='';
foreach ($slide as $id=>$name) {
  if (substr($name,0,2)=='X ') {
    unset($slide[$id]);
    unset($slideName[$id]);
    unset($slidePage[$id]);
    unset($slideTags[$id]);
    unset($slideTopics[$id]);
  } else {
    if ($name!=$prec) {
      $section[$id]=$name;
      $sectionName[$name]=$slideName[$id];
      $prec=$name;
    }
  }
}
$tags=array();
foreach ($slideTags as $id=>$name) {
 $split=explode(" ",$name);
 foreach ($split as $tag) {
   if (trim($tag) and !array_key_exists($tag, $tags)) {
     $tags[$tag]=array();
   }
   $tags[$tag][]=$id;
 }
}
ksort($tags);