<?php
$section=array();
$sectionName=array();
$topics=array();
$tags=array();
$page=array();
$slideRoot='img';
$slideExt='.png';

// Copy and paste
$slide[0]='Welcome '; $slideName[0]='Welcome'; $slidePage['Welcome']='0'; $slideTags[0]='welcome home'; $slideTopics[0]='';
$slide[1]='Functional'; $slideName[1]='Functional '; $slidePage['Functional1']='1'; $slideTags[1]='functional'; $slideTopics[1]='Ticket Activity Milestone Action Planning Workload Cost Report';
$slide[2]='Functional'; $slideName[2]='Functional (2)'; $slidePage['Functional2']='2'; $slideTags[2]='functional'; $slideTopics[2]='Expense Bill Risk Action Issue Meeting Decision Question Message Import ';
$slide[3]='Functional'; $slideName[3]='Functional (3)'; $slidePage['Functional3']='3'; $slideTags[3]='functional'; $slideTopics[3]='Client User Resource AccessRight Calendar';
$slide[4]='Functional'; $slideName[4]='Functional (4)'; $slidePage['Functional4']='4'; $slideTags[4]='functional'; $slideTopics[4]='Document Requirement Test Parameter';
$slide[5]='Functional'; $slideName[5]='Functional (5)'; $slidePage['Functional5']='5'; $slideTags[5]='functional'; $slideTopics[5]='AccessProfile GuiFilter';
$slide[6]='Technical'; $slideName[6]='Technical'; $slidePage['Technical1']='6'; $slideTags[6]='technical gui interface ajax browser'; $slideTopics[6]='GuiGenerality';
$slide[7]='Technical'; $slideName[7]='Technical (2)'; $slidePage['Technical2']='7'; $slideTags[7]='install setup deploy'; $slideTopics[7]='Installation';
$slide[8]='Technical'; $slideName[8]='Technical (3)'; $slidePage['Technical3']='8'; $slideTags[8]='parameter'; $slideTopics[8]='Parameters1';
$slide[9]='Installation'; $slideName[9]='Installation'; $slidePage['Installation']='9'; $slideTags[9]='install setup deploy php mysql http server zip'; $slideTopics[9]='Configuration Parameters1 NewVersion Connection';
$slide[10]='Configuration'; $slideName[10]='Configuration'; $slidePage['Configuration']='10'; $slideTags[10]='install setup config parameter'; $slideTopics[10]='Installation Parameters1 NewVersion Connection';
$slide[11]='Parameters'; $slideName[11]='Parameters'; $slidePage['Parameters1']='11'; $slideTags[11]='config parameter install setup'; $slideTopics[11]='Installation Configuration NewVersion';
$slide[12]='Parameters'; $slideName[12]='Parameters (2)'; $slidePage['Parameters2']='12'; $slideTags[12]='config parameter install setup'; $slideTopics[12]='Installation Configuration NewVersion';
$slide[13]='Parameters'; $slideName[13]='Parameters (3)'; $slidePage['Parameters3']='13'; $slideTags[13]='config parameter install setup'; $slideTopics[13]='Installation Configuration NewVersion';
$slide[14]='Parameters'; $slideName[14]='Parameters (4)'; $slidePage['Parameters4']='14'; $slideTags[14]='config parameter install setup'; $slideTopics[14]='Installation Configuration NewVersion';
$slide[15]='Parameters'; $slideName[15]='Parameters (5)'; $slidePage['Parameters5']='15'; $slideTags[15]='config parameter install setup'; $slideTopics[15]='Installation Configuration NewVersion';
$slide[16]='NewVersion'; $slideName[16]='Install new version'; $slidePage['NewVersion']='16'; $slideTags[16]='install setup deploy php mysql http server zip new version release update'; $slideTopics[16]='Installation Configuration Parameters1';
$slide[17]='Connection'; $slideName[17]='Connection'; $slidePage['Connection']='17'; $slideTags[17]='connect login'; $slideTopics[17]='GuiGenerality Installation Configuration';
$slide[18]='GUI'; $slideName[18]='User interface'; $slidePage['GuiGenerality']='18'; $slideTags[18]='gui interface'; $slideTopics[18]='Themes GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[19]='GUI'; $slideName[19]='Toolbars'; $slidePage['GuiToolbar']='19'; $slideTags[19]='gui interface toolbar show hide switch help manual hyperlink logo external-shortcuts shortcuts'; $slideTopics[19]='Themes GuiGenerality GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[20]='GUI'; $slideName[20]='Menu'; $slidePage['GuiMenu']='20'; $slideTags[20]='gui interface menu project combo'; $slideTopics[20]='Themes GuiGenerality GuiToolbar GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[21]='GUI'; $slideName[21]='Quick Menu'; $slidePage['GuiQuickMenu']='21'; $slideTags[21]='gui interface menu project combo'; $slideTopics[21]='Themes GuiGenerality GuiToolbar GuiMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[22]='GUI'; $slideName[22]='List'; $slidePage['GuiList']='22'; $slideTags[22]='gui interface list column'; $slideTopics[22]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[23]='GUI'; $slideName[23]='Filter'; $slidePage['GuiFilter']='23'; $slideTags[23]='gui interface filter complex'; $slideTopics[23]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[24]='GUI'; $slideName[24]='ListParameter'; $slidePage['GuiListParameters']='24'; $slideTags[24]='gui interface list order selection width'; $slideTopics[24]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[25]='GUI'; $slideName[25]='Detail'; $slidePage['GuiDetail']='25'; $slideTags[25]='gui interface detail item save print'; $slideTopics[25]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiCombo GuiAlert GuiProject';
$slide[26]='GUI'; $slideName[26]='Combo detail'; $slidePage['GuiCombo']='26'; $slideTags[26]='gui interface detail item save print combo list'; $slideTopics[26]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail  GuiAlert GuiProject';
$slide[27]='GUI'; $slideName[27]='Alert'; $slidePage['GuiAlert']='27'; $slideTags[27]='gui interface detail item save print combo list alert info warning'; $slideTopics[27]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiProject';
$slide[28]='Themes'; $slideName[28]='Themes'; $slidePage['Themes']='28'; $slideTags[28]='theme color'; $slideTopics[28]='GuiGenerality ThemesTemplates';
$slide[29]='Themes'; $slideName[29]='Themes templates'; $slidePage['ThemesTemplates']='29'; $slideTags[29]='theme color example'; $slideTopics[29]='GuiGenerality Themes';
$slide[30]='Multilingual'; $slideName[30]='Multilingual'; $slidePage['Multilingual']='30'; $slideTags[30]='english french german translat multiling'; $slideTopics[30]='GuiGenerality Configuration Parameters1';
$slide[31]='Creation'; $slideName[31]='Creation'; $slidePage['Creation']='31'; $slideTags[31]='creation'; $slideTopics[31]='GuiGenerality Update Delete Copy';
$slide[32]='Update'; $slideName[32]='Update'; $slidePage['Update']='32'; $slideTags[32]='update'; $slideTopics[32]='GuiGenerality Creation Delete copy';
$slide[33]='Delete'; $slideName[33]='Delete'; $slidePage['Delete']='33'; $slideTags[33]='delete'; $slideTopics[33]='GuiGenerality Creation Update Copy';
$slide[34]='Copy'; $slideName[34]='Copy'; $slidePage['Copy']='34'; $slideTags[34]='copy'; $slideTopics[34]='GuiGenerality Creation Update Delete';
$slide[35]='SendMail'; $slideName[35]='Send mail'; $slidePage['SendMail']='35'; $slideTags[35]='mail email receivers'; $slideTopics[35]='GuiGenerality Mail AutomaticEmailing StatusMail IndicatorDefinition';
$slide[36]='MultipleUpdate'; $slideName[36]='Multiple Update'; $slidePage['MultipleUpdate']='36'; $slideTags[36]='multiple update several grouped'; $slideTopics[36]='GuiGenerality Update';
$slide[37]='Checklist'; $slideName[37]='Checklist'; $slidePage['Checklist']='37'; $slideTags[37]='checklist quality'; $slideTopics[37]='ChecklistDefinition';
$slide[38]='Export'; $slideName[38]='Export'; $slidePage['Export']='38'; $slideTags[38]='export csv'; $slideTopics[38]='Import';
$slide[39]='Today'; $slideName[39]='Today'; $slidePage['Today']='39'; $slideTags[39]='today summary todo message'; $slideTopics[39]='Message Project Ticket Activity Milestone Risk Action Issue';
$slide[40]='Today'; $slideName[40]='Today parameters'; $slidePage['TodayParameters']='40'; $slideTags[40]='today summary todo message'; $slideTopics[40]='Message Project Ticket Activity Milestone Risk Action Issue Report';
$slide[41]='Project'; $slideName[41]='Project'; $slidePage['Project']='41'; $slideTags[41]='project planning sub-project'; $slideTopics[41]='ProjectFields ProjectProgress ProjectAffectation ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[42]='Project'; $slideName[42]='Project fields'; $slidePage['ProjectFields']='42'; $slideTags[42]='project planning sub-project hyperlink external-shortcuts shortcuts'; $slideTopics[42]='Project ProjectAffectation ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning Affectation Customer';
$slide[43]='Project'; $slideName[43]='Project affectations and versions'; $slidePage['ProjectAffectation']='43'; $slideTags[43]='project planning affectation version'; $slideTopics[43]='Project ProjectFields ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[44]='Project'; $slideName[44]='Project progress'; $slidePage['ProjectProgress']='44'; $slideTags[44]='project planning'; $slideTopics[44]='Project ProjectFields ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[45]='Project'; $slideName[45]='Project dependencies'; $slidePage['ProjectDependencies']='45'; $slideTags[45]='project planning'; $slideTopics[45]='Project ProjectFields ProjectProgress ProjectAffectation GuiGenerality Creation Update Delete Planning';
$slide[46]='Document'; $slideName[46]='Document'; $slidePage['Document']='46'; $slideTags[46]='document directory file'; $slideTopics[46]='DocumentFields DocumentVersions DocumentDirectory DocumentApprovers Product Project';
$slide[47]='Document'; $slideName[47]='Document fields'; $slidePage['DocumentFields']='47'; $slideTags[47]='document directory file'; $slideTopics[47]='Document DocumentVersions DocumentDirectory DocumentApprovers Product Project LinkedElements';
$slide[48]='Document'; $slideName[48]='Document versions'; $slidePage['DocumentVersions']='48'; $slideTags[48]='document directory file version'; $slideTopics[48]='Document DocumentFields DocumentDirectory DocumentApprovers Product Project';
$slide[49]='Document'; $slideName[49]='Document approvers'; $slidePage['DocumentApprovers']='49'; $slideTags[49]='document directory file version approvers approve'; $slideTopics[49]='Document DocumentFields DocumentDirectory DocumentVersion Product Project';
$slide[50]='Ticket'; $slideName[50]='Ticket'; $slidePage['Ticket']='50'; $slideTags[50]='ticket bug task track'; $slideTopics[50]='TicketFields TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[51]='Ticket'; $slideName[51]='Ticket fields'; $slidePage['TicketFields']='51'; $slideTags[51]='ticket bug task track'; $slideTopics[51]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[52]='Ticket'; $slideName[52]='Ticket fields'; $slidePage['TicketFields2']='52'; $slideTags[52]='ticket bug task track work timer'; $slideTopics[52]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[53]='TicketSimple'; $slideName[53]='Simple Ticket'; $slidePage['TicketSimple']='53'; $slideTags[53]='ticket bug task track simple'; $slideTopics[53]='TicketSimpleFields Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[54]='TicketSimple'; $slideName[54]='Simple Ticket fields'; $slidePage['TicketSimpleFields']='54'; $slideTags[54]='ticket bug task track simple'; $slideTopics[54]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[55]='TicketSimple'; $slideName[55]='Simple Ticket fields'; $slidePage['TicketSimpleFields2']='55'; $slideTags[55]='ticket bug task track simple'; $slideTopics[55]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[56]='Activity'; $slideName[56]='Activity'; $slidePage['Activity']='56'; $slideTags[56]='activity task planning'; $slideTopics[56]='ActivityFields ActivityAssignment ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[57]='Activity'; $slideName[57]='Activity fields'; $slidePage['ActivityFields']='57'; $slideTags[57]='activity task planning'; $slideTopics[57]='Activity ActivityAssignement ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[58]='Activity'; $slideName[58]='Activity assignment'; $slidePage['ActivityAssignement']='58'; $slideTags[58]='activity task planning assignment'; $slideTopics[58]='Activity ActivityFields ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[59]='Activity'; $slideName[59]='Activity progress'; $slidePage['ActivityProgress']='59'; $slideTags[59]='activity task planning progress'; $slideTopics[59]='Activity ActivityFields ActivityAssignment ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[60]='Activity'; $slideName[60]='Activity dependency'; $slidePage['ActivityDependencies']='60'; $slideTags[60]='activity task planning'; $slideTopics[60]='Activity ActivityFields ActivityAssignment ActivityProgress GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[61]='Milestone'; $slideName[61]='Milestone'; $slidePage['Milestone']='61'; $slideTags[61]='milestone flag '; $slideTopics[61]='MilestoneFields MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[62]='Milestone'; $slideName[62]='Milestone fields'; $slidePage['MilestoneFields']='62'; $slideTags[62]='milestone flag '; $slideTopics[62]='Milestone MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[63]='Milestone'; $slideName[63]='Milestone progress'; $slidePage['MilestoneProgress']='63'; $slideTags[63]='milestone flag '; $slideTopics[63]='Milestone MilestoneFields MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[64]='Milestone'; $slideName[64]='Milestone dependencies'; $slidePage['MilestoneDependencies']='64'; $slideTags[64]='milestone flag '; $slideTopics[64]='Milestone MilestoneFields MilestoneProgress GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[65]='Action'; $slideName[65]='Action'; $slidePage['Action']='65'; $slideTags[65]='risk action issue'; $slideTopics[65]='ActionFields Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[66]='Action'; $slideName[66]='Action fields'; $slidePage['ActionFields']='66'; $slideTags[66]='risk action issue'; $slideTopics[66]='Action Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[67]='Imputation'; $slideName[67]='Real work allocation'; $slidePage['Imputation']='67'; $slideTags[67]='imputation work follow-up allocation'; $slideTopics[67]='Activity ActivityAssignement Planning Resource Project Affectation';
$slide[68]='Planning'; $slideName[68]='Planning'; $slidePage['Planning1']='68'; $slideTags[68]='planning work plan date calculation gantt'; $slideTopics[68]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[69]='Planning'; $slideName[69]='Planning (2)'; $slidePage['Planning2']='69'; $slideTags[69]='planning work plan date calculation gantt'; $slideTopics[69]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[70]='Planning'; $slideName[70]='Planning (3)'; $slidePage['Planning3']='70'; $slideTags[70]='planning work plan date calculation gantt'; $slideTopics[70]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[71]='Planning'; $slideName[71]='Planning (4)'; $slidePage['Planning4']='71'; $slideTags[71]='planning work plan date calculation gantt'; $slideTopics[71]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[72]='Planning'; $slideName[72]='Planning (5)'; $slidePage['Planning5']='72'; $slideTags[72]='planning work plan date calculation gantt'; $slideTopics[72]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[73]='PortfolioPlanning'; $slideName[73]='Projects portfolio'; $slidePage['PortfolioPlanning']='73'; $slideTags[73]='planning gantt portfolio'; $slideTopics[73]='Planning';
$slide[74]='ResourcePlanning'; $slideName[74]='Resource Planning'; $slidePage['ResourcePlanning']='74'; $slideTags[74]='planning work plan date calculation gantt resource'; $slideTopics[74]='ActivityAssignement ActivityProgress ActivityDependencies Planning';
$slide[75]='Report'; $slideName[75]='Report'; $slidePage['Report']='75'; $slideTags[75]='parameter report print '; $slideTopics[75]='';
$slide[76]='Requirement'; $slideName[76]='Requirement'; $slidePage['Requirement']='76'; $slideTags[76]='requirement'; $slideTopics[76]='RequirementFields TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[77]='Requirement'; $slideName[77]='Requirement fields'; $slidePage['RequirementFields']='77'; $slideTags[77]='requirement'; $slideTopics[77]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[78]='Requirement'; $slideName[78]='Requirement fields'; $slidePage['RequirementFields2']='78'; $slideTags[78]='requirement'; $slideTopics[78]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[79]='TestCase'; $slideName[79]='Test case'; $slidePage['TestCase']='79'; $slideTags[79]='test case'; $slideTopics[79]='TestCaseFields Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[80]='TestCase'; $slideName[80]='Test case fields'; $slidePage['TestCaseFields']='80'; $slideTags[80]='test case'; $slideTopics[80]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[81]='TestCase'; $slideName[81]='Test case fields'; $slidePage['TestCaseFields2']='81'; $slideTags[81]='test case'; $slideTopics[81]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[82]='TestSession'; $slideName[82]='Test session'; $slidePage['TestSession']='82'; $slideTags[82]='test session'; $slideTopics[82]='TestSessionFields Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[83]='TestSession'; $slideName[83]='Test session fields'; $slidePage['TestSessionFields']='83'; $slideTags[83]='test session'; $slideTopics[83]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[84]='TestSession'; $slideName[84]='Test session fields'; $slidePage['TestSessionFields2']='84'; $slideTags[84]='test session'; $slideTopics[84]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[85]='Quotation'; $slideName[85]='Quotation'; $slidePage['Quotation']='85'; $slideTags[85]='quotation proposal estimate'; $slideTopics[85]='Order Creation Update Delete';
$slide[86]='Quotation'; $slideName[86]='Quotation fields'; $slidePage['QuotationFields']='86'; $slideTags[86]='quotation proposal estimate'; $slideTopics[86]='Order Creation Update Delete';
$slide[87]='Command'; $slideName[87]='Order'; $slidePage['Command']='87'; $slideTags[87]='order bill command'; $slideTopics[87]='Activity Quotation';
$slide[88]='Command'; $slideName[88]='Order fields'; $slidePage['CommandFields']='88'; $slideTags[88]='order bill command'; $slideTopics[88]='Activity Quotation';
$slide[89]='IndividualExpense'; $slideName[89]='Individual expense'; $slidePage['IndividualExpense']='89'; $slideTags[89]='expense cost travel '; $slideTopics[89]='IndividualExpenseFields IndividualExpenseDetails ProjectExpense';
$slide[90]='IndividualExpense'; $slideName[90]='Individual expense fields'; $slidePage['IndividualExpenseFields']='90'; $slideTags[90]='expense cost travel '; $slideTopics[90]='IndividualExpense IndividualExpenseDetails ProjectExpense';
$slide[91]='IndividualExpense'; $slideName[91]='Individual expense details'; $slidePage['IndividualExpenseDetails']='91'; $slideTags[91]='expense cost travel detail'; $slideTopics[91]='IndividualExpenseFields IndividualExpense ProjectExpense';
$slide[92]='ProjectExpense'; $slideName[92]='Project expense'; $slidePage['ProjectExpense']='92'; $slideTags[92]='expense'; $slideTopics[92]='ProjectExpenseFields IndividualExpense';
$slide[93]='ProjectExpense'; $slideName[93]='Project expense fields'; $slidePage['ProjectExpenseFields']='93'; $slideTags[93]='expense'; $slideTopics[93]='ProjectExpense IndividualExpense';
$slide[94]='Term'; $slideName[94]='Term'; $slidePage['Term']='94'; $slideTags[94]='term trigger bill fixed price'; $slideTopics[94]='TermFileds Bill';
$slide[95]='Term'; $slideName[95]='Term fields'; $slidePage['TermFields']='95'; $slideTags[95]='term trigger bill fixed price'; $slideTopics[95]='Term Bill';
$slide[96]='Bill'; $slideName[96]='Bill'; $slidePage['Bill']='96'; $slideTags[96]='bill billing'; $slideTopics[96]='Term Bill ActivityPrice BillingType BillType';
$slide[97]='Bill'; $slideName[97]='Bill fields'; $slidePage['BillFields']='97'; $slideTags[97]='bill billing'; $slideTopics[97]='Term Bill ActivityPrice BillingType BillType Recipient Contact';
$slide[98]='Bill'; $slideName[98]='Bill lines'; $slidePage['BillLines']='98'; $slideTags[98]='bill billing'; $slideTopics[98]='Term Bill ActivityPrice BillingType BillType';
$slide[99]='ActivityPrice'; $slideName[99]='Activity price'; $slidePage['ActivityPrice']='99'; $slideTags[99]='activity price bill billing'; $slideTopics[99]='Activity ActivityType BillingType';
$slide[100]='Risk'; $slideName[100]='Risk'; $slidePage['Risk']='100'; $slideTags[100]='risk action issue opportunity'; $slideTopics[100]='RiskFields Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[101]='Risk'; $slideName[101]='Risk fields'; $slidePage['RiskFields']='101'; $slideTags[101]='risk action issue opportunity'; $slideTopics[101]='Risk Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[102]='Opportunity'; $slideName[102]='Opportunity'; $slidePage['Opportunity']='102'; $slideTags[102]='opportunity risk action issue'; $slideTopics[102]='OpportunityFields Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[103]='Opportunity'; $slideName[103]='Opportunity fields'; $slidePage['OpportunityFields']='103'; $slideTags[103]='opportunity risk action issue'; $slideTopics[103]='Opportunity Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[104]='Issue'; $slideName[104]='Issue'; $slidePage['Issue']='104'; $slideTags[104]='risk action issue'; $slideTopics[104]='IssueFields IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[105]='Issue'; $slideName[105]='Issue fields'; $slidePage['IssueFields']='105'; $slideTags[105]='risk action issue'; $slideTopics[105]='Issue IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[106]='Meeting'; $slideName[106]='Meeting'; $slidePage['Meeting']='106'; $slideTags[106]='meeting workshop steering committee invitation attendees'; $slideTopics[106]='MeetingFields MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[107]='Meeting'; $slideName[107]='Meeting fields'; $slidePage['MeetingFields']='107'; $slideTags[107]='meeting workshop steering committee'; $slideTopics[107]='Meeting MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[108]='PeriodicMeeting'; $slideName[108]='Periodic meeting'; $slidePage['PeriodicMeeting']='108'; $slideTags[108]='meeting workshop steering committee invitation attendees periodic'; $slideTopics[108]='PeriodicMeetingFields Meeting MeetingType';
$slide[109]='PeriodicMeeting'; $slideName[109]='Periodic meeting fields'; $slidePage['PeriodicMeetingFields']='109'; $slideTags[109]='meeting workshop steering committee periodic'; $slideTopics[109]='PeriodicMeeting Meeting MeetingType';
$slide[110]='Decision'; $slideName[110]='Decision'; $slidePage['Decision']='110'; $slideTags[110]='decision'; $slideTopics[110]='DecisionFields DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[111]='Decision'; $slideName[111]='Decision fields'; $slidePage['DecisionFields']='111'; $slideTags[111]='decision'; $slideTopics[111]='Decision DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[112]='Question'; $slideName[112]='Question'; $slidePage['Question']='112'; $slideTags[112]='question answer'; $slideTopics[112]='QuestionFields QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[113]='Question'; $slideName[113]='Question fields'; $slidePage['QuestionFields']='113'; $slideTags[113]='question answer'; $slideTopics[113]='Question QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[114]='Mail'; $slideName[114]='Emails'; $slidePage['Mail']='114'; $slideTags[114]='email mail'; $slideTopics[114]='AutomaticEmailing SendMail';
$slide[115]='Alert'; $slideName[115]='Alerts'; $slidePage['Alert']='115'; $slideTags[115]='alert warning information indicator'; $slideTopics[115]='GuiAlert IndicatorDefinition';
$slide[116]='Message'; $slideName[116]='Message'; $slidePage['Message']='116'; $slideTags[116]='message alert'; $slideTopics[116]='User Project Profile Today';
$slide[117]='Import'; $slideName[117]='Import'; $slidePage['Import']='117'; $slideTags[117]='import load csv xlsx'; $slideTopics[117]='AutomaticImport Export';
$slide[118]='Import'; $slideName[118]='Import Run'; $slidePage['ImportRun']='118'; $slideTags[118]='import load'; $slideTopics[118]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[119]='AutomaticImport'; $slideName[119]='Automatic Import'; $slidePage['AutomaticImport']='119'; $slideTags[119]='automatic automated import cron'; $slideTopics[119]='Import GlobalParameter';
$slide[120]='Affectation'; $slideName[120]='Affectation'; $slidePage['Affectation']='120'; $slideTags[120]='affectation resource contact user project'; $slideTopics[120]='GuiGenerality Resource Contact User Project';
$slide[121]='User'; $slideName[121]='User'; $slidePage['User']='121'; $slideTags[121]='contact resource user login password'; $slideTopics[121]='GuiGenerality Contact Resource UserAffectation';
$slide[122]='User'; $slideName[122]='User affectations'; $slidePage['UserAffectation']='122'; $slideTags[122]='contact resource user login password affectation'; $slideTopics[122]='GuiGenerality Contact Resource User';
$slide[123]='Resource'; $slideName[123]='Resource description'; $slidePage['Resource']='123'; $slideTags[123]='resource capacity affectation'; $slideTopics[123]='ResourceCost GuiGenerality User Contact Team Planning Affectation';
$slide[124]='Resource'; $slideName[124]='Resource function cost & affectation'; $slidePage['ResourceCost']='124'; $slideTags[124]='resource capacity affectation cost'; $slideTopics[124]='GuiGenerality User Contact Team Planning Affectation Resource';
$slide[125]='Contact'; $slideName[125]='Contact'; $slidePage['Contact']='125'; $slideTags[125]='contact customer requestor'; $slideTopics[125]='Client User GuiGenerality Creation Update Delete AutomaticEmailing ContactAffectation';
$slide[126]='Contact'; $slideName[126]='Contact affectations'; $slidePage['ContactAffectation']='126'; $slideTags[126]='contact customer requestor affectation'; $slideTopics[126]='Client User GuiGenerality Creation Update Delete AutomaticEmailing Contact';
$slide[127]='Client'; $slideName[127]='Customer'; $slidePage['Client']='127'; $slideTags[127]='client customer contact'; $slideTopics[127]='Contact Project GuiGenerality Creation Update Delete';
$slide[128]='Recipient'; $slideName[128]='Recipient'; $slidePage['Recipient']='128'; $slideTags[128]='recipient bill'; $slideTopics[128]='Bill';
$slide[129]='Team'; $slideName[129]='Team'; $slidePage['Team']='129'; $slideTags[129]='team resource affectation'; $slideTopics[129]='GuiGenerality Resource';
$slide[130]='Product'; $slideName[130]='Product'; $slidePage['Product']='130'; $slideTags[130]='product version'; $slideTopics[130]='Version Project Customer Contact';
$slide[131]='Version'; $slideName[131]='Version'; $slidePage['Version']='131'; $slideTags[131]='product version'; $slideTopics[131]='Product Project Customer Contact';
$slide[132]='Context'; $slideName[132]='Context'; $slidePage['Context']='132'; $slideTags[132]='context environment os browser'; $slideTopics[132]='Ticket TranslatableName';
$slide[133]='Calendar'; $slideName[133]='Calendar'; $slidePage['Calendar']='133'; $slideTags[133]='calendar off open closed day'; $slideTopics[133]='GuiGenerality Planning';
$slide[134]='Calendar'; $slideName[134]='Calendar description'; $slidePage['CalendarDescription']='134'; $slideTags[134]='calendar off open closed day'; $slideTopics[134]='GuiGenerality Planning';
$slide[135]='DocumentDirectory'; $slideName[135]='Document directory'; $slidePage['DocumentDirectory']='135'; $slideTags[135]='document directory folder place'; $slideTopics[135]='Document';
$slide[136]='Role'; $slideName[136]='Function'; $slidePage['Role']='136'; $slideTags[136]='function resource cost'; $slideTopics[136]='GuiGenerality Resource';
$slide[137]='Status'; $slideName[137]='Status'; $slidePage['Status']='137'; $slideTags[137]='status workflow lifecycle'; $slideTopics[137]='Workflow Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[138]='Quality'; $slideName[138]='Quality level'; $slidePage['Quality']='138'; $slideTags[138]='quality'; $slideTopics[138]='Project Today';
$slide[139]='HealthStatus'; $slideName[139]='Health Status'; $slidePage['HealthStatus']='139'; $slideTags[139]='health'; $slideTopics[139]='Project Today';
$slide[140]='OverallProgress'; $slideName[140]='Overall Progress'; $slidePage['OverallProgress']='140'; $slideTags[140]='progress'; $slideTopics[140]='Project Today';
$slide[141]='Trend'; $slideName[141]='Trend'; $slidePage['Trend']='141'; $slideTags[141]='trend'; $slideTopics[141]='Project Today';
$slide[142]='Likelihood'; $slideName[142]='Likelihood'; $slidePage['Likelihood']='142'; $slideTags[142]='likelihood probability'; $slideTopics[142]='GuiGenerality criticality severity risk';
$slide[143]='Criticality'; $slideName[143]='Criticality'; $slidePage['Criticality']='143'; $slideTags[143]='criticality'; $slideTopics[143]='GuiGenerality risk ticket likelihood severity priority urgency';
$slide[144]='Severity'; $slideName[144]='Severity'; $slidePage['Severity']='144'; $slideTags[144]='severity'; $slideTopics[144]='GuiGenerality risk criticality likelihood';
$slide[145]='Urgency'; $slideName[145]='Urgency'; $slidePage['Urgency']='145'; $slideTags[145]='urgency priority'; $slideTopics[145]='GuiGenerality ticket priority criticality';
$slide[146]='Priority'; $slideName[146]='Priority'; $slidePage['Priority']='146'; $slideTags[146]='priority urgency'; $slideTopics[146]='GuiGenerality urgency criticality ticket';
$slide[147]='RiskLevel'; $slideName[147]='Risk level'; $slidePage['RiskLevel']='147'; $slideTags[147]='risk level'; $slideTopics[147]='GuiGenerality';
$slide[148]='Feasibility'; $slideName[148]='Feasibility'; $slidePage['Feasibility']='148'; $slideTags[148]='feasibility'; $slideTopics[148]='GuiGenerality';
$slide[149]='Efficiency'; $slideName[149]='Efficiency'; $slidePage['Efficiency']='149'; $slideTags[149]='efficiency'; $slideTopics[149]='GuiGenerality Action';
$slide[150]='PredefinedNote'; $slideName[150]='Predefined note'; $slidePage['PredefinedNote']='150'; $slideTags[150]='predefined note text'; $slideTopics[150]='Notes';
$slide[151]='Workflow'; $slideName[151]='Workflow description'; $slidePage['Workflow']='151'; $slideTags[151]='workflow status'; $slideTopics[151]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[152]='Workflow'; $slideName[152]='Workflow table'; $slidePage['WorkflowTable']='152'; $slideTags[152]='workflow status'; $slideTopics[152]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[153]='StatusMail'; $slideName[153]='Mail on events'; $slidePage['StatusMail']='153'; $slideTags[153]='mail emailing status'; $slideTopics[153]='GuiGenerality Mail Status AutomaticEmailing ReplyToEmails SendMail';
$slide[154]='ReplyToEmail'; $slideName[154]='Reply to emails'; $slidePage['ReplyToEmail']='154'; $slideTags[154]='mail emailing reply'; $slideTopics[154]='GuiGenerality MailAutomaticEmailing';
$slide[155]='TicketDelay'; $slideName[155]='Delay for tickets'; $slidePage['TicketDelay']='155'; $slideTags[155]='delay ticket'; $slideTopics[155]='GuiGenerality Ticket';
$slide[156]='IndicatorDefinition'; $slideName[156]='Indicator'; $slidePage['IndicatorDefinition']='156'; $slideTags[156]='delay indicator alert warning'; $slideTopics[156]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality SendMail';
$slide[157]='ChecklistDefinition'; $slideName[157]='Checklist definition'; $slidePage['ChecklistDefinition']='157'; $slideTags[157]='checklist quality'; $slideTopics[157]='Checklist';
$slide[158]='ProjectType'; $slideName[158]='Project type'; $slidePage['ProjectType']='158'; $slideTags[158]='project type template administrative operational billing'; $slideTopics[158]='Project Bill';
$slide[159]='TicketType'; $slideName[159]='Ticket type'; $slidePage['TicketType']='159'; $slideTags[159]='type ticket'; $slideTopics[159]='Ticket GuiGenerality';
$slide[160]='ActivityType'; $slideName[160]='Activity type'; $slidePage['ActivityType']='160'; $slideTags[160]='activity type'; $slideTopics[160]='Activity GuiGenerality';
$slide[161]='MilestoneType'; $slideName[161]='Milestone type'; $slidePage['MilestoneType']='161'; $slideTags[161]='milestone type'; $slideTopics[161]='Milestone GuiGenerality';
$slide[162]='QuotationType'; $slideName[162]='Quotation type'; $slidePage['MilestoneType']='162'; $slideTags[162]='quotation type'; $slideTopics[162]='Order Bill GuiGenerality';
$slide[163]='CommandType'; $slideName[163]='Order type'; $slidePage['CommandType']='163'; $slideTags[163]='order type'; $slideTopics[163]='Quotation Bill GuiGenerality';
$slide[164]='IndividualExpenseType'; $slideName[164]='Individual expense type'; $slidePage['IndividualExpenseType']='164'; $slideTags[164]='expense type'; $slideTopics[164]='IndividualExpense GuiGenerality';
$slide[165]='ProjectExpenseType'; $slideName[165]='Project expensetype'; $slidePage['ProjectExpenseType']='165'; $slideTags[165]='expense type'; $slideTopics[165]='ProjectExpense GuiGenerality';
$slide[166]='ExpenseDetailType'; $slideName[166]='Expense detail type'; $slidePage['ExpenseDetailType']='166'; $slideTags[166]='expense type'; $slideTopics[166]='IndividualExpense ProjectExpense GuiGenerality';
$slide[167]='BillType'; $slideName[167]='Bill type'; $slidePage['BillType']='167'; $slideTags[167]='bill type'; $slideTopics[167]='Bill GuiGenerality Creation Update Delete';
$slide[168]='RiskType'; $slideName[168]='Risk type'; $slidePage['RiskType']='168'; $slideTags[168]='risk type'; $slideTopics[168]='Risk GuiGenerality Creation Update Delete';
$slide[169]='RiskType'; $slideName[169]='Opportunity type'; $slidePage['Opportunity Type']='169'; $slideTags[169]='opportunity type'; $slideTopics[169]='Opportunity GuiGenerality Creation Update Delete';
$slide[170]='ActionType'; $slideName[170]='Action type'; $slidePage['ActionType']='170'; $slideTags[170]='action type'; $slideTopics[170]='Action GuiGenerality Creation Update Delete';
$slide[171]='IssueType'; $slideName[171]='Issue type'; $slidePage['IssueType']='171'; $slideTags[171]='issue type'; $slideTopics[171]='Issue GuiGenerality Creation Update Delete';
$slide[172]='MeetingType'; $slideName[172]='Meeting type'; $slidePage['MeetingType']='172'; $slideTags[172]='meeting type'; $slideTopics[172]='Meeting GuiGenerality Creation Update Delete';
$slide[173]='DecisionType'; $slideName[173]='Decision type'; $slidePage['DecisionType']='173'; $slideTags[173]='decision type'; $slideTopics[173]='Decision GuiGenerality Creation Update Delete';
$slide[174]='QuestionType'; $slideName[174]='Question type'; $slidePage['QuestionType']='174'; $slideTags[174]='question type'; $slideTopics[174]='Question GuiGenerality Creation Update Delete';
$slide[175]='MessageType'; $slideName[175]='Message type'; $slidePage['MessageType']='175'; $slideTags[175]='message type'; $slideTopics[175]='Message GuiGenerality Creation Update Delete';
$slide[176]='DocumentType'; $slideName[176]='Document type'; $slidePage['DocumentType']='176'; $slideTags[176]='document type'; $slideTopics[176]='Document GuiGenerality Creation Update Delete';
$slide[177]='ContextType'; $slideName[177]='Context type'; $slidePage['ContextType']='177'; $slideTags[177]='context type'; $slideTopics[177]='Context GuiGenerality Creation Update Delete';
$slide[178]='RequirementType'; $slideName[178]='Requirement type'; $slidePage['RequirementType']='178'; $slideTags[178]='requirement type'; $slideTopics[178]='Requirement GuiGenerality Creation Update Delete';
$slide[179]='TestCaseType'; $slideName[179]='Test case type'; $slidePage['TestCaseType']='179'; $slideTags[179]='test case type'; $slideTopics[179]='TestCase GuiGenerality Creation Update Delete';
$slide[180]='TestSessionType'; $slideName[180]='Test session type'; $slidePage['TestSessionType']='180'; $slideTags[180]='test session type'; $slideTopics[180]='TestSession GuiGenerality Creation Update Delete';
$slide[181]='Profile'; $slideName[181]='Profile'; $slidePage['Profile']='181'; $slideTags[181]='connection profile'; $slideTopics[181]='TranslatableName User';
$slide[182]='AccessProfile'; $slideName[182]='Access mode'; $slidePage['AccessProfile']='182'; $slideTags[182]='access mode read write update delete'; $slideTopics[182]='TranslatableName User Resource Profile';
$slide[183]='Habilitation'; $slideName[183]='Access to forms'; $slidePage['Habilitation']='183'; $slideTags[183]='ticket bug task track habilitation'; $slideTopics[183]='Profile AccessRight';
$slide[184]='HabilitationReport'; $slideName[184]='Access to reports'; $slidePage['HabilitationReport']='184'; $slideTags[184]='access report rights'; $slideTopics[184]='Profile';
$slide[185]='AccessRight'; $slideName[185]='Access mode to data'; $slidePage['AccessMode']='185'; $slideTags[185]='access screen form rights'; $slideTopics[185]='Profile Habilitation';
$slide[186]='HabilitationOther'; $slideName[186]='Specific access mode'; $slidePage['HabilitationOther']='186'; $slideTags[186]='access specific'; $slideTopics[186]='User Profile GuiCombo';
$slide[187]='HabilitationOther'; $slideName[187]='Specific access mode'; $slidePage['HabilitationOther2']='187'; $slideTags[187]='access specific'; $slideTopics[187]='User Profile GuiCombo';
$slide[188]='Administration'; $slideName[188]='Administration'; $slidePage['Administration']='188'; $slideTags[188]='administration cron maintenance purge'; $slideTopics[188]='';
$slide[189]='Audit'; $slideName[189]='Audit connections'; $slidePage['Audit']='189'; $slideTags[189]='connections who_is_online'; $slideTopics[189]='';
$slide[190]='GlobalParameter'; $slideName[190]='Global parameters'; $slidePage['GlobalParameter']='190'; $slideTags[190]='parameters work hour day unit planning responsible'; $slideTopics[190]='';
$slide[191]='GlobalParameter'; $slideName[191]='Global parameters'; $slidePage['GlobalParameter2']='191'; $slideTags[191]='parameters user password ldap'; $slideTopics[191]='';
$slide[192]='GlobalParameter'; $slideName[192]='Global parameters'; $slidePage['GlobalParameter3']='192'; $slideTags[192]='parameters format reference localization internationalizatin language'; $slideTopics[192]='';
$slide[193]='GlobalParameter'; $slideName[193]='Global parameters'; $slidePage['GlobalParameter4']='193'; $slideTags[193]='parameters icons theme files directories billing'; $slideTopics[193]='';
$slide[194]='GlobalParameter'; $slideName[194]='Global parameters'; $slidePage['GlobalParameter5']='194'; $slideTags[194]='parameters cron email'; $slideTopics[194]='';
$slide[195]='GlobalParameter'; $slideName[195]='Global parameters'; $slidePage['GlobalParameter6']='195'; $slideTags[195]='parameters email'; $slideTopics[195]='';
$slide[196]='GlobalParameter'; $slideName[196]='Global parameters'; $slidePage['GlobalParameter7']='196'; $slideTags[196]='parameters email'; $slideTopics[196]='';
$slide[197]='UserParameter'; $slideName[197]='User parameters'; $slidePage['UserParameter']='197'; $slideTags[197]='parameters'; $slideTopics[197]='';
$slide[198]='TranslatableName'; $slideName[198]='Translatable name'; $slidePage['translatableName']='198'; $slideTags[198]='translatable translation name profile'; $slideTopics[198]='AccessProfile ConnectionProfile ';
$slide[199]='AutomaticEmailing'; $slideName[199]='Automatic emailing'; $slidePage['AutomaticEmailing']='199'; $slideTags[199]='automatic email mail'; $slideTopics[199]='Mail SendMail Status GuiGenerality Creation Update Delete';
$slide[200]='API'; $slideName[200]='api'; $slidePage['api']='200'; $slideTags[200]='api'; $slideTopics[200]='';
$slide[201]='API'; $slideName[201]='call api'; $slidePage['apiCode']='201'; $slideTags[201]='api'; $slideTopics[201]='';
$slide[202]='LinkedElements'; $slideName[202]='Linked elements'; $slidePage['LinkedElements']='202'; $slideTags[202]='link linked'; $slideTopics[202]='';
$slide[203]='Attachments'; $slideName[203]='Attachments'; $slidePage['Attachments']='203'; $slideTags[203]='attach file link privacy'; $slideTopics[203]='Ticket Activity Milestone Risk Issue Meeting Decision Question Parameters4 UserParameters';
$slide[204]='Notes'; $slideName[204]='Notes'; $slidePage['Notes']='204'; $slideTags[204]='note comment privacy predefined'; $slideTopics[204]='Ticket Activity Milestone Risk Action Issue Meeting Decision Question UserParameters';
$slide[205]='ChangeHistory'; $slideName[205]='Change history'; $slidePage['ChangeHistory']='205'; $slideTags[205]='change history track update'; $slideTopics[205]='UserParameters';
$slide[206]='Backup'; $slideName[206]='Backup / Restore'; $slidePage['Backup']='206'; $slideTags[206]='backup restore'; $slideTopics[206]='';
$slide[207]='Shortcuts'; $slideName[207]='Shortcuts'; $slidePage['Shortcuts']='207'; $slideTags[207]='shortcut key'; $slideTopics[207]='';
$slide[208]='LastWords'; $slideName[208]='Last words'; $slidePage['LastWords']='208'; $slideTags[208]='murphy hofstader history version'; $slideTopics[208]='';

if (! isset($includeManual)) {
  foreach ($slide as $id=>$name) {
    echo 'slide[' . $id . ']=' . $name . '<br/>';
  }
}

$prec='';
foreach ($slide as $id=>$name) {
  if (substr($name,0,2)=='X ') {
    unset($slide[$id]);
    unset($slideName[$id]);
    unset($slidePage[$id]);
    unset($slideTags[$id]);
    unset($slideTopics[$id]);
  } else {
    if ($name!=$prec) {
      $section[$id]=$name;
      $sectionName[$name]=$slideName[$id];
      $prec=$name;
    }
  }
}
$tags=array();
foreach ($slideTags as $id=>$name) {
 $split=explode(" ",$name);
 foreach ($split as $tag) {
   if (trim($tag) and !array_key_exists($tag, $tags)) {
     $tags[$tag]=array();
   }
   $tags[$tag][]=$id;
 }
}
ksort($tags);